const initialSessions = [
  {
    domain: "Technical",
    topics: "",
    year: "1st", // changed from "1st Year"
    trainer: "Kishor Jashnani",
    date: "2025-02-21",
    campus: "IIMP",
    batch: "FB 5",
    studentCount: "",
    time: "09:30 - 12:30",
    hrs: "3",
    costPerHrs: "1500",
    costPerDay: "4500",
    foodLodging: "",
    travel: "",
    totalAmount: "54000",
    particular: "Training Cost",
    total: "54,000",
    status: "",
    topicCovered: "AI in Excel",
    actualStudentCount: "70"
  },
  {
    domain: "Technical",
    topics: "",
    year: "1st", // changed from "1st Year"
    trainer: "Kishor Jashnani",
    date: "2025-02-21",
    campus: "IIMP",
    batch: "FB 6",
    studentCount: "",
    time: "13:30 - 16:30",
    hrs: "3",
    costPerHrs: "1500",
    costPerDay: "4500",
    foodLodging: "",
    travel: "",
    totalAmount: "5400.0",
    particular: "10% TDS",
    total: "",
    status: "",
    topicCovered: "AI in Excel",
    actualStudentCount: "67"
  },
  {
    domain: "Technical",
    topics: "",
    year: "1st", // changed from "1st Year"
    trainer: "Kishor Jashnani",
    date: "2025-02-22",
    campus: "IIMP",
    batch: "FB 5",
    studentCount: "",
    time: "09:30 - 12:30",
    hrs: "3",
    costPerHrs: "1500",
    costPerDay: "4500",
    foodLodging: "",
    travel: "",
    totalAmount: "48600",
    particular: "Total",
    total: "48,600",
    status: "",
    topicCovered: "AI in Excel",
    actualStudentCount: "61"
  },
  {
    domain: "Technical",
    topics: "",
    year: "1st", // changed from "1st Year"
    trainer: "Kishor Jashnani",
    date: "2025-02-22",
    campus: "IIMP",
    batch: "FB 6",
    studentCount: "",
    time: "13:30 - 16:30",
    hrs: "3",
    costPerHrs: "1500",
    costPerDay: "4500",
    foodLodging: "",
    travel: "",
    totalAmount: "",
    particular: "Miscellaneous cost",
    total: "0",
    status: "",
    topicCovered: "AI in Excel",
    actualStudentCount: "59"
  },
  {
    domain: "Technical",
    topics: "",
    year: "1st", // changed from "1st Year"
    trainer: "Kishor Jashnani",
    date: "2025-02-23",
    campus: "IIMP",
    batch: "FB 5",
    studentCount: "",
    time: "09:30 - 12:30",
    hrs: "3",
    costPerHrs: "1500",
    costPerDay: "4500",
    foodLodging: "",
    travel: "",
    totalAmount: "48600",
    particular: "Total Payable Amount",
    total: "48,600",
    status: "",
    topicCovered: "AI in Excel",
    actualStudentCount: "71"
  },
  {
    domain: "Softskills",
    topics: "Communication",
    year: "1st", // changed from "1st Year"
    trainer: "Amita",
    date: "2025-02-21",
    campus: "IIMP",
    batch: "ALL",
    studentCount: "",
    time: "09:30 - 16:30", // updated
    hrs: "6",
    costPerHrs: "1000",
    costPerDay: "6000",
    foodLodging: "1000",
    travel: "1500",
    totalAmount: "36500",
    particular: "Training Cost",
    total: "30,000",
    status: "",
    topicCovered: "Verbal and non-verbal Communication,Barriers to Communicaion,Elements of Communication,3 and 11C's of communication, Real life Examples of Business Failures.",
    actualStudentCount: "45"
  },
  {
    domain: "Softskills",
    topics: "Communication",
    year: "1st", // changed from "1st Year"
    trainer: "Amita",
    date: "2025-02-22",
    campus: "IIMP",
    batch: "ALL",
    studentCount: "",
    time: "09:30 - 16:30", // updated
    hrs: "6",
    costPerHrs: "1000",
    costPerDay: "6000",
    foodLodging: "1000",
    travel: "",
    totalAmount: "",
    particular: "10% TDS",
    total: "3000.0",
    status: "",
    topicCovered: "SWOT Analysis,Topics in GD, Mock Interviews, Body Language, Hand Gestures, Mock Group Discussion, Resume Writing, Email Writing.",
    actualStudentCount: "45"
  },
  {
    domain: "Softskills",
    topics: "Communication",
    year: "1st", // changed from "1st Year"
    trainer: "Amita",
    date: "2025-02-27",
    campus: "IIMP",
    batch: "HR",
    studentCount: "",
    time: "09:30 - 16:30", // updated
    hrs: "6",
    costPerHrs: "1000",
    costPerDay: "6000",
    foodLodging: "1000",
    travel: "",
    totalAmount: "",
    particular: "Total",
    total: "27,000",
    status: "",
    topicCovered: "",
    actualStudentCount: ""
  },
  {
    domain: "Softskills",
    topics: "Communication",
    year: "1st", // changed from "1st Year"
    trainer: "Amita",
    date: "2025-02-28",
    campus: "IIMP",
    batch: "HR",
    studentCount: "",
    time: "09:30 - 16:30", // updated
    hrs: "6",
    costPerHrs: "1000",
    costPerDay: "6000",
    foodLodging: "1000",
    travel: "",
    totalAmount: "",
    particular: "Miscellaneous cost",
    total: "6,500",
    status: "",
    topicCovered: "",
    actualStudentCount: ""
  },
  {
    domain: "Softskills",
    topics: "SIP into PPO",
    year: "1st", // changed from "1st Year"
    trainer: "Amita",
    date: "2025-03-01",
    campus: "IIMP",
    batch: "HR",
    studentCount: "",
    time: "09:30 - 16:30", // updated
    hrs: "6",
    costPerHrs: "1000",
    costPerDay: "6000",
    foodLodging: "1000",
    travel: "",
    totalAmount: "",
    particular: "Total Payable Amount",
    total: "33,500",
    status: "",
    topicCovered: "",
    actualStudentCount: ""
  },
  {
    domain: "Aptitude",
    topics: "",
    year: "1st", // changed from "1st Year"
    trainer: "Pritesh Cumble",
    date: "2025-02-22",
    campus: "IIMP",
    batch: "HR",
    studentCount: "",
    time: "09:30 - 16:30", // updated
    hrs: "6",
    costPerHrs: "1000",
    costPerDay: "6000",
    foodLodging: "750",
    travel: "1500",
    totalAmount: "42000",
    particular: "Training Cost",
    total: "36,000",
    status: "",
    topicCovered: "Percentage, Profit and Loss,  Ratio proportion, Blood Relation, Direction",
    actualStudentCount: "35"
  },
  {
    domain: "Aptitude",
    topics: "",
    year: "1st", // changed from "1st Year"
    trainer: "Pritesh Cumble",
    date: "2025-02-23",
    campus: "IIMP",
    batch: "MB 7",
    studentCount: "",
    time: "13:30 - 16:30", // updated
    hrs: "3",
    costPerHrs: "1000",
    costPerDay: "3000",
    foodLodging: "750",
    travel: "",
    totalAmount: "",
    particular: "10% TDS",
    total: "3600.0",
    status: "",
    topicCovered: "Percentage,Number Series",
    actualStudentCount: "41"
  },
  {
    domain: "Aptitude",
    topics: "",
    year: "1st", // changed from "1st Year"
    trainer: "Pritesh Cumble",
    date: "2025-02-23",
    campus: "IIMP",
    batch: "MB 8",
    studentCount: "",
    time: "09:30 - 12:30", // updated
    hrs: "3",
    costPerHrs: "1000",
    costPerDay: "3000",
    foodLodging: "",
    travel: "",
    totalAmount: "",
    particular: "Total",
    total: "32,400",
    status: "",
    topicCovered: "Percentage,Number Series",
    actualStudentCount: "47"
  },
  {
    domain: "Aptitude",
    topics: "",
    year: "1st", // changed from "1st Year"
    trainer: "Pritesh Cumble",
    date: "2025-02-24",
    campus: "IIMP",
    batch: "MB 7",
    studentCount: "",
    time: "13:30 - 16:30", // updated
    hrs: "3",
    costPerHrs: "1000",
    costPerDay: "3000",
    foodLodging: "750",
    travel: "",
    totalAmount: "",
    particular: "Miscellaneous cost",
    total: "6,000",
    status: "",
    topicCovered: "Profit & Loss, Blood Relation",
    actualStudentCount: "45"
  },
  {
    domain: "Aptitude",
    topics: "",
    year: "1st", // changed from "1st Year"
    trainer: "Pritesh Cumble",
    date: "2025-02-24",
    campus: "IIMP",
    batch: "MB 8",
    studentCount: "",
    time: "09:30 - 12:30", // updated
    hrs: "3",
    costPerHrs: "1000",
    costPerDay: "3000",
    foodLodging: "",
    travel: "",
    totalAmount: "",
    particular: "Total Payable Amount",
    total: "38,400",
    status: "",
    topicCovered: "Profit & Loss, Blood Relation",
    actualStudentCount: "50"
  },
  // ...continue adding all other rows you provided in the same format...
];

export default initialSessions;
