import React, { useState } from 'react';

const QRCodeGenerator = ({ invoiceNumber }) => {
  const [showPopup, setShowPopup] = useState(false);

  const generateQRCode = () => {
    const qrText = `INVOICE:${invoiceNumber}`;
    return `https://quickchart.io/qr?text=${encodeURIComponent(qrText)}&size=120`;
  };

  const handleQRClick = () => {
    setShowPopup(true);
  };

  const closePopup = () => {
    setShowPopup(false);
  };

  return (
    <>
      <div className="qr-code-container text-center">
        <img 
          src={generateQRCode()} 
          alt="QR Code" 
          className="mx-auto border border-gray-300 cursor-pointer hover:border-blue-500 transition-colors"
          onClick={handleQRClick}
          title="Click to view invoice details"
          style={{ width: '120px', height: '120px' }}
          onError={(e) => {
            e.target.src = `https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=INVOICE:${invoiceNumber}`;
          }}
        />
        <p className="text-xs text-gray-600 mt-1">Scan QR Code</p>
      </div>

      {/* Custom Popup Modal */}
      {showPopup && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-1000">
          <div className="bg-white p-6 rounded-lg shadow-xl max-w-sm mx-4">
            <div className="text-center">
              <h3 className="text-lg font-bold text-gray-800 mb-4">
                Invoice Verification
              </h3>
              
              <div className="mb-4 p-3 bg-blue-50 rounded">
                <p className="text-sm text-gray-600">Invoice Number</p>
                <p className="text-xl font-bold text-blue-800">{invoiceNumber}</p>
              </div>

              <div className="mb-4 p-2 bg-green-50 rounded">
                <p className="text-xs text-green-700">
                  ✅ Verified by Gryphon Academy Pvt Ltd
                </p>
              </div>

              <div className="text-xs text-gray-500 mb-4">
                This QR code contains authentic invoice information 
                generated by Gryphon Academy Pvt Ltd
              </div>

              <button
                onClick={closePopup}
                className="bg-blue-600 text-white px-6 py-2 rounded hover:bg-blue-700 font-semibold transition-colors"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default QRCodeGenerator;