const tasksData = [
  { account: 'ICEM', role: 'Social Media', task: 'Pre Training Creative' },
  { account: 'ICEM', role: 'Social Media', task: 'Post Training Creative' },
  { account: 'ICEM', role: 'Social Media', task: 'Pre Placement Creative' },
  { account: 'ICEM', role: 'Social Media', task: 'Post Placement Drive Creative' },
  { account: 'ICEM', role: 'Social Media', task: 'Placement after Drive Creative' },
  { account: 'ICEM', role: 'Social Media', task: 'Festival Creatives' },
  { account: 'ICEM', role: 'Social Media', task: 'Reel cover page' },
  { account: 'ICEM', role: 'Social Media', task: 'Google banners' },
  { account: 'ICEM', role: 'Social Media', task: 'Linkedin banners' },
  { account: 'ICEM', role: 'Social Media', task: 'Whats app Creatives' },
  { account: 'ICEM', role: 'Social Media', task: 'Blog cover page' },
  { account: 'ICEM', role: 'Social Media', task: 'Hiring Creative' },
  { account: 'ICEM', role: 'Social Media', task: 'Emplyoee Creatives' },
  { account: 'ICEM', role: 'Social Media', task: 'Post Event Creative' },
  { account: 'ICEM', role: 'Social Media', task: 'Pre event Creatives' },
  { account: 'ICEM', role: 'Social Media', task: 'Admission Creatives' },
  { account: 'ICEM', role: 'Social Media', task: 'Emailers' },
  { account: 'ICEM', role: 'Social Media', task: 'Content Creatives' },
  { account: 'ICEM', role: 'Digital Media', task: 'Brochures' },
  { account: 'ICEM', role: 'Digital Media', task: 'Training Modules' },
  { account: 'ICEM', role: 'Digital Media', task: 'Certificates ' },
  { account: 'ICEM', role: 'Digital Media', task: 'Symols, Stamp and Logos format' },
  { account: 'ICEM', role: 'Digital Media', task: 'Website images' },
  { account: 'ICEM', role: 'Digital Media', task: 'Websites Banners' },
  { account: 'ICEM', role: 'Digital Media', task: 'Website Design' },
  { account: 'ICEM', role: 'Digital Media', task: 'Trainers Profile' },
  { account: 'ICEM', role: 'Print Media', task: 'External Hoardings' },
  { account: 'ICEM', role: 'Print Media', task: 'Internal Hoardings' },
  { account: 'ICEM', role: 'Print Media', task: 'Standees' },
  { account: 'ICEM', role: 'Print Media', task: 'Newspaper' },
  { account: 'ICEM', role: 'Print Media', task: 'Brochure' },
  { account: 'ICEM', role: 'Print Media', task: 'Event Print Media' },
  { account: 'ICEM', role: 'Print Media', task: 'Office Print Media' },
  { account: 'ICEM', role: 'Event', task: 'Logo' },
  { account: 'ICEM', role: 'Event', task: 'Invites' },
  { account: 'ICEM', role: 'Event', task: 'Pre Event Creatives' },
  { account: 'ICEM', role: 'Event', task: 'Post Event Creatives' },
  { account: 'ICEM', role: 'Event', task: 'Agenda' },
  { account: 'ICEM', role: 'Ad Videos', task: 'Admissions Reel' },
  { account: 'ICEM', role: 'Social Media', task: 'Festival Reel' },
  { account: 'ICEM', role: 'Social Media', task: 'Training Reel' },
  { account: 'ICEM', role: 'Social Media', task: 'Placement Reel' },
  { account: 'ICEM', role: 'Social Media', task: 'Internal Branding Reel' },
  { account: 'ICEM', role: 'Social Media', task: 'Content Creation' },
  { account: 'ICEM', role: 'Social Media', task: 'Motion Videos' },
  { account: 'ICEM', role: 'Event', task: 'AV' },
  { account: 'ICEM', role: 'Event', task: 'Pre Branding Reel' },
  { account: 'ICEM', role: 'Event', task: 'Post Branding Reel' },
  { account: 'ICEM', role: 'Social Media', task: 'Pre Training Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Post Training Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Pre Placement Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Post Placement Drive Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Placement after Drive Creative Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Festival Creatives Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Reel cover page Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Google banners Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Linkedin banners Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Whats app Creatives Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Blog cover page Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Hiring Creative Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Emplyoee Creatives Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Post Event Creative Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Pre event Creatives Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Admission Creatives Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Emailers Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Content Creatives Content' },
  { account: 'ICEM', role: 'Social Media', task: 'Caption' },
  { account: 'ICEM', role: 'Ad Videos', task: 'Admissions Scripts' },
  { account: 'ICEM', role: 'Social Media', task: 'Festival Reel Script' },
  { account: 'ICEM', role: 'Social Media', task: 'Training Reel Script' },
  { account: 'ICEM', role: 'Social Media', task: 'Placement Reel Script' },
  { account: 'ICEM', role: 'Social Media', task: 'Internal Branding Reel Script' },
  { account: 'ICEM', role: 'Social Media', task: 'Content Creation Script' },
  { account: 'ICEM', role: 'Social Media', task: 'Motion Videos Script' },
  { account: 'ICEM', role: 'Event', task: 'AV Script' },
  { account: 'ICEM', role: 'Event', task: 'Pre Branding Reel Script' },
  { account: 'ICEM', role: 'Event', task: 'Post Branding Reel Script' },
  { account: 'ICEM', role: 'Digital Media', task: 'Brochures Content' },
  { account: 'ICEM', role: 'Digital Media', task: 'Training Modules Content' },
  { account: 'ICEM', role: 'Digital Media', task: 'Certificates Content' },
  { account: 'ICEM', role: 'Digital Media', task: 'Trainers Profile Content' },
  { account: 'ICEM', role: 'Print Media', task: 'External Hoardings Content' },
  { account: 'ICEM', role: 'Print Media', task: 'Internal Hoardings Content' },
  { account: 'ICEM', role: 'Print Media', task: 'Standees Content' },
  { account: 'ICEM', role: 'Print Media', task: 'Newspaper Content' },
  { account: 'ICEM', role: 'Print Media', task: 'Brochure Content' },
  { account: 'ICEM', role: 'Print Media', task: 'Event Print Media Content' },
  { account: 'ICEM', role: 'Print Media', task: 'Office Print Media Content' },
  { account: 'ICEM', role: 'Content Calendar', task: 'Weekly content Calender' },
  { account: 'ICEM', role: 'Blog Creation', task: 'Trending Topics' },
  { account: 'ICEM', role: 'Blog Creation', task: 'Technical' },
  { account: 'ICEM', role: 'Blog Creation', task: 'Branding' },
  { account: 'ICEM', role: 'SEO', task: 'Website Content' },
  { account: 'ICEM', role: 'SEO', task: 'Landing Page Content' },
  { account: 'ICEM', role: 'SEO', task: 'Ad Copies Content' },
  { account: 'ICEM', role: 'Event', task: 'Pre event Creatives Content' },
  { account: 'ICEM', role: 'Event', task: 'Post Event Creatives Content' },
  { account: 'ICEM', role: 'Event', task: 'Agenda Content' },
  { account: 'ICEM', role: 'Event', task: 'Concept Note Content' },
  { account: 'ICEM', role: 'Event', task: 'Invites Content' },
  { account: 'ICEM', role: 'Event', task: 'Agenda Content' },
  { account: 'ICEM', role: 'Event', task: 'Mail drafts' },
  { account: 'ICEM', role: 'Event', task: 'Guest List tracker & maintenance' },
  { account: 'ICEM', role: 'Proof reading', task: '' },
  { account: 'ICEM', role: 'Social Media', task: 'Pre Training Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Post Training Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Pre Placement Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Post Placement Drive Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Placement after Drive Creative Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Festival Creatives Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Reel cover page Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Google banners Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Linkedin banners Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Whats app Creatives Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Blog cover page Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Hiring Creative Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Emplyoee Creatives Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Post Event Creative Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Pre event Creatives Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Admission Creatives Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Emailers Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Posting Creatives Posting' },
  { account: 'ICEM', role: 'Ad Videos', task: 'Admissions Reel Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Festival Reel Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Training Reel Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Placement Reel Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Internal Branding Reel Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Content Creation Reel Posting' },
  { account: 'ICEM', role: 'Social Media', task: 'Motion Video Posting' },
  { account: 'ICEM', role: 'Event', task: 'AV' },
  { account: 'ICEM', role: 'Event', task: 'Pre Branding Reel' },
  { account: 'ICEM', role: 'Event', task: 'Post Branding Reel' },
  { account: 'ICEM', role: 'PPT', task: 'Content Creation PPT' },
  { account: 'ICEM', role: 'PPT', task: 'Sales PPT' },
  { account: 'ICEM', role: 'PPT', task: 'Onboarding PPT' },
  { account: 'ICEM', role: 'PPT', task: 'Induction PPT' },
  { account: 'ICEM', role: 'PPT', task: 'Pitch Deck PPT' },
  { account: 'ICEM', role: 'PPT', task: 'Review PPT' },
  { account: 'ICEM', role: 'PPT', task: 'Topic Covered PPT' },
  { account: 'ICEM', role: 'Ad campaigns', task: 'Ad campaigns Set up' },
  { account: 'ICEM', role: 'Ad campaigns', task: 'Ad campaign Optimization' },
  { account: 'ICEM', role: 'Ad campaigns', task: 'Lead Status tracking' },
  { account: 'ICEM', role: 'Event', task: 'Event PPT' },
  { account: 'ICEM', role: 'Event', task: 'Backdrops' },
  { account: 'ICEM', role: 'Event', task: 'Console Music' },
  { account: 'ICEM', role: 'Co-ordination', task: 'IU Team' },
  { account: 'ICEM', role: 'Co-ordination', task: 'ICEM Team' },
  { account: 'ICEM', role: 'Co-ordination', task: 'Vendors' },
  { account: 'ICEM', role: 'Follow up', task: 'External Hoardings' },
  { account: 'ICEM', role: 'Follow up', task: 'Internal Hoardings' },
  { account: 'ICEM', role: 'Follow up', task: 'Standees' },
  { account: 'ICEM', role: 'Follow up', task: 'Newspaper' },
  { account: 'ICEM', role: 'Follow up', task: 'Brochure' },
  { account: 'ICEM', role: 'Follow up', task: 'Event Print Media' },
  { account: 'ICEM', role: 'Follow up', task: 'Office Print Media' },
  { account: 'IU', role: 'Social Media', task: 'Pre Training Creative' },
  { account: 'IU', role: 'Social Media', task: 'Post Training Creative' },
  { account: 'IU', role: 'Social Media', task: 'Pre Placement Creative' },
  { account: 'IU', role: 'Social Media', task: 'Post Placement Drive Creative' },
  { account: 'IU', role: 'Social Media', task: 'Placement after Drive Creative' },
  { account: 'IU', role: 'Social Media', task: 'Festival Creatives' },
  { account: 'IU', role: 'Social Media', task: 'Reel cover page' },
  { account: 'IU', role: 'Social Media', task: 'Google banners' },
  { account: 'IU', role: 'Social Media', task: 'Linkedin banners' },
  { account: 'IU', role: 'Social Media', task: 'Whats app Creatives' },
  { account: 'IU', role: 'Social Media', task: 'Blog cover page' },
  { account: 'IU', role: 'Social Media', task: 'Hiring Creative' },
  { account: 'IU', role: 'Social Media', task: 'Emplyoee Creatives' },
  { account: 'IU', role: 'Social Media', task: 'Post Event Creative' },
  { account: 'IU', role: 'Social Media', task: 'Pre event Creatives' },
  { account: 'IU', role: 'Social Media', task: 'Admission Creatives' },
  { account: 'IU', role: 'Social Media', task: 'Emailers' },
  { account: 'IU', role: 'Social Media', task: 'Content Creatives' },
  { account: 'IU', role: 'Digital Media', task: 'Brochures' },
  { account: 'IU', role: 'Digital Media', task: 'Training Modules' },
  { account: 'IU', role: 'Digital Media', task: 'Certificates' },
  { account: 'IU', role: 'Digital Media', task: 'Symols, Stamp and Logos format' },
  { account: 'IU', role: 'Digital Media', task: 'Website images' },
  { account: 'IU', role: 'Digital Media', task: 'Websites Banners' },
  { account: 'IU', role: 'Digital Media', task: 'Website Design' },
  { account: 'IU', role: 'Digital Media', task: 'Trainers Profile' },
  { account: 'IU', role: 'Print Media', task: 'External Hoardings' },
  { account: 'IU', role: 'Print Media', task: 'Internal Hoardings' },
  { account: 'IU', role: 'Print Media', task: 'Standees' },
  { account: 'IU', role: 'Print Media', task: 'Newspaper' },
  { account: 'IU', role: 'Print Media', task: 'Brochure' },
  { account: 'IU', role: 'Print Media', task: 'Event Print Media' },
  { account: 'IU', role: 'Print Media', task: 'Office Print Media' },
  { account: 'IU', role: 'Event', task: 'Logo' },
  { account: 'IU', role: 'Event', task: 'Invites' },
  { account: 'IU', role: 'Event', task: 'Pre Event Creatives' },
  { account: 'IU', role: 'Event', task: 'Post Event Creatives' },
  { account: 'IU', role: 'Event', task: 'Agenda' },
  { account: 'IU', role: 'Ad Videos', task: 'Admissions Reel' },
  { account: 'IU', role: 'Social Media', task: 'Festival Reel' },
  { account: 'IU', role: 'Social Media', task: 'Training Reel' },
  { account: 'IU', role: 'Social Media', task: 'Placement Reel' },
  { account: 'IU', role: 'Social Media', task: 'Internal Branding Reel' },
  { account: 'IU', role: 'Social Media', task: 'Content Creation' },
  { account: 'IU', role: 'Social Media', task: 'Motion Videos' },
  { account: 'IU', role: 'Event', task: 'AV' },
  { account: 'IU', role: 'Event', task: 'Pre Branding Reel' },
  { account: 'IU', role: 'Event', task: 'Post Branding Reel' },
  { account: 'IU', role: 'Social Media', task: 'Pre Training Content' },
  { account: 'IU', role: 'Social Media', task: 'Post Training Content' },
  { account: 'IU', role: 'Social Media', task: 'Pre Placement Content' },
  { account: 'IU', role: 'Social Media', task: 'Post Placement Drive Content' },
  { account: 'IU', role: 'Social Media', task: 'Placement after Drive Creative Content' },
  { account: 'IU', role: 'Social Media', task: 'Festival Creatives Content' },
  { account: 'IU', role: 'Social Media', task: 'Reel cover page Content' },
  { account: 'IU', role: 'Social Media', task: 'Google banners Content' },
  { account: 'IU', role: 'Social Media', task: 'Linkedin banners Content' },
  { account: 'IU', role: 'Social Media', task: 'Whats app Creatives Content' },
  { account: 'IU', role: 'Social Media', task: 'Blog cover page Content' },
  { account: 'IU', role: 'Social Media', task: 'Hiring Creative Content' },
  { account: 'IU', role: 'Social Media', task: 'Emplyoee Creatives Content' },
  { account: 'IU', role: 'Social Media', task: 'Post Event Creative Content' },
  { account: 'IU', role: 'Social Media', task: 'Pre event Creatives Content' },
  { account: 'IU', role: 'Social Media', task: 'Admission Creatives Content' },
  { account: 'IU', role: 'Social Media', task: 'Emailers Content' },
  { account: 'IU', role: 'Social Media', task: 'Content Creatives Content' },
  { account: 'IU', role: 'Social Media', task: 'Caption' },
  { account: 'IU', role: 'Ad Videos', task: 'Admissions Scripts' },
  { account: 'IU', role: 'Social Media', task: 'Festival Reel Script' },
  { account: 'IU', role: 'Social Media', task: 'Training Reel Script' },
  { account: 'IU', role: 'Social Media', task: 'Placement Reel Script' },
  { account: 'IU', role: 'Social Media', task: 'Internal Branding Reel Script' },
  { account: 'IU', role: 'Social Media', task: 'Content Creation Script' },
  { account: 'IU', role: 'Social Media', task: 'Motion Videos Script' },
  { account: 'IU', role: 'Event', task: 'AV Script' },
  { account: 'IU', role: 'Event', task: 'Pre Branding Reel Script' },
  { account: 'IU', role: 'Event', task: 'Post Branding Reel Script' },
  { account: 'IU', role: 'Digital Media', task: 'Brochures Content' },
  { account: 'IU', role: 'Digital Media', task: 'Training Modules Content' },
  { account: 'IU', role: 'Digital Media', task: 'Certificates Content' },
  { account: 'IU', role: 'Digital Media', task: 'Trainers Profile Content' },
  { account: 'IU', role: 'Print Media', task: 'External Hoardings Content' },
  { account: 'IU', role: 'Print Media', task: 'Internal Hoardings Content' },
  { account: 'IU', role: 'Print Media', task: 'Standees Content' },
  { account: 'IU', role: 'Print Media', task: 'Newspaper Content' },
  { account: 'IU', role: 'Print Media', task: 'Brochure Content' },
  { account: 'IU', role: 'Print Media', task: 'Event Print Media Content' },
  { account: 'IU', role: 'Print Media', task: 'Office Print Media Content' },
  { account: 'IU', role: 'Content Calendar', task: 'Weekly content Calender' },
  { account: 'IU', role: 'Blog Creation', task: 'Trending Topics' },
  { account: 'IU', role: 'Blog Creation', task: 'Technical' },
  { account: 'IU', role: 'Blog Creation', task: 'Branding' },
  { account: 'IU', role: 'SEO', task: 'Website Content' },
  { account: 'IU', role: 'SEO', task: 'Landing Page Content' },
  { account: 'IU', role: 'SEO', task: 'Ad Copies Content' },
  { account: 'IU', role: 'Event', task: 'Pre event Creatives Content' },
  { account: 'IU', role: 'Event', task: 'Post Event Creatives Content' },
  { account: 'IU', role: 'Event', task: 'Agenda Content' },
  { account: 'IU', role: 'Event', task: 'Concept Note Content' },
  { account: 'IU', role: 'Event', task: 'Invites Content' },
  { account: 'IU', role: 'Event', task: 'Agenda Content' },
  { account: 'IU', role: 'Event', task: 'Mail drafts' },
  { account: 'IU', role: 'Event', task: 'Guest List tracker & maintenance' },
  { account: 'IU', role: 'Proof reading', task: '' },
  { account: 'IU', role: 'Social Media', task: 'Pre Training Posting' },
  { account: 'IU', role: 'Social Media', task: 'Post Training Posting' },
  { account: 'IU', role: 'Social Media', task: 'Pre Placement Posting' },
  { account: 'IU', role: 'Social Media', task: 'Post Placement Drive Posting' },
  { account: 'IU', role: 'Social Media', task: 'Placement after Drive Creative Posting' },
  { account: 'IU', role: 'Social Media', task: 'Festival Creatives Posting' },
  { account: 'IU', role: 'Social Media', task: 'Reel cover page Posting' },
  { account: 'IU', role: 'Social Media', task: 'Google banners Posting' },
  { account: 'IU', role: 'Social Media', task: 'Linkedin banners Posting' },
  { account: 'IU', role: 'Social Media', task: 'Whats app Creatives Posting' },
  { account: 'IU', role: 'Social Media', task: 'Blog cover page Posting' },
  { account: 'IU', role: 'Social Media', task: 'Hiring Creative Posting' },
  { account: 'IU', role: 'Social Media', task: 'Emplyoee Creatives Posting' },
  { account: 'IU', role: 'Social Media', task: 'Post Event Creative Posting' },
  { account: 'IU', role: 'Social Media', task: 'Pre event Creatives Posting' },
  { account: 'IU', role: 'Social Media', task: 'Admission Creatives Posting' },
  { account: 'IU', role: 'Social Media', task: 'Emailers Posting' },
  { account: 'IU', role: 'Social Media', task: 'Posting Creatives Posting' },
  { account: 'IU', role: 'Ad Videos', task: 'Admissions Reel Posting' },
  { account: 'IU', role: 'Social Media', task: 'Festival Reel Posting' },
  { account: 'IU', role: 'Social Media', task: 'Training Reel Posting' },
  { account: 'IU', role: 'Social Media', task: 'Placement Reel Posting' },
  { account: 'IU', role: 'Social Media', task: 'Internal Branding Reel Posting' },
  { account: 'IU', role: 'Social Media', task: 'Content Creation Reel Posting' },
  { account: 'IU', role: 'Social Media', task: 'Motion Video Posting' },
  { account: 'IU', role: 'Event', task: 'AV' },
  { account: 'IU', role: 'Event', task: 'Pre Branding Reel' },
  { account: 'IU', role: 'Event', task: 'Post Branding Reel' },
  { account: 'IU', role: 'PPT', task: 'Content Creation PPT' },
  { account: 'IU', role: 'PPT', task: 'Sales PPT' },
  { account: 'IU', role: 'PPT', task: 'Onboarding PPT' },
  { account: 'IU', role: 'PPT', task: 'Induction PPT' },
  { account: 'IU', role: 'PPT', task: 'Pitch Deck PPT' },
  { account: 'IU', role: 'PPT', task: 'Review PPT' },
  { account: 'IU', role: 'PPT', task: 'Topic Covered PPT' },
  { account: 'IU', role: 'Ad campaigns', task: 'Ad campaigns Set up' },
  { account: 'IU', role: 'Ad campaigns', task: 'Ad campaign Optimization' },
  { account: 'IU', role: 'Ad campaigns', task: 'Lead Status tracking' },
  { account: 'IU', role: 'Event', task: 'Event PPT' },
  { account: 'IU', role: 'Event', task: 'Backdrops' },
  { account: 'IU', role: 'Event', task: 'Console Music' },
  { account: 'IU', role: 'Co-ordination', task: 'IU Team' },
  { account: 'IU', role: 'Co-ordination', task: 'ICEM Team' },
  { account: 'IU', role: 'Co-ordination', task: 'Vendors' },
  { account: 'IU', role: 'Follow up', task: 'External Hoardings' },
  { account: 'IU', role: 'Follow up', task: 'Internal Hoardings' },
  { account: 'IU', role: 'Follow up', task: 'Standees' },
  { account: 'IU', role: 'Follow up', task: 'Newspaper' },
  { account: 'IU', role: 'Follow up', task: 'Brochure' },
  { account: 'IU', role: 'Follow up', task: 'Event Print Media' },
  { account: 'IU', role: 'Follow up', task: 'Office Print Media' },
  { account: 'GA', role: 'Social Media', task: 'Pre Training Creative' },
  { account: 'GA', role: 'Social Media', task: 'Post Training Creative' },
  { account: 'GA', role: 'Social Media', task: 'Pre Placement Creative' },
  { account: 'GA', role: 'Social Media', task: 'Post Placement Drive Creative' },
  { account: 'GA', role: 'Social Media', task: 'Placement after Drive Creative' },
  { account: 'GA', role: 'Social Media', task: 'Festival Creatives' },
  { account: 'GA', role: 'Social Media', task: 'Reel cover page' },
  { account: 'GA', role: 'Social Media', task: 'Google banners' },
  { account: 'GA', role: 'Social Media', task: 'Linkedin banners' },
  { account: 'GA', role: 'Social Media', task: 'Whats app Creatives' },
  { account: 'GA', role: 'Social Media', task: 'Blog cover page' },
  { account: 'GA', role: 'Social Media', task: 'Hiring Creative' },
  { account: 'GA', role: 'Social Media', task: 'Emplyoee Creatives' },
  { account: 'GA', role: 'Social Media', task: 'Post Event Creative' },
  { account: 'GA', role: 'Social Media', task: 'Pre event Creatives' },
  { account: 'GA', role: 'Social Media', task: 'Admission Creatives' },
  { account: 'GA', role: 'Social Media', task: 'Emailers' },
  { account: 'GA', role: 'Social Media', task: 'Content Creatives' },
  { account: 'GA', role: 'Digital Media', task: 'Brochures' },
  { account: 'GA', role: 'Digital Media', task: 'Training Modules' },
  { account: 'GA', role: 'Digital Media', task: 'Certificates' },
  { account: 'GA', role: 'Digital Media', task: 'Symols, Stamp and Logos format' },
  { account: 'GA', role: 'Digital Media', task: 'Website images' },
  { account: 'GA', role: 'Digital Media', task: 'Websites Banners' },
  { account: 'GA', role: 'Digital Media', task: 'Website Design' },
  { account: 'GA', role: 'Digital Media', task: 'Trainers Profile' },
  { account: 'GA', role: 'Print Media', task: 'External Hoardings' },
  { account: 'GA', role: 'Print Media', task: 'Internal Hoardings' },
  { account: 'GA', role: 'Print Media', task: 'Standees' },
  { account: 'GA', role: 'Print Media', task: 'Newspaper' },
  { account: 'GA', role: 'Print Media', task: 'Brochure' },
  { account: 'GA', role: 'Print Media', task: 'Event Print Media' },
  { account: 'GA', role: 'Print Media', task: 'Office Print Media' },
  { account: 'GA', role: 'Event', task: 'Logo' },
  { account: 'GA', role: 'Event', task: 'Invites' },
  { account: 'GA', role: 'Event', task: 'Pre Event Creatives' },
  { account: 'GA', role: 'Event', task: 'Post Event Creatives' },
  { account: 'GA', role: 'Event', task: 'Agenda' },
  { account: 'GA', role: 'Ad Videos', task: 'Admissions Reel' },
  { account: 'GA', role: 'Social Media', task: 'Festival Reel' },
  { account: 'GA', role: 'Social Media', task: 'Training Reel' },
  { account: 'GA', role: 'Social Media', task: 'Placement Reel' },
  { account: 'GA', role: 'Social Media', task: 'Internal Branding Reel' },
  { account: 'GA', role: 'Social Media', task: 'Content Creation' },
  { account: 'GA', role: 'Social Media', task: 'Motion Videos' },
  { account: 'GA', role: 'Event', task: 'AV' },
  { account: 'GA', role: 'Event', task: 'Pre Branding Reel' },
  { account: 'GA', role: 'Event', task: 'Post Branding Reel' },
  { account: 'GA', role: 'Social Media', task: 'Pre Training Content' },
  { account: 'GA', role: 'Social Media', task: 'Post Training Content' },
  { account: 'GA', role: 'Social Media', task: 'Pre Placement Content' },
  { account: 'GA', role: 'Social Media', task: 'Post Placement Drive Content' },
  { account: 'GA', role: 'Social Media', task: 'Placement after Drive Creative Content' },
  { account: 'GA', role: 'Social Media', task: 'Festival Creatives Content' },
  { account: 'GA', role: 'Social Media', task: 'Reel cover page Content' },
  { account: 'GA', role: 'Social Media', task: 'Google banners Content' },
  { account: 'GA', role: 'Social Media', task: 'Linkedin banners Content' },
  { account: 'GA', role: 'Social Media', task: 'Whats app Creatives Content' },
  { account: 'GA', role: 'Social Media', task: 'Blog cover page Content' },
  { account: 'GA', role: 'Social Media', task: 'Hiring Creative Content' },
  { account: 'GA', role: 'Social Media', task: 'Emplyoee Creatives Content' },
  { account: 'GA', role: 'Social Media', task: 'Post Event Creative Content' },
  { account: 'GA', role: 'Social Media', task: 'Pre event Creatives Content' },
  { account: 'GA', role: 'Social Media', task: 'Admission Creatives Content' },
  { account: 'GA', role: 'Social Media', task: 'Emailers Content' },
  { account: 'GA', role: 'Social Media', task: 'Content Creatives Content' },
  { account: 'GA', role: 'Social Media', task: 'Caption' },
  { account: 'GA', role: 'Ad Videos', task: 'Admissions Scripts' },
  { account: 'GA', role: 'Social Media', task: 'Festival Reel Script' },
  { account: 'GA', role: 'Social Media', task: 'Training Reel Script' },
  { account: 'GA', role: 'Social Media', task: 'Placement Reel Script' },
  { account: 'GA', role: 'Social Media', task: 'Internal Branding Reel Script' },
  { account: 'GA', role: 'Social Media', task: 'Content Creation Script' },
  { account: 'GA', role: 'Social Media', task: 'Motion Videos Script' },
  { account: 'GA', role: 'Event', task: 'AV Script' },
  { account: 'GA', role: 'Event', task: 'Pre Branding Reel Script' },
  { account: 'GA', role: 'Event', task: 'Post Branding Reel Script' },
  { account: 'GA', role: 'Digital Media', task: 'Brochures Content' },
  { account: 'GA', role: 'Digital Media', task: 'Training Modules Content' },
  { account: 'GA', role: 'Digital Media', task: 'Certificates Content' },
  { account: 'GA', role: 'Digital Media', task: 'Trainers Profile Content' },
  { account: 'GA', role: 'Print Media', task: 'External Hoardings Content' },
  { account: 'GA', role: 'Print Media', task: 'Internal Hoardings Content' },
  { account: 'GA', role: 'Print Media', task: 'Standees Content' },
  { account: 'GA', role: 'Print Media', task: 'Newspaper Content' },
  { account: 'GA', role: 'Print Media', task: 'Brochure Content' },
  { account: 'GA', role: 'Print Media', task: 'Event Print Media Content' },
  { account: 'GA', role: 'Print Media', task: 'Office Print Media Content' },
  { account: 'GA', role: 'Content Calendar', task: 'Weekly content Calender' },
  { account: 'GA', role: 'Blog Creation', task: 'Trending Topics' },
  { account: 'GA', role: 'Blog Creation', task: 'Technical' },
  { account: 'GA', role: 'Blog Creation', task: 'Branding' },
  { account: 'GA', role: 'SEO', task: 'Website Content' },
  { account: 'GA', role: 'SEO', task: 'Landing Page Content' },
  { account: 'GA', role: 'SEO', task: 'Ad Copies Content' },
  { account: 'GA', role: 'Event', task: 'Pre event Creatives Content' },
  { account: 'GA', role: 'Event', task: 'Post Event Creatives Content' },
  { account: 'GA', role: 'Event', task: 'Agenda Content' },
  { account: 'GA', role: 'Event', task: 'Concept Note Content' },
  { account: 'GA', role: 'Event', task: 'Invites Content' },
  { account: 'GA', role: 'Event', task: 'Agenda Content' },
  { account: 'GA', role: 'Event', task: 'Mail drafts' },
  { account: 'GA', role: 'Event', task: 'Guest List tracker & maintenance' },
  { account: 'GA', role: 'Proof reading', task: '' },
  { account: 'GA', role: 'Social Media', task: 'Pre Training Posting' },
  { account: 'GA', role: 'Social Media', task: 'Post Training Posting' },
  { account: 'GA', role: 'Social Media', task: 'Pre Placement Posting' },
  { account: 'GA', role: 'Social Media', task: 'Post Placement Drive Posting' },
  { account: 'GA', role: 'Social Media', task: 'Placement after Drive Creative Posting' },
  { account: 'GA', role: 'Social Media', task: 'Festival Creatives Posting' },
  { account: 'GA', role: 'Social Media', task: 'Reel cover page Posting' },
  { account: 'GA', role: 'Social Media', task: 'Google banners Posting' },
  { account: 'GA', role: 'Social Media', task: 'Linkedin banners Posting' },
  { account: 'GA', role: 'Social Media', task: 'Whats app Creatives Posting' },
  { account: 'GA', role: 'Social Media', task: 'Blog cover page Posting' },
  { account: 'GA', role: 'Social Media', task: 'Hiring Creative Posting' },
  { account: 'GA', role: 'Social Media', task: 'Emplyoee Creatives Posting' },
  { account: 'GA', role: 'Social Media', task: 'Post Event Creative Posting' },
  { account: 'GA', role: 'Social Media', task: 'Pre event Creatives Posting' },
  { account: 'GA', role: 'Social Media', task: 'Admission Creatives Posting' },
  { account: 'GA', role: 'Social Media', task: 'Emailers Posting' },
  { account: 'GA', role: 'Social Media', task: 'Posting Creatives Posting' },
  { account: 'GA', role: 'Ad Videos', task: 'Admissions Reel Posting' },
  { account: 'GA', role: 'Social Media', task: 'Festival Reel Posting' },
  { account: 'GA', role: 'Social Media', task: 'Training Reel Posting' },
  { account: 'GA', role: 'Social Media', task: 'Placement Reel Posting' },
  { account: 'GA', role: 'Social Media', task: 'Internal Branding Reel Posting' },
  { account: 'GA', role: 'Social Media', task: 'Content Creation Reel Posting' },
  { account: 'GA', role: 'Social Media', task: 'Motion Video Posting' },
  { account: 'GA', role: 'Event', task: 'AV' },
  { account: 'GA', role: 'Event', task: 'Pre Branding Reel' },
  { account: 'GA', role: 'Event', task: 'Post Branding Reel' },
  { account: 'GA', role: 'PPT', task: 'Content Creation PPT' },
  { account: 'GA', role: 'PPT', task: 'Sales PPT' },
  { account: 'GA', role: 'PPT', task: 'Onboarding PPT' },
  { account: 'GA', role: 'PPT', task: 'Induction PPT' },
  { account: 'GA', role: 'PPT', task: 'Pitch Deck PPT' },
  { account: 'GA', role: 'PPT', task: 'Review PPT' },
  { account: 'GA', role: 'PPT', task: 'Topic Covered PPT' },
  { account: 'GA', role: 'Ad campaigns', task: 'Ad campaigns Set up' },
  { account: 'GA', role: 'Ad campaigns', task: 'Ad campaign Optimization' },
  { account: 'GA', role: 'Ad campaigns', task: 'Lead Status tracking' },
  { account: 'GA', role: 'Event', task: 'Event PPT' },
  { account: 'GA', role: 'Event', task: 'Backdrops' },
  { account: 'GA', role: 'Event', task: 'Console Music' },
  { account: 'GA', role: 'Co-ordination', task: 'Vendors' },
  { account: 'GA', role: 'Follow up', task: 'External Hoardings' },
  { account: 'GA', role: 'Follow up', task: 'Internal Hoardings' },
  { account: 'GA', role: 'Follow up', task: 'Standees' },
  { account: 'GA', role: 'Follow up', task: 'Newspaper' },
  { account: 'GA', role: 'Follow up', task: 'Brochure' },
  { account: 'GA', role: 'Follow up', task: 'Event Print Media' },
  { account: 'GA', role: 'Follow up', task: 'Office Print Media' },
  { account: 'GA', role: 'IT Admin', task: 'Email & Account Setup' },
  { account: 'GA', role: 'IT Admin', task: 'Exchange 365 confuguration' },
  { account: 'GA', role: 'IT Admin', task: 'Powerbi Admin Panel' },
  { account: 'GA', role: 'IT Admin', task: 'Perview Microsoft 365 Admin Panel.' },
  { account: 'GA', role: 'Analysis', task: 'Requirement Gathering' },
  { account: 'GA', role: 'Analysis', task: 'Planning' },
  { account: 'GA', role: 'Design', task: 'Design Architecture' },
  { account: 'GA', role: 'Design', task: 'Prototype' },
  { account: 'GA', role: 'Design', task: 'Approval' },
  { account: 'GA', role: 'Coding', task: 'Source Code' },
  { account: 'GA', role: 'Coding', task: 'Frontend / Backend' },
  { account: 'GA', role: 'Coding', task: 'Collaboration' },
  { account: 'GA', role: 'Testing', task: 'Unit Testing' },
  { account: 'GA', role: 'Testing', task: 'Mobile Responsive' },
  { account: 'GA', role: 'Testing', task: 'I-Pad and Tab Responsive' },
  { account: 'GA', role: 'Testing', task: 'Browser Responsive' },
  { account: 'GA', role: 'Deployment', task: 'Pre-deployment check' },
  { account: 'GA', role: 'Deployment', task: 'Environment setup' },
  { account: 'GA', role: 'Deployment', task: 'Code Deployment' },
  { account: 'GA', role: 'Deployment', task: 'Post-Deployment Testing' },
  { account: 'GA', role: 'Deployment', task: 'Performance Monitoring' },
  { account: 'GA', role: 'CRM', task: 'Goals & Approval' },
  { account: 'GA', role: 'CRM', task: 'Scope & Planning' },
  { account: 'GA', role: 'CRM', task: 'Team Kickoff' },
  { account: 'GA', role: 'CRM', task: 'Development & Monitoring' },
  { account: 'GA', role: 'CRM', task: 'Testing & Quality' },
  { account: 'GA', role: 'CRM', task: 'Deployment & Closure' },
  { account: 'GA', role: 'Documentation', task: 'Report Generation' },
  { account: 'GA', role: 'Documentation', task: 'Data Cleaning & Standardization' },
  { account: 'GA', role: 'Documentation', task: 'DM Drive Organization' },
  { account: 'GA', role: 'Design', task: 'Design Architecture Modification' },
  { account: 'GA', role: 'Coding', task: 'Source Code Modification' },
  { account: 'GA', role: 'Testing', task: 'Unit Testing Modification' },
  { account: 'GA', role: 'Testing', task: 'Mobile Responsive Modification' },
  { account: 'GA', role: 'Testing', task: 'I-Pad and Tab Responsive Modification' },
  { account: 'GA', role: 'Testing', task: 'Browser Responsive Modification' },
  { account: 'GA', role: 'Documentation', task: 'Payments' },
  { account: 'GA', role: 'Co-ordination', task: 'Meeting Link' },
  { account: 'GA', role: 'Co-ordination', task: 'Mail Drafts' },
  { account: 'GA', role: 'Co-ordination', task: 'Google Ad Funds' },
  { account: 'GA', role: 'Social Media', task: 'LinkedIn Comments' },
  { account: 'GA', role: 'Social Media', task: 'Linkedin Repost' },
  { account: 'GA', role: 'Documentation', task: 'Calenders' },
  { account: 'GA', role: 'Documentation', task: 'Reports' },
  { account: 'GA', role: 'Documentation', task: 'MOM Content' },
  { account: 'ICEM', role: 'Analysis', task: 'Requirement Gathering' },
  { account: 'ICEM', role: 'Analysis', task: 'Planning' },
  { account: 'ICEM', role: 'WD Design', task: 'Design Architecture' },
  { account: 'ICEM', role: 'WD Design', task: 'Prototype' },
  { account: 'ICEM', role: 'WD Design', task: 'Approval' },
  { account: 'ICEM', role: 'Coding', task: 'Source Code' },
  { account: 'ICEM', role: 'Coding', task: 'Frontend / Backend' },
  { account: 'ICEM', role: 'Coding', task: 'Collaboration' },
  { account: 'ICEM', role: 'Testing', task: 'Unit Testing' },
  { account: 'ICEM', role: 'Testing', task: 'Mobile Responsive' },
  { account: 'ICEM', role: 'Testing', task: 'I-Pad and Tab Responsive' },
  { account: 'ICEM', role: 'Testing', task: 'Browser Responsive' },
  { account: 'ICEM', role: 'Deployment', task: 'Pre-deployment check' },
  { account: 'ICEM', role: 'Deployment', task: 'Environment setup' },
  { account: 'ICEM', role: 'Deployment', task: 'Code Deployment' },
  { account: 'ICEM', role: 'Deployment', task: 'Post-Deployment Testing' },
  { account: 'ICEM', role: 'Deployment', task: 'Performance Monitoring' },
  { account: 'ICEM', role: 'CRM', task: 'Goals & Approval' },
  { account: 'ICEM', role: 'CRM', task: 'Scope & Planning' },
  { account: 'ICEM', role: 'CRM', task: 'Team Kickoff' },
  { account: 'ICEM', role: 'CRM', task: 'Development & Monitoring' },
  { account: 'ICEM', role: 'CRM', task: 'Testing & Quality' },
  { account: 'ICEM', role: 'CRM', task: 'Deployment & Closure' },
  { account: 'ICEM', role: 'Documentation', task: 'Report Generation' },
  { account: 'ICEM', role: 'Documentation', task: 'Data Cleaning & Standardization' },
  { account: 'ICEM', role: 'Documentation', task: 'DM Drive Organization' },
  { account: 'ICEM', role: 'Design', task: 'Design Architecture Modification' },
  { account: 'ICEM', role: 'Coding', task: 'Source Code Modification' },
  { account: 'ICEM', role: 'Testing', task: 'Unit Testing Modification' },
  { account: 'ICEM', role: 'Testing', task: 'Mobile Responsive Modification' },
  { account: 'ICEM', role: 'Testing', task: 'I-Pad and Tab Responsive Modification' },
  { account: 'ICEM', role: 'Testing', task: 'Browser Responsive Modification' },
  { account: 'ICEM', role: 'Documentation', task: 'Payments' },
  { account: 'ICEM', role: 'Co-ordination', task: 'Meeting Link' },
  { account: 'ICEM', role: 'Co-ordination', task: 'Mail Drafts' },
  { account: 'ICEM', role: 'Co-ordination', task: 'Google Ad Funds' },
  { account: 'ICEM', role: 'Social Media', task: 'LinkedIn Comments' },
  { account: 'ICEM', role: 'Social Media', task: 'Linkedin Repost' },
  { account: 'ICEM', role: 'Documentation', task: 'Calenders' },
  { account: 'ICEM', role: 'Documentation', task: 'Reports' },
  { account: 'ICEM', role: 'Documentation', task: 'MOM Content' },
  { account: 'SB', role: 'Documentation', task: 'Payments' },
  { account: 'SB', role: 'Co-ordination', task: 'Meeting Link' },
  { account: 'SB', role: 'Co-ordination', task: 'Mail Drafts' },
  { account: 'SB', role: 'Co-ordination', task: 'Google Ad Funds' },
  { account: 'SB', role: 'Social Media', task: 'LinkedIn Comments' },
  { account: 'SB', role: 'Social Media', task: 'Linkedin Repost' },
  { account: 'SB', role: 'Documentation', task: 'Calenders' },
  { account: 'SB', role: 'Documentation', task: 'Reports' },
  { account: 'SB', role: 'Documentation', task: 'MOM Content' },
  { account: 'UA', role: 'Social Media', task: 'Pre Training Creative' },
  { account: 'UA', role: 'Social Media', task: 'Post Training Creative' },
  { account: 'UA', role: 'Social Media', task: 'Pre Placement Creative' },
  { account: 'UA', role: 'Social Media', task: 'Post Placement Drive Creative' },
  { account: 'UA', role: 'Social Media', task: 'Placement after Drive Creative' },
  { account: 'UA', role: 'Social Media', task: 'Festival Creatives' },
  { account: 'UA', role: 'Social Media', task: 'Reel cover page' },
  { account: 'UA', role: 'Social Media', task: 'Google banners' },
  { account: 'UA', role: 'Social Media', task: 'Linkedin banners' },
  { account: 'UA', role: 'Social Media', task: 'Whats app Creatives' },
  { account: 'UA', role: 'Social Media', task: 'Blog cover page' },
  { account: 'UA', role: 'Social Media', task: 'Hiring Creative' },
  { account: 'UA', role: 'Social Media', task: 'Emplyoee Creatives' },
  { account: 'UA', role: 'Social Media', task: 'Post Event Creative' },
  { account: 'UA', role: 'Social Media', task: 'Pre event Creatives' },
  { account: 'UA', role: 'Social Media', task: 'Admission Creatives' },
  { account: 'UA', role: 'Social Media', task: 'Emailers' },
  { account: 'UA', role: 'Social Media', task: 'Content Creatives' },
  { account: 'UA', role: 'Digital Media', task: 'Brochures' },
  { account: 'UA', role: 'Digital Media', task: 'Training Modules' },
  { account: 'UA', role: 'Digital Media', task: 'Certificates' },
  { account: 'UA', role: 'Digital Media', task: 'Symols, Stamp and Logos format' },
  { account: 'UA', role: 'Digital Media', task: 'Website images' },
  { account: 'UA', role: 'Digital Media', task: 'Websites Banners' },
  { account: 'UA', role: 'Digital Media', task: 'Website Design' },
  { account: 'UA', role: 'Digital Media', task: 'Trainers Profile' },
  { account: 'UA', role: 'Print Media', task: 'External Hoardings' },
  { account: 'UA', role: 'Print Media', task: 'Internal Hoardings' },
  { account: 'UA', role: 'Print Media', task: 'Standees' },
  { account: 'UA', role: 'Print Media', task: 'Newspaper' },
  { account: 'UA', role: 'Print Media', task: 'Brochure' },
  { account: 'UA', role: 'Print Media', task: 'Event Print Media' },
  { account: 'UA', role: 'Print Media', task: 'Office Print Media' },
  { account: 'UA', role: 'Event', task: 'Logo' },
  { account: 'UA', role: 'Event', task: 'Invites' },
  { account: 'UA', role: 'Event', task: 'Pre Event Creatives' },
  { account: 'UA', role: 'Event', task: 'Post Event Creatives' },
  { account: 'UA', role: 'Event', task: 'Agenda' },
  { account: 'UA', role: 'Ad Videos', task: 'Admissions Reel' },
  { account: 'UA', role: 'Social Media', task: 'Festival Reel' },
  { account: 'UA', role: 'Social Media', task: 'Training Reel' },
  { account: 'UA', role: 'Social Media', task: 'Placement Reel' },
  { account: 'UA', role: 'Social Media', task: 'Internal Branding Reel' },
  { account: 'UA', role: 'Social Media', task: 'Content Creation' },
  { account: 'UA', role: 'Social Media', task: 'Motion Videos' },
  { account: 'UA', role: 'Event', task: 'AV' },
  { account: 'UA', role: 'Event', task: 'Pre Branding Reel' },
  { account: 'UA', role: 'Event', task: 'Post Branding Reel' },
  { account: 'UA', role: 'Social Media', task: 'Pre Training Content' },
  { account: 'UA', role: 'Social Media', task: 'Post Training Content' },
  { account: 'UA', role: 'Social Media', task: 'Pre Placement Content' },
  { account: 'UA', role: 'Social Media', task: 'Post Placement Drive Content' },
  { account: 'UA', role: 'Social Media', task: 'Placement after Drive Creative Content' },
  { account: 'UA', role: 'Social Media', task: 'Festival Creatives Content' },
  { account: 'UA', role: 'Social Media', task: 'Reel cover page Content' },
  { account: 'UA', role: 'Social Media', task: 'Google banners Content' },
  { account: 'UA', role: 'Social Media', task: 'Linkedin banners Content' },
  { account: 'UA', role: 'Social Media', task: 'Whats app Creatives Content' },
  { account: 'UA', role: 'Social Media', task: 'Blog cover page Content' },
  { account: 'UA', role: 'Social Media', task: 'Hiring Creative Content' },
  { account: 'UA', role: 'Social Media', task: 'Emplyoee Creatives Content' },
  { account: 'UA', role: 'Social Media', task: 'Post Event Creative Content' },
  { account: 'UA', role: 'Social Media', task: 'Pre event Creatives Content' },
  { account: 'UA', role: 'Social Media', task: 'Admission Creatives Content' },
  { account: 'UA', role: 'Social Media', task: 'Emailers Content' },
  { account: 'UA', role: 'Social Media', task: 'Content Creatives Content' },
  { account: 'UA', role: 'Social Media', task: 'Caption' },
  { account: 'UA', role: 'Ad Videos', task: 'Admissions Scripts' },
  { account: 'UA', role: 'Social Media', task: 'Festival Reel Script' },
  { account: 'UA', role: 'Social Media', task: 'Training Reel Script' },
  { account: 'UA', role: 'Social Media', task: 'Placement Reel Script' },
  { account: 'UA', role: 'Social Media', task: 'Internal Branding Reel Script' },
  { account: 'UA', role: 'Social Media', task: 'Content Creation Script' },
  { account: 'UA', role: 'Social Media', task: 'Motion Videos Script' },
  { account: 'UA', role: 'Event', task: 'AV Script' },
  { account: 'UA', role: 'Event', task: 'Pre Branding Reel Script' },
  { account: 'UA', role: 'Event', task: 'Post Branding Reel Script' },
  { account: 'UA', role: 'Digital Media', task: 'Brochures Content' },
  { account: 'UA', role: 'Digital Media', task: 'Training Modules Content' },
  { account: 'UA', role: 'Digital Media', task: 'Certificates Content' },
  { account: 'UA', role: 'Digital Media', task: 'Trainers Profile Content' },
  { account: 'UA', role: 'Print Media', task: 'External Hoardings Content' },
  { account: 'UA', role: 'Print Media', task: 'Internal Hoardings Content' },
  { account: 'UA', role: 'Print Media', task: 'Standees Content' },
  { account: 'UA', role: 'Print Media', task: 'Newspaper Content' },
  { account: 'UA', role: 'Print Media', task: 'Brochure Content' },
  { account: 'UA', role: 'Print Media', task: 'Event Print Media Content' },
  { account: 'UA', role: 'Print Media', task: 'Office Print Media Content' },
  { account: 'UA', role: 'Content Calendar', task: 'Weekly content Calender' },
  { account: 'UA', role: 'Blog Creation', task: 'Trending Topics' },
  { account: 'UA', role: 'Blog Creation', task: 'Technical' },
  { account: 'UA', role: 'Blog Creation', task: 'Branding' },
  { account: 'UA', role: 'SEO', task: 'Website Content' },
  { account: 'UA', role: 'SEO', task: 'Landing Page Content' },
  { account: 'UA', role: 'SEO', task: 'Ad Copies Content' },
  { account: 'UA', role: 'Event', task: 'Pre event Creatives Content' },
  { account: 'UA', role: 'Event', task: 'Post Event Creatives Content' },
  { account: 'UA', role: 'Event', task: 'Agenda Content' },
  { account: 'UA', role: 'Event', task: 'Concept Note Content' },
  { account: 'UA', role: 'Event', task: 'Invites Content' },
  { account: 'UA', role: 'Event', task: 'Agenda Content' },
  { account: 'UA', role: 'Event', task: 'Mail drafts' },
  { account: 'UA', role: 'Event', task: 'Guest List tracker & maintenance' },
  { account: 'UA', role: 'Proof reading', task: '' },
  { account: 'UA', role: 'Social Media', task: 'Pre Training Posting' },
  { account: 'UA', role: 'Social Media', task: 'Post Training Posting' },
  { account: 'UA', role: 'Social Media', task: 'Pre Placement Posting' },
  { account: 'UA', role: 'Social Media', task: 'Post Placement Drive Posting' },
  { account: 'UA', role: 'Social Media', task: 'Placement after Drive Creative Posting' },
  { account: 'UA', role: 'Social Media', task: 'Festival Creatives Posting' },
  { account: 'UA', role: 'Social Media', task: 'Reel cover page Posting' },
  { account: 'UA', role: 'Social Media', task: 'Google banners Posting' },
  { account: 'UA', role: 'Social Media', task: 'Linkedin banners Posting' },
  { account: 'UA', role: 'Social Media', task: 'Whats app Creatives Posting' },
  { account: 'UA', role: 'Social Media', task: 'Blog cover page Posting' },
  { account: 'UA', role: 'Social Media', task: 'Hiring Creative Posting' },
  { account: 'UA', role: 'Social Media', task: 'Emplyoee Creatives Posting' },
  { account: 'UA', role: 'Social Media', task: 'Post Event Creative Posting' },
  { account: 'UA', role: 'Social Media', task: 'Pre event Creatives Posting' },
  { account: 'UA', role: 'Social Media', task: 'Admission Creatives Posting' },
  { account: 'UA', role: 'Social Media', task: 'Emailers Posting' },
  { account: 'UA', role: 'Social Media', task: 'Posting Creatives Posting' },
  { account: 'UA', role: 'Ad Videos', task: 'Admissions Reel Posting' },
  { account: 'UA', role: 'Social Media', task: 'Festival Reel Posting' },
  { account: 'UA', role: 'Social Media', task: 'Training Reel Posting' },
  { account: 'UA', role: 'Social Media', task: 'Placement Reel Posting' },
  { account: 'UA', role: 'Social Media', task: 'Internal Branding Reel Posting' },
  { account: 'UA', role: 'Social Media', task: 'Content Creation Reel Posting' },
  { account: 'UA', role: 'Social Media', task: 'Motion Video Posting' },
  { account: 'UA', role: 'Event', task: 'AV' },
  { account: 'UA', role: 'Event', task: 'Pre Branding Reel' },
  { account: 'UA', role: 'Event', task: 'Post Branding Reel' },
  { account: 'UA', role: 'PPT', task: 'Content Creation PPT' },
  { account: 'UA', role: 'PPT', task: 'Sales PPT' },
  { account: 'UA', role: 'PPT', task: 'Onboarding PPT' },
  { account: 'UA', role: 'PPT', task: 'Induction PPT' },
  { account: 'UA', role: 'PPT', task: 'Pitch Deck PPT' },
  { account: 'UA', role: 'PPT', task: 'Review PPT' },
  { account: 'UA', role: 'PPT', task: 'Topic Covered PPT' },
  { account: 'UA', role: 'Ad campaigns', task: 'Ad campaigns Set up' },
  { account: 'UA', role: 'Ad campaigns', task: 'Ad campaign Optimization' },
  { account: 'UA', role: 'Ad campaigns', task: 'Lead Status tracking' },
  { account: 'UA', role: 'Event', task: 'Event PPT' },
  { account: 'UA', role: 'Event', task: 'Backdrops' },
  { account: 'UA', role: 'Event', task: 'Console Music' },
  { account: 'TNSS', role: 'Social Media', task: 'Pre Training Creative' },
  { account: 'TNSS', role: 'Social Media', task: 'Post Training Creative' },
  { account: 'TNSS', role: 'Social Media', task: 'Pre Placement Creative' },
  { account: 'TNSS', role: 'Social Media', task: 'Post Placement Drive Creative' },
  { account: 'TNSS', role: 'Social Media', task: 'Placement after Drive Creative' },
  { account: 'TNSS', role: 'Social Media', task: 'Festival Creatives' },
  { account: 'TNSS', role: 'Social Media', task: 'Reel cover page' },
  { account: 'TNSS', role: 'Social Media', task: 'Google banners' },
  { account: 'TNSS', role: 'Social Media', task: 'Linkedin banners' },
  { account: 'TNSS', role: 'Social Media', task: 'Whats app Creatives' },
  { account: 'TNSS', role: 'Social Media', task: 'Blog cover page' },
  { account: 'TNSS', role: 'Social Media', task: 'Hiring Creative' },
  { account: 'TNSS', role: 'Social Media', task: 'Emplyoee Creatives' },
  { account: 'TNSS', role: 'Social Media', task: 'Post Event Creative' },
  { account: 'TNSS', role: 'Social Media', task: 'Pre event Creatives' },
  { account: 'TNSS', role: 'Social Media', task: 'Admission Creatives' },
  { account: 'TNSS', role: 'Social Media', task: 'Emailers' },
  { account: 'TNSS', role: 'Social Media', task: 'Content Creatives' },
  { account: 'TNSS', role: 'Digital Media', task: 'Brochures' },
  { account: 'TNSS', role: 'Digital Media', task: 'Training Modules' },
  { account: 'TNSS', role: 'Digital Media', task: 'Certificates' },
  { account: 'TNSS', role: 'Digital Media', task: 'Symols, Stamp and Logos format' },
  { account: 'TNSS', role: 'Digital Media', task: 'Website images' },
  { account: 'TNSS', role: 'Digital Media', task: 'Websites Banners' },
  { account: 'TNSS', role: 'Digital Media', task: 'Website Design' },
  { account: 'TNSS', role: 'Digital Media', task: 'Trainers Profile' },
  { account: 'TNSS', role: 'Print Media', task: 'External Hoardings' },
  { account: 'TNSS', role: 'Print Media', task: 'Internal Hoardings' },
  { account: 'TNSS', role: 'Print Media', task: 'Standees' },
  { account: 'TNSS', role: 'Print Media', task: 'Newspaper' },
  { account: 'TNSS', role: 'Print Media', task: 'Brochure' },
  { account: 'TNSS', role: 'Print Media', task: 'Event Print Media' },
  { account: 'TNSS', role: 'Print Media', task: 'Office Print Media' },
  { account: 'TNSS', role: 'Event', task: 'Logo' },
  { account: 'TNSS', role: 'Event', task: 'Invites' },
  { account: 'TNSS', role: 'Event', task: 'Pre Event Creatives' },
  { account: 'TNSS', role: 'Event', task: 'Post Event Creatives' },
  { account: 'TNSS', role: 'Event', task: 'Agenda' },
  { account: 'TNSS', role: 'Ad Videos', task: 'Admissions Reel' },
  { account: 'TNSS', role: 'Social Media', task: 'Festival Reel' },
  { account: 'TNSS', role: 'Social Media', task: 'Training Reel' },
  { account: 'TNSS', role: 'Social Media', task: 'Placement Reel' },
  { account: 'TNSS', role: 'Social Media', task: 'Internal Branding Reel' },
  { account: 'TNSS', role: 'Social Media', task: 'Content Creation' },
  { account: 'TNSS', role: 'Social Media', task: 'Motion Videos' },
  { account: 'TNSS', role: 'Event', task: 'AV' },
  { account: 'TNSS', role: 'Event', task: 'Pre Branding Reel' },
  { account: 'TNSS', role: 'Event', task: 'Post Branding Reel' },
  { account: 'TNSS', role: 'Social Media', task: 'Pre Training Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Post Training Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Pre Placement Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Post Placement Drive Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Placement after Drive Creative Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Festival Creatives Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Reel cover page Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Google banners Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Linkedin banners Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Whats app Creatives Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Blog cover page Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Hiring Creative Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Emplyoee Creatives Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Post Event Creative Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Pre event Creatives Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Admission Creatives Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Emailers Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Content Creatives Content' },
  { account: 'TNSS', role: 'Social Media', task: 'Caption' },
  { account: 'TNSS', role: 'Ad Videos', task: 'Admissions Scripts' },
  { account: 'TNSS', role: 'Social Media', task: 'Festival Reel Script' },
  { account: 'TNSS', role: 'Social Media', task: 'Training Reel Script' },
  { account: 'TNSS', role: 'Social Media', task: 'Placement Reel Script' },
  { account: 'TNSS', role: 'Social Media', task: 'Internal Branding Reel Script' },
  { account: 'TNSS', role: 'Social Media', task: 'Content Creation Script' },
  { account: 'TNSS', role: 'Social Media', task: 'Motion Videos Script' },
  { account: 'TNSS', role: 'Event', task: 'AV Script' },
  { account: 'TNSS', role: 'Event', task: 'Pre Branding Reel Script' },
  { account: 'TNSS', role: 'Event', task: 'Post Branding Reel Script' },
  { account: 'TNSS', role: 'Digital Media', task: 'Brochures Content' },
  { account: 'TNSS', role: 'Digital Media', task: 'Training Modules Content' },
  { account: 'TNSS', role: 'Digital Media', task: 'Certificates Content' },
  { account: 'TNSS', role: 'Digital Media', task: 'Trainers Profile Content' },
  { account: 'TNSS', role: 'Print Media', task: 'External Hoardings Content' },
  { account: 'TNSS', role: 'Print Media', task: 'Internal Hoardings Content' },
  { account: 'TNSS', role: 'Print Media', task: 'Standees Content' },
  { account: 'TNSS', role: 'Print Media', task: 'Newspaper Content' },
  { account: 'TNSS', role: 'Print Media', task: 'Brochure Content' },
  { account: 'TNSS', role: 'Print Media', task: 'Event Print Media Content' },
  { account: 'TNSS', role: 'Print Media', task: 'Office Print Media Content' },
  { account: 'TNSS', role: 'Content Calendar', task: 'Weekly content Calender' },
  { account: 'TNSS', role: 'Blog Creation', task: 'Trending Topics' },
  { account: 'TNSS', role: 'Blog Creation', task: 'Technical' },
  { account: 'TNSS', role: 'Blog Creation', task: 'Branding' },
  { account: 'TNSS', role: 'SEO', task: 'Website Content' },
  { account: 'TNSS', role: 'SEO', task: 'Landing Page Content' },
  { account: 'TNSS', role: 'SEO', task: 'Ad Copies Content' },
  { account: 'TNSS', role: 'Event', task: 'Pre event Creatives Content' },
  { account: 'TNSS', role: 'Event', task: 'Post Event Creatives Content' },
  { account: 'TNSS', role: 'Event', task: 'Agenda Content' },
  { account: 'TNSS', role: 'Event', task: 'Concept Note Content' },
  { account: 'TNSS', role: 'Event', task: 'Invites Content' },
  { account: 'TNSS', role: 'Event', task: 'Agenda Content' },
  { account: 'TNSS', role: 'Event', task: 'Mail drafts' },
  { account: 'TNSS', role: 'Event', task: 'Guest List tracker & maintenance' },
  { account: 'TNSS', role: 'Proof reading', task: '' },
  { account: 'TNSS', role: 'Social Media', task: 'Pre Training Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Post Training Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Pre Placement Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Post Placement Drive Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Placement after Drive Creative Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Festival Creatives Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Reel cover page Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Google banners Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Linkedin banners Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Whats app Creatives Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Blog cover page Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Hiring Creative Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Emplyoee Creatives Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Post Event Creative Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Pre event Creatives Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Admission Creatives Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Emailers Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Posting Creatives Posting' },
  { account: 'TNSS', role: 'Ad Videos', task: 'Admissions Reel Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Festival Reel Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Training Reel Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Placement Reel Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Internal Branding Reel Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Content Creation Reel Posting' },
  { account: 'TNSS', role: 'Social Media', task: 'Motion Video Posting' },
  { account: 'TNSS', role: 'Event', task: 'AV' },
  { account: 'TNSS', role: 'Event', task: 'Pre Branding Reel' },
  { account: 'TNSS', role: 'Event', task: 'Post Branding Reel' },
  { account: 'TNSS', role: 'PPT', task: 'Content Creation PPT' },
  { account: 'TNSS', role: 'PPT', task: 'Sales PPT' },
  { account: 'TNSS', role: 'PPT', task: 'Onboarding PPT' },
  { account: 'TNSS', role: 'PPT', task: 'Induction PPT' },
  { account: 'TNSS', role: 'PPT', task: 'Pitch Deck PPT' },
  { account: 'TNSS', role: 'PPT', task: 'Review PPT' },
  { account: 'TNSS', role: 'PPT', task: 'Topic Covered PPT' },
  { account: 'TNSS', role: 'Ad campaigns', task: 'Ad campaigns Set up' },
  { account: 'TNSS', role: 'Ad campaigns', task: 'Ad campaign Optimization' },
  { account: 'TNSS', role: 'Ad campaigns', task: 'Lead Status tracking' },
  { account: 'TNSS', role: 'Event', task: 'Event PPT' },
  { account: 'TNSS', role: 'Event', task: 'Backdrops' },
  { account: 'TNSS', role: 'Event', task: 'Console Music' },
  { account: 'GA', role: 'IT Admin', task: 'Email & Account Setup' },
  { account: 'GA', role: 'IT Admin', task: 'Exchange 365 confuguration' },
  { account: 'GA', role: 'IT Admin', task: 'Powerbi Admin Panel' },
  { account: 'GA', role: 'IT Admin', task: 'Perview Microsoft 365 Admin Panel.' },
  { account: 'GA', role: 'Analysis', task: 'Requirement Gathering' },
  { account: 'GA', role: 'Analysis', task: 'Planning' },
  { account: 'GA', role: 'WD Design', task: 'Design Architecture' },
  { account: 'GA', role: 'WD Design', task: 'Prototype' },
  { account: 'GA', role: 'WD Design', task: 'Approval' },
  { account: 'GA', role: 'Coding', task: 'Source Code' },
  { account: 'GA', role: 'Coding', task: 'Frontend / Backend' },
  { account: 'GA', role: 'Coding', task: 'Collaboration' },
  { account: 'GA', role: 'Testing', task: 'Unit Testing' },
  { account: 'GA', role: 'Testing', task: 'Mobile Responsive' },
  { account: 'GA', role: 'Testing', task: 'I-Pad and Tab Responsive' },
  { account: 'GA', role: 'Testing', task: 'Browser Responsive' },
  { account: 'GA', role: 'Deployment', task: 'Pre-deployment check' },
  { account: 'GA', role: 'Deployment', task: 'Environment setup' },
  { account: 'GA', role: 'Deployment', task: 'Code Deployment' },
  { account: 'GA', role: 'Deployment', task: 'Post-Deployment Testing' },
  { account: 'GA', role: 'Deployment', task: 'Performance Monitoring' },
  { account: 'GA', role: 'CRM', task: 'Goals & Approval' },
  { account: 'GA', role: 'CRM', task: 'Scope & Planning' },
  { account: 'GA', role: 'CRM', task: 'Team Kickoff' },
  { account: 'GA', role: 'CRM', task: 'Development & Monitoring' },
  { account: 'GA', role: 'CRM', task: 'Testing & Quality' },
  { account: 'GA', role: 'CRM', task: 'Deployment & Closure' },
  { account: 'GA', role: 'Documentation', task: 'Report Generation' },
  { account: 'GA', role: 'Documentation', task: 'Data Cleaning & Standardization' },
  { account: 'GA', role: 'Documentation', task: 'DM Drive Organization' },
  { account: 'GA', role: 'Design', task: 'Design Architecture Modification' },
  { account: 'GA', role: 'Coding', task: 'Source Code Modification' },
  { account: 'GA', role: 'Testing', task: 'Unit Testing Modification' },
  { account: 'GA', role: 'Testing', task: 'Mobile Responsive Modification' },
  { account: 'GA', role: 'Testing', task: 'I-Pad and Tab Responsive Modification' },
  { account: 'GA', role: 'Testing', task: 'Browser Responsive Modification' },
  { account: 'GA', role: 'Documentation', task: 'Payments' },
  { account: 'GA', role: 'Co-ordination', task: 'Meeting Link' },
  { account: 'GA', role: 'Co-ordination', task: 'Mail Drafts' },
  { account: 'GA', role: 'Co-ordination', task: 'Google Ad Funds' },
  { account: 'GA', role: 'Social Media', task: 'LinkedIn Comments' },
  { account: 'GA', role: 'Social Media', task: 'Linkedin Repost' },
  { account: 'GA', role: 'Documentation', task: 'Calenders' },
  { account: 'GA', role: 'Documentation', task: 'Reports' },
  { account: 'GA', role: 'Documentation', task: 'MOM Content' },
  { account: 'ICEM', role: 'Analysis', task: 'Requirement Gathering' },
  { account: 'ICEM', role: 'Analysis', task: 'Planning' },
  { account: 'ICEM', role: 'WD Design', task: 'Design Architecture' },
  { account: 'ICEM', role: 'WD Design', task: 'Prototype' },
  { account: 'ICEM', role: 'WD Design', task: 'Approval' },
  { account: 'ICEM', role: 'Coding', task: 'Source Code' },
  { account: 'ICEM', role: 'Coding', task: 'Frontend / Backend' },
  { account: 'ICEM', role: 'Coding', task: 'Collaboration' },
  { account: 'ICEM', role: 'Testing', task: 'Unit Testing' },
  { account: 'ICEM', role: 'Testing', task: 'Mobile Responsive' },
  { account: 'ICEM', role: 'Testing', task: 'I-Pad and Tab Responsive' },
  { account: 'ICEM', role: 'Testing', task: 'Browser Responsive' },
  { account: 'ICEM', role: 'Deployment', task: 'Pre-deployment check' },
  { account: 'ICEM', role: 'Deployment', task: 'Environment setup' },
  { account: 'ICEM', role: 'Deployment', task: 'Code Deployment' },
  { account: 'ICEM', role: 'Deployment', task: 'Post-Deployment Testing' },
  { account: 'ICEM', role: 'Deployment', task: 'Performance Monitoring' },
  { account: 'ICEM', role: 'CRM', task: 'Goals & Approval' },
  { account: 'ICEM', role: 'CRM', task: 'Scope & Planning' },
  { account: 'ICEM', role: 'CRM', task: 'Team Kickoff' },
  { account: 'ICEM', role: 'CRM', task: 'Development & Monitoring' },
  { account: 'ICEM', role: 'CRM', task: 'Testing & Quality' },
  { account: 'ICEM', role: 'CRM', task: 'Deployment & Closure' },
  { account: 'ICEM', role: 'Documentation', task: 'Report Generation' },
  { account: 'ICEM', role: 'Documentation', task: 'Data Cleaning & Standardization' },
  { account: 'ICEM', role: 'Documentation', task: 'DM Drive Organization' },
  { account: 'ICEM', role: 'Design', task: 'Design Architecture Modification' },
  { account: 'ICEM', role: 'Coding', task: 'Source Code Modification' },
  { account: 'ICEM', role: 'Testing', task: 'Unit Testing Modification' },
  { account: 'ICEM', role: 'Testing', task: 'Mobile Responsive Modification' },
  { account: 'ICEM', role: 'Testing', task: 'I-Pad and Tab Responsive Modification' },
  { account: 'ICEM', role: 'Testing', task: 'Browser Responsive Modification' },
  { account: 'ICEM', role: 'Documentation', task: 'Payments' },
  { account: 'ICEM', role: 'Co-ordination', task: 'Meeting Link' },
  { account: 'ICEM', role: 'Co-ordination', task: 'Mail Drafts' },
  { account: 'ICEM', role: 'Co-ordination', task: 'Google Ad Funds' },
  { account: 'ICEM', role: 'Social Media', task: 'LinkedIn Comments' },
  { account: 'ICEM', role: 'Social Media', task: 'Linkedin Repost' },
  { account: 'ICEM', role: 'Documentation', task: 'Calenders' },
  { account: 'ICEM', role: 'Documentation', task: 'Reports' },
  { account: 'ICEM', role: 'Documentation', task: 'MOM Content' },
  { account: 'SB', role: 'Documentation', task: 'Payments' },
  { account: 'SB', role: 'Co-ordination', task: 'Meeting Link' },
  { account: 'SB', role: 'Co-ordination', task: 'Mail Drafts' },
  { account: 'SB', role: 'Co-ordination', task: 'Google Ad Funds' },
  { account: 'SB', role: 'Social Media', task: 'LinkedIn Comments' },
  { account: 'SB', role: 'Social Media', task: 'Linkedin Repost' },
  { account: 'SB', role: 'Documentation', task: 'Calenders' },
  { account: 'SB', role: 'Documentation', task: 'Reports' },
  { account: 'SB', role: 'Documentation', task: 'MOM Content' },
  { account: 'UA', role: 'IT Admin', task: 'Email & Account Setup' },
  { account: 'UA', role: 'IT Admin', task: 'Exchange 365 confuguration' },
  { account: 'UA', role: 'IT Admin', task: 'Powerbi Admin Panel' },
  { account: 'UA', role: 'IT Admin', task: 'Perview Microsoft 365 Admin Panel.' },
  { account: 'UA', role: 'Analysis', task: 'Requirement Gathering' },
  { account: 'UA', role: 'Analysis', task: 'Planning' },
  { account: 'UA', role: 'WD Design', task: 'Design Architecture' },
  { account: 'UA', role: 'WD Design', task: 'Prototype' },
  { account: 'UA', role: 'WD Design', task: 'Approval' },
  { account: 'UA', role: 'Coding', task: 'Source Code' },
  { account: 'UA', role: 'Coding', task: 'Frontend / Backend' },
  { account: 'UA', role: 'Coding', task: 'Collaboration' },
  { account: 'UA', role: 'Testing', task: 'Unit Testing' },
  { account: 'UA', role: 'Testing', task: 'Mobile Responsive' },
  { account: 'UA', role: 'Testing', task: 'I-Pad and Tab Responsive' },
  { account: 'UA', role: 'Testing', task: 'Browser Responsive' },
  { account: 'UA', role: 'Deployment', task: 'Pre-deployment check' },
  { account: 'UA', role: 'Deployment', task: 'Environment setup' },
  { account: 'UA', role: 'Deployment', task: 'Code Deployment' },
  { account: 'UA', role: 'Deployment', task: 'Post-Deployment Testing' },
  { account: 'UA', role: 'Deployment', task: 'Performance Monitoring' },
  { account: 'UA', role: 'CRM', task: 'Goals & Approval' },
  { account: 'UA', role: 'CRM', task: 'Scope & Planning' },
  { account: 'UA', role: 'CRM', task: 'Team Kickoff' },
  { account: 'UA', role: 'CRM', task: 'Development & Monitoring' },
  { account: 'UA', role: 'CRM', task: 'Testing & Quality' },
  { account: 'UA', role: 'CRM', task: 'Deployment & Closure' },
  { account: 'UA', role: 'Documentation', task: 'Report Generation' },
  { account: 'UA', role: 'Documentation', task: 'Data Cleaning & Standardization' },
  { account: 'UA', role: 'Documentation', task: 'DM Drive Organization' },
  { account: 'UA', role: 'WD Design', task: 'Design Architecture Modification' },
  { account: 'UA', role: 'Coding', task: 'Source Code Modification' },
  { account: 'UA', role: 'Testing', task: 'Unit Testing Modification' },
  { account: 'UA', role: 'Testing', task: 'Mobile Responsive Modification' },
  { account: 'UA', role: 'Testing', task: 'I-Pad and Tab Responsive Modification' },
  { account: 'UA', role: 'Testing', task: 'Browser Responsive Modification' },
  { account: 'UA', role: 'Documentation', task: 'Payments' },
  { account: 'UA', role: 'Co-ordination', task: 'Meeting Link' },
  { account: 'UA', role: 'Co-ordination', task: 'Mail Drafts' },
  { account: 'UA', role: 'Co-ordination', task: 'Google Ad Funds' },
  { account: 'UA', role: 'Social Media', task: 'LinkedIn Comments' },
  { account: 'UA', role: 'Social Media', task: 'Linkedin Repost' },
  { account: 'UA', role: 'Documentation', task: 'Calenders' },
  { account: 'UA', role: 'Documentation', task: 'Reports' },
  { account: 'UA', role: 'Documentation', task: 'MOM Content' },
  { account: 'TNSS', role: 'IT Admin', task: 'Email & Account Setup' },
  { account: 'TNSS', role: 'IT Admin', task: 'Exchange 365 confuguration' },
  { account: 'TNSS', role: 'IT Admin', task: 'Powerbi Admin Panel' },
  { account: 'TNSS', role: 'IT Admin', task: 'Perview Microsoft 365 Admin Panel.' },
  { account: 'TNSS', role: 'Analysis', task: 'Requirement Gathering' },
  { account: 'TNSS', role: 'Analysis', task: 'Planning' },
  { account: 'TNSS', role: 'WD Design', task: 'Design Architecture' },
  { account: 'TNSS', role: 'WD Design', task: 'Prototype' },
  { account: 'TNSS', role: 'WD Design', task: 'Approval' },
  { account: 'TNSS', role: 'Coding', task: 'Source Code' },
  { account: 'TNSS', role: 'Coding', task: 'Frontend / Backend' },
  { account: 'TNSS', role: 'Coding', task: 'Collaboration' },
  { account: 'TNSS', role: 'Testing', task: 'Unit Testing' },
  { account: 'TNSS', role: 'Testing', task: 'Mobile Responsive' },
  { account: 'TNSS', role: 'Testing', task: 'I-Pad and Tab Responsive' },
  { account: 'TNSS', role: 'Testing', task: 'Browser Responsive' },
  { account: 'TNSS', role: 'Deployment', task: 'Pre-deployment check' },
  { account: 'TNSS', role: 'Deployment', task: 'Environment setup' },
  { account: 'TNSS', role: 'Deployment', task: 'Code Deployment' },
  { account: 'TNSS', role: 'Deployment', task: 'Post-Deployment Testing' },
  { account: 'TNSS', role: 'Deployment', task: 'Performance Monitoring' },
  { account: 'TNSS', role: 'CRM', task: 'Goals & Approval' },
  { account: 'TNSS', role: 'CRM', task: 'Scope & Planning' },
  { account: 'TNSS', role: 'CRM', task: 'Team Kickoff' },
  { account: 'TNSS', role: 'CRM', task: 'Development & Monitoring' },
  { account: 'TNSS', role: 'CRM', task: 'Testing & Quality' },
  { account: 'TNSS', role: 'CRM', task: 'Deployment & Closure' },
  { account: 'TNSS', role: 'Documentation', task: 'Report Generation' },
  { account: 'TNSS', role: 'Documentation', task: 'Data Cleaning & Standardization' },
  { account: 'TNSS', role: 'Documentation', task: 'DM Drive Organization' },
  { account: 'TNSS', role: 'WD Design', task: 'Design Architecture Modification' },
  { account: 'TNSS', role: 'Coding', task: 'Source Code Modification' },
  { account: 'TNSS', role: 'Testing', task: 'Unit Testing Modification' },
  { account: 'TNSS', role: 'Testing', task: 'Mobile Responsive Modification' },
  { account: 'TNSS', role: 'Testing', task: 'I-Pad and Tab Responsive Modification' },
  { account: 'TNSS', role: 'Testing', task: 'Browser Responsive Modification' },
  { account: 'GA', role: 'Print Media', task: 'Brochures Content' },
  { account: 'SB', role: 'Documentation', task: 'Meeting Link' },
  { account: 'ICEM', role: 'Social Media', task: 'Changes' },
  { account: 'ICEM', role: 'Print Media', task: 'Brochures' },
  { account: 'ICEM', role: 'Social Media', task: 'Admissions Reel Posting' },
  { account: 'IU', role: 'Social Media', task: 'Admissions Reel Posting' },
  { account: 'IU', role: 'Follow up', task: 'Lead Status tracking' },
  { account: 'ICEM', role: 'Follow up', task: 'Lead Status tracking' },
  { account: 'GA', role: 'Follow up', task: 'Lead Status tracking' },
  { account: 'UA', role: 'Follow up', task: 'Lead Status tracking' },
  { account: 'IU', role: 'Follow up', task: 'Payments' },
  { account: 'ICEM', role: 'Follow up', task: 'Payments' },
  { account: 'GA', role: 'Follow up', task: 'Payments' },
  { account: 'UA', role: 'Follow up', task: 'Payments' },
];

export default tasksData;