export const budgetComponents = {
  sales: {
    emails: "Email Subscriptions",
    laptops: "Laptops",
    tshirts: "T-shirts",
    printmedia: "Print Media",
    diwaligifts: "Diwali Gifts",
  },
  cr: {
    emails: "Email Subscriptions",
    laptops: "Laptops",
    tshirts: "T-shirts",
    printmedia: "Print Media",
    gifts: "Diwali & Other Gifts",
  },
  lnd: {
    laptops: "Laptops",
    printmedia: "Print Media",
    trainertshirts: "Trainer T-shirts",
    tshirts: "T-shirts",
  },
  hr: {
    tshirts: "T-shirts",
    email: "Email Subscriptions",
    laptops: "Laptops",
    ca: "CA Consultancy",
  },
  dm: {
    laptops: "Laptops",
    email: "Email Subscriptions",
    printmedia: "Print Media",
    tshirts: "T-shirts",
    trademarks: "Trademarks / Domains",
    adobe: "Adobe Creative Cloud",
    envato: "Envato Subscription",
    canva: "Canva Pro",
    softwareinstallation: "Software Installation",
    simcard: "SIM Card / Network Tools",
    elevenlabs: "Eleven Labs Subscription",
    performancemarketing: "Performance Marketing",
  },
  admin: {
    emails: "Email Subscriptions",
    pt: "Promotional Tools",
    laptops: "Laptops",
    tshirts: "T-shirts",
    printmedia: "Print Media",
    diwaligifts: "Diwali Gifts",
  },
  purchase: {
    emails: "Email Subscriptions",
    pt: "Promotional Tools",
    laptops: "Laptops",
    tshirts: "T-shirts",
    printmedia: "Print Media",
    diwaligifts: "Diwali Gifts",
  },
  placement: {
    emails: "Email Subscriptions",
    laptops: "Laptops",
    tshirts: "T-shirts",
    printmedia: "Print Media",
    training_materials: "Training Materials",
    placement_events: "Placement Events",
    diwaligifts: "Diwali Gifts",
    travel_expenses: "Travel Expenses",
  },
  management: {
    emails: "Email Subscriptions",
  },
};

// Component colors mapping
export const componentColors = {
  emails: "bg-blue-100 text-blue-800 border-blue-200",
  pt: "bg-purple-100 text-purple-800 border-purple-200",
  laptops: "bg-sky-100 text-sky-800 border-sky-200",
  tshirts: "bg-indigo-100 text-indigo-800 border-indigo-200",
  printmedia: "bg-cyan-100 text-cyan-800 border-cyan-200",
  diwaligifts: "bg-pink-100 text-pink-800 border-pink-200",
  gifts: "bg-orange-100 text-orange-800 border-orange-200",
  trainertshirts: "bg-green-100 text-green-800 border-green-200",
  esic: "bg-red-100 text-red-800 border-red-200",
  email: "bg-blue-100 text-blue-800 border-blue-200",
  ca: "bg-gray-100 text-gray-800 border-gray-200",
  trademarks: "bg-yellow-100 text-yellow-800 border-yellow-200",
  adobe: "bg-red-100 text-red-800 border-red-200",
  envato: "bg-green-100 text-green-800 border-green-200",
  canva: "bg-blue-100 text-blue-800 border-blue-200",
  softwareinstallation: "bg-purple-100 text-purple-800 border-purple-200",
  simcard: "bg-indigo-100 text-indigo-800 border-indigo-200",
  elevenlabs: "bg-amber-100 text-amber-800 border-amber-200",
  performancemarketing: "bg-pink-100 text-pink-800 border-pink-200",
  training_materials: "bg-teal-100 text-teal-800 border-teal-200",
  placement_events: "bg-violet-100 text-violet-800 border-violet-200",
  corporate_gifts: "bg-rose-100 text-rose-800 border-rose-200",
  travel_expenses: "bg-lime-100 text-lime-800 border-lime-200",
};
