// stateCityData.js
const stateCityData = {
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Kalyan-Dombivali",
    "Vasai-Virar",
    "Solapur",
    "Mira-Bhayandar",
    "Bhiwandi",
    "Amravati",
    "Nanded-Waghala",
    "Sangli",
    "Malegaon",
    "Beed",
    "Akola",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Ichalkaranji",
    "Parbhani",
    "Panvel",
    "Yavatmal",
    "Achalpur",
    "Dharashiv",
    "Nandurbar",
    "Satara",
    "Wardha",
    "Udgir",
    "Chhatrapati Sambhajinagar",
    "Amalner",
    "Akot",
    "Pandharpur",
    "Shrirampur",
    "Parli",
    "Washim",
    "Ambejogai",
    "Manmad",
    "Ratnagiri",
    "Uran Islampur",
    "Pusad",
    "Sangamner",
    "Shirpur-Warwade",
    "Malkapur",
    "Wani",
    "Lonavla",
    "Talegaon Dabhade",
    "Anjangaon",
    "Umred",
    "Palghar",
    "Shegaon",
    "Ozar",
    "Phaltan",
    "Yevla",
    "Shahade",
    "Vita",
    "Umarkhed",
    "Warora",
    "Pachora",
    "Tumsar",
    "Manjlegaon",
    "Sillod",
    "Arvi",
    "Nandura",
    "Vaijapur",
    "Wadgaon Road",
    "Sailu",
    "Murtijapur",
    "Tasgaon",
    "Mehkar",
    "Yawal",
    "Pulgaon",
    "Nilanga",
    "Wai",
    "Umarga",
    "Paithan",
    "Rahuri",
    "Nawapur",
    "Tuljapur",
    "Morshi",
    "Purna",
    "Satana",
    "Pathri",
    "Sinnar",
    "Uchgaon",
    "Uran",
    "Pen",
    "Karjat",
    "Manwath",
    "Partur",
    "Sangole",
    "Mangrulpir",
    "Risod",
    "Shirur",
    "Savner",
    "Sasvad",
    "Pandharkaoda",
    "Talode",
    "Shrigonda",
    "Shirdi",
    "Raver",
    "Mukhed",
    "Rajura",
    "Vadgaon Kasba",
    "Tirora",
    "Mahad",
    "Lonar",
    "Sawantwadi",
    "Pathardi",
    "Pauni",
    "Ramtek",
    "Mul",
    "Soyagaon",
    "Mangalvedhe",
    "Narkhed",
    "Shendurjana",
    "Patur",
    "Mhaswad",
    "Loha",
    "Nandgaon",
    "Warud",
    "Bhandara",
    "Chandrapur",
    "Gadchiroli",
    "Gondia",
    "Hingoli",
    "Kolhapur",
    "Malvan",
    "Oros",
    "Boisar",
    "Deoli",
    "Arjuni Morgaon",
    "Aheri",
    "Sironcha",
    "Tiroda",
    "Bramhapuri",
    "Jalgaon",
    "Jalna",
    "Alibag",
    "Sindhudurg",
    "Mumbra",
    "Fort",
    "Buldhana",
    "Hinganghat",
    "Chikhli",
    "Shahapur",
    "Shrivardhan",
    "Dapoli",
    "Murbad",
    "Baramati",
    "Bhusawal",
    "Chalisgaon",
    "Dombivli",
    "Khamgaon",
    "Kharghar",
    "Osmanabad",
    "Rahimatpur",
    "Rajapur",
    "Roha",
    "Saphale",
    "Shirpur",
    "Talegaon",
    "Vengurla",
    "Karad",
    "Akluj",
    "Ambarnath",
    "Ambajogai"
  ],
   Karnataka: [
    "Heroor",
    "Addur",
    "Adityapatna",
    "Adyar",
    "Afzalpur",
    "Aland",
    "Alevoor",
    "Allipura",
    "Alnavar",
    "Alur",
    "Amaravathi",
    "Ambikanagara",
    "Aminagad",
    "Anekal",
    "Ankola",
    "Annigeri",
    "Arasinakunte",
    "Arkalgud",
    "Arkula",
    "Arsikere",
    "Athni",
    "Attibele",
    "Aurad",
    "Aversa",
    "Bada",
    "Badagabettu",
    "Badagaulipady",
    "Badami",
    "Bagalkot",
    "Bagepalli",
    "Bail Hongal",
    "Bajpe",
    "Bangalore",
    "Bangarapet",
    "Bankapura",
    "Bannur",
    "Bantval",
    "Basavakalyan",
    "Basavana Bagevadi",
    "Basettihalli",
    "Belgaum",
    "Belgaum Cantonment",
    "Bellary",
    "Belma",
    "Beltangadi",
    "Belur",
    "Belvata",
    "Benakanahalli",
    "Bethamangala",
    "Bhadravati",
    "Bhalki",
    "Bhatkal",
    "Bhimarayanagudi",
    "Bhogadi",
    "Bidadi",
    "Bidar",
    "Bijapur",
    "Bilgi",
    "Birur",
    "Bobruwada",
    "Bommasandra",
    "Bondathila",
    "Byadgi",
    "Byrapura",
    "Challakere",
    "Chamarajanagar",
    "Channagiri",
    "Channapatna",
    "Channarayapatna",
    "Chelur",
    "Chikkaballapura",
    "Chikkabanavara",
    "Chikkabidarakallu",
    "Chikkajajur",
    "Chikmagalur",
    "Chiknayakanhalli",
    "Chincoli",
    "Chintamani",
    "Chitapur",
    "Chitgoppa",
    "Chitradurga",
    "Dandeli",
    "Davanagere",
    "Devadurga",
    "Devanahalli",
    "Dod Ballapur",
    "Dommasandra",
    "Donimalai Township",
    "Elwala",
    "Gadag-Betigeri",
    "Gajendragarh",
    "Gangawati",
    "Gargeswari",
    "Gauribidanur",
    "Gogipeth",
    "Gokak",
    "Gokak Falls",
    "Gonikoppal",
    "Gubbi",
    "Gudibanda",
    "Gudur",
    "Gulbarga",
    "Guledgudda",
    "Gundlupet",
    "Gurmatkal",
    "Haliyal",
    "Hangal",
    "Hanur",
    "Haralapura",
    "Harapanahalli",
    "Harekala",
    "Harihar",
    "Hassan",
    "Hatti",
    "Hatti Gold Mines",
    "Haveri",
    "Hebbagodi",
    "Heggadadevankote",
    "Hindalgi",
    "Hinkal",
    "Hirekerur",
    "Hiriyur",
    "Holalkere",
    "Hole Narsipur",
    "Homnabad",
    "Honavar",
    "Hongalli",
    "Honnali",
    "Hoovina Hadagalli",
    "Hosakote",
    "Hosanagara",
    "Hosdurga",
    "Hospet",
    "Hubli-Dharwad",
    "Hukeri",
    "Huliyar",
    "Hunasamaranahalli",
    "Hungund",
    "Hunsur",
    "Hutagalli",
    "Ilkal",
    "Indi",
    "Jagalur",
    "Jali",
    "Jamkhandi",
    "Jevargi",
    "Jigani",
    "Jog Kargal",
    "Kadakola",
    "Kadigenahalli",
    "Kadur",
    "Kadwad",
    "Kairangala",
    "Kakati",
    "Kalghatgi",
    "Kamalapuram",
    "Kamalnagar",
    "Kamatgi",
    "Kampli",
    "Kanakapura",
    "Kangrali BK",
    "Kangrali KH",
    "Kariyangala",
    "Karkal",
    "Karwar",
    "Kawalettu",
    "Kenjar",
    "Kerur",
    "Khanapur",
    "Kodiyal",
    "Kolambe",
    "Kolar",
    "Kollegal",
    "Konaje",
    "Konappana Agrahara",
    "Konnur",
    "Koorgalli",
    "Koppa",
    "Koppal",
    "Korangrapady",
    "Koratagere",
    "Kotekara",
    "Koteshwar",
    "Kotturu",
    "Krishnarajanagara",
    "Krishnarajpet",
    "Kudchi",
    "Kudligi",
    "Kudremukh",
    "Kudur",
    "Kumbalagodu",
    "Kumta",
    "Kundapura",
    "Kundgol",
    "Kunigal",
    "Kurekuppa",
    "Kurgunta",
    "Kushalnagar",
    "Kushtagi",
    "Kuvettu",
    "Lakshmeshwar",
    "Lingsugur",
    "Londa",
    "Machche",
    "Madanaiyakanahalli",
    "Maddur",
    "Madhugiri",
    "Madikeri",
    "Magadi",
    "Mahalingpur",
    "Malavalli",
    "Mallar",
    "Malur",
    "Mandya",
    "Mangalore",
    "Manipura",
    "Manjanady",
    "Manvi",
    "Maragondahalli",
    "Matadakurubarahatti",
    "Mellahalli",
    "Molakalmuru",
    "Moodabettu",
    "Mouje Nandgad",
    "Mudalgi",
    "Mudbidri",
    "Muddebihal",
    "Mudgal",
    "Mudhol",
    "Mudigere",
    "Muduperar",
    "Mudushedde",
    "Mulbagal",
    "Mulgund",
    "Mulki",
    "Mulur",
    "Mundargi",
    "Mundgod",
    "Munirabad Project Area",
    "Munnur",
    "Munnuru",
    "Mutga",
    "Mysore",
    "Nadsal",
    "Nagamangala",
    "Nanjangud",
    "Narasimharajapura",
    "Naregal",
    "Nargund",
    "Narikombu",
    "Navalgund",
    "Navoor",
    "Neermarga",
    "Nelamangala",
    "Nipani",
    "Pandavapura",
    "Pavagada",
    "Peeranwadi",
    "Piriyapatna",
    "Pudu",
    "Puttur",
    "Rabkavi Banhatti",
    "Raichur",
    "Ramanagara",
    "Ramdurg",
    "Ranibennur",
    "Raybag",
    "Robertson Pet",
    "Ron",
    "Sadalgi",
    "Sagar",
    "Saidapur",
    "Sajipanadu",
    "Sakleshpur",
    "Saligram",
    "Sambra",
    "Sandur",
    "Sankeshwar",
    "Sanoor",
    "Saragur",
    "Sarjapura",
    "Satyamangala",
    "Saundatti-Yellamma",
    "Savanur",
    "Sedam",
    "Shahabad",
    "Shahabad ACC",
    "Shahpur",
    "Shaktinagar",
    "Shiggaon",
    "Shikarpur",
    "Shimoga",
    "Shirhatti",
    "Shorapur",
    "Shravanabelgola",
    "Shrirangapattana",
    "Siddapur",
    "Sidlaghatta",
    "Sindgi",
    "Sindhnur",
    "Sira",
    "Siralkoppa",
    "Sirsi",
    "Siruguppa",
    "Someshwar",
    "Somvarpet",
    "Sorab",
    "Sringeri",
    "Srinivaspur",
    "Srirampura",
    "Sulebhavi",
    "Sulya",
    "Talapady",
    "Talipady",
    "Tarikere",
    "Tattilli",
    "Tekkalakote",
    "Tenkanidyoor",
    "Terdal",
    "Thokur",
    "Thumbe",
    "Tiptur",
    "Tirthahalli",
    "Tirumakudal Narsipur",
    "Tonse East",
    "Tumkur",
    "Turuvekere",
    "Udupi",
    "Udyavara",
    "Ullal",
    "Uppinangady",
    "Vaddu",
    "Varamballi",
    "Venkatapura",
    "Vijayapura",
    "Virajpet",
    "Vittal",
    "Wadi",
    "Yadgir",
    "Yelandur",
    "Yelbarga",
    "Yellapur",
    "Yellur",
    "Yenagudde",
  ],
   Gujarat: [
    "Adalaj",
    "Ahmadabad (Ahmedabad)",
    "Ahmadabad Cantonment",
    "Ahwa",
    "Alang",
    "Alang-Sosiya",
    "Alikherva",
    "Amardad",
    "Ambaji",
    "Ambaliyasan",
    "Amboli",
    "Amod",
    "Amreli",
    "Anand",
    "Anandpar",
    "Andada",
    "Anjar",
    "Anklav",
    "Anklesvar (Ankleshwar)",
    "Anklesvar INA",
    "Antaliya",
    "Antarjal",
    "Arsodiya",
    "Atul",
    "Baben",
    "Babra",
    "Bagasara",
    "Bajwa",
    "Balasinor",
    "Balitha",
    "Baliyasan",
    "Bansda (Vansda)",
    "Bantwa (Bantva)",
    "Bardoli",
    "Bareja",
    "Barwala",
    "Bavla",
    "Bayad",
    "Bechar (Becharaji)",
    "Bhabhar",
    "Bhachau",
    "Bhadkodara",
    "Bhagal (Jagana)",
    "Bhagdawada",
    "Bhalpara",
    "Bhanvad",
    "Bharthana Kosad",
    "Bharuch",
    "Bharuch INA",
    "Bhavnagar",
    "Bhayavadar",
    "Bhilad",
    "Bhiloda",
    "Bholav",
    "Bhuj",
    "Bhurivel",
    "Bilimora",
    "Bilimora (Talodh)",
    "Bodeli",
    "Bopal",
    "Boriavi",
    "Borsad",
    "Botad",
    "Chaklasi",
    "Chalala",
    "Chalthan",
    "Chanasma",
    "Chandrapur",
    "Chanod",
    "Chhapi",
    "Chhapra",
    "Chhatral",
    "Chhatral INA",
    "Chhaya",
    "Chhiri",
    "Chhota Udaipur",
    "Chikhli",
    "Chiloda (Naroda)",
    "Chorvad",
    "Chotila",
    "Dabhoi",
    "Daheli",
    "Dakor",
    "Damnagar",
    "Dediapada",
    "Deesa",
    "Dehari",
    "Dehgam (Dahegam)",
    "Deodar",
    "Devgadbaria (Devgadh Baria)",
    "Devsar",
    "Dhandhuka",
    "Dhanera",
    "Dharampur",
    "Dhasa Vishi",
    "Dhola",
    "Dholka",
    "Dhoraji",
    "Dhrangadhra",
    "Dhrol",
    "Digvijaygram",
    "Dohad (Dahod)",
    "Dungarpur",
    "Dwarka",
    "Freelandgunj",
    "Gadhada",
    "Gadkhol",
    "Galpadar",
    "Gamdi",
    "Gandevi",
    "Gandhidham",
    "Gandhinagar",
    "Gariadhar",
    "Ghanteshvar",
    "Ghogha",
    "Godhra",
    "Gondal",
    "GSFC (Motikhavdi Sikka)",
    "GSFC Complex INA",
    "Hadgood",
    "Hajira INA",
    "Halol",
    "Halvad",
    "Harij",
    "Himatnagar",
    "Ichchhapor",
    "Idar",
    "Jafrabad",
    "Jafrabad",
    "Jambusar",
    "Jamjodhpur",
    "Jamnagar",
    "Jarod",
    "Jasdan",
    "Jawaharnagar (Gujarat Refinery)",
    "Jetalsar",
    "Jetpur",
    "Jetpur Navagadh",
    "Jhadeshwar",
    "Jhalod",
    "Junagadh",
    "Kabilpor",
    "Kadi",
    "Kadodara",
    "Kakoshi",
    "Kalavad",
    "Kaliawadi",
    "Kalol",
    "Kalol",
    "Kalol INA",
    "Kalol INA",
    "Kandla",
    "Kanjari",
    "Kanodar",
    "Kansad",
    "Kapadvanj",
    "Karachiya",
    "Karamsad",
    "Karjan",
    "Karvad",
    "Kathlal",
    "Katpar",
    "Kavant",
    "Keshod",
    "Kevadiya",
    "Khambhalia (Jamkhambhaliya)",
    "Khambhat",
    "Khapat",
    "Kharach",
    "Kharaghoda",
    "Kheda",
    "Khedbrahma",
    "Kheralu",
    "Kim",
    "Kodinar",
    "Kosamba",
    "Kotharia",
    "Kutiyana",
    "Lathi",
    "Lavachha",
    "Lilia",
    "Limbdi",
    "Limkheda",
    "Limla",
    "Lodhika",
    "Lunawada (Lunavada)",
    "Madhapar",
    "Magdalla",
    "Mahendranagar",
    "Mahesana (Mehsana)",
    "Mahudha",
    "Mahuva",
    "Mahuvar",
    "Maktampur",
    "Malanka",
    "Maliya",
    "Malpur",
    "Manavadar",
    "Mandvi",
    "Mandvi",
    "Mangrol",
    "Mankuva",
    "Mansa",
    "Meghraj",
    "Mehmedabad",
    "Mirjhapar",
    "Mithapur",
    "Modasa",
    "Mora",
    "Morvi (Morbi)",
    "Mundra",
    "Nadiad",
    "Nanakwada (Nanakvada)",
    "Nandej",
    "Nandelav",
    "Nandesari",
    "Nandesari INA",
    "Nari",
    "Nasvadi",
    "Nava Bhildi",
    "Navsari",
    "Ode",
    "Okha",
    "Orvad",
    "Paddhari",
    "Padra",
    "Palaj",
    "Palanpur",
    "Palej",
    "Palitana",
    "Panoli",
    "Parabada",
    "Pardi",
    "Pardi Kanade",
    "Pardi Parnera",
    "Pardi Sondhpur",
    "Parnera",
    "Patan",
    "Patdi",
    "Pethapur",
    "Petlad",
    "Petro-Chemical Complex INA",
    "Porbandar",
    "Por-Ramangamdi",
    "Prantij",
    "Radhanpur",
    "Rajkot",
    "Rajpipla",
    "Rajula",
    "Ranavav",
    "Ranoli",
    "Ranpur",
    "Rapar",
    "Raval",
    "Ravapara",
    "Reliance Complex",
    "Sachin",
    "Sachin INA",
    "Sagbara",
    "Saij",
    "Saktasanala",
    "Salaya",
    "Salvav",
    "Sanand",
    "Sanjali",
    "Sanjan",
    "Sanjeli",
    "Santrampur",
    "Saputara",
    "Sarangpore",
    "Sarigam",
    "Sarigam INA",
    "Sathamba",
    "Savarkundla",
    "Savgadh",
    "Savli",
    "Sayan",
    "Selamba",
    "Shaktinagar",
    "Shapur",
    "Shehera",
    "Sherpura",
    "Sidhpur",
    "Sidsar",
    "Sihor",
    "Sikka",
    "Singarva",
    "Sojitra",
    "Solsumba",
    "Songadh",
    "Songadh",
    "Sukhpar",
    "Surat",
    "Surendranagar Dudhrej (Dudhrej)",
    "Sutrapada",
    "Talaja",
    "Talala",
    "Talod",
    "Tarsadi",
    "Tarsali",
    "Thangadh",
    "Thara",
    "Tharad",
    "Thasra",
    "Trajpar",
    "Ukai",
    "Umbergaon",
    "Umbergaon INA",
    "Umrala",
    "Umreth",
    "Una",
    "Undera",
    "Unjha",
    "Upleta",
    "Vadali",
    "Vadnagar",
    "Vadodara",
    "Vaghodia (Waghodia)",
    "Vaghodia INA",
    "Valia-Jhagadia, GNFC Scooter Project Area",
    "Valia-Naldhari",
    "Vallabhipur (Vallabhi)",
    "Vallabh Vidyanagar (Vallabh Vidhyanagar)",
    "Valsad",
    "Valsad INA",
    "Vanthali",
    "Vapi",
    "Vapi INA",
    "Vareli",
    "Vartej",
    "Vasna Borsad INA",
    "Vavdi Bujarg",
    "Vavol",
    "Veraval",
    "Veraval",
    "Vijalpor",
    "Vijapur",
    "Vijaynagar",
    "Viramgam",
    "Virpur",
    "Visavadar",
    "Visnagar",
    "Vithal Udyognagar INA",
    "Vyara",
    "Wadhwan",
    "Waghai",
    "Wankaner"
  ],
  Haryana: [
    "Aakera",
    "Adampur",
    "Ambala",
    "Ambala Cantonment",
    "Ambala Sadar",
    "Asan Khurd",
    "Assandh",
    "Ateli",
    "Babiyal",
    "Badhi Majra",
    "Badh Malak",
    "Badshahpur",
    "Baghola",
    "Bahadurgarh",
    "Barara",
    "Barwala",
    "Bawal",
    "Bawani Khera",
    "Bayyanpur",
    "Beri",
    "Bhakali",
    "Bhiwani",
    "Bhondsi",
    "Bhuran",
    "Bilaspur",
    "Bir Ghaghar",
    "Boh",
    "Buria",
    "Chandi Mandir",
    "Charkhi Dadri",
    "Cheeka",
    "Chhachhrauli",
    "Dharuhera",
    "Ellenabad",
    "Faizabad",
    "Farakhpur",
    "Faridabad",
    "Farrukhnagar",
    "Fatehabad",
    "Fazalpur",
    "Ferozepur Jhirka",
    "Ganaur",
    "Gangwa",
    "Garhi Harsaru",
    "Gharaunda",
    "Ghatal Mahaniawas",
    "Gohana",
    "Gurgaon",
    "Hailey Mandi",
    "Hansi",
    "Hassan Pur",
    "Hathin",
    "Hisar",
    "HMT Pinjore",
    "Hodal",
    "Indri",
    "Ismailabad",
    "Jagadhri",
    "Jandli",
    "Jhajjar",
    "Jhakal Mandi (Jakhal Mandi)",
    "Jind",
    "Julana",
    "Kabri",
    "Kachrauli",
    "Kaithal",
    "Kakar Majra",
    "Kalanaur",
    "Kalanwali",
    "Kalayat",
    "Kalka",
    "Kanina",
    "Kansepur",
    "Kanwla",
    "Kardhan",
    "Karnal",
    "Kharkhoda",
    "Kheri Nangal",
    "Khori Kalan",
    "Kundli",
    "Ladrawan",
    "Ladwa",
    "Loharu",
    "Maham",
    "Maheshari",
    "Majra",
    "Mandi Dabwali",
    "Manendragarh",
    "Manesar",
    "Manethi",
    "Mayyer",
    "Mustafabad",
    "Nagal Chaudhry (Nangal Choudhary)",
    "Nagina",
    "Nanhera",
    "Naraingarh",
    "Narnaul",
    "Narnaund",
    "Narwana",
    "Nilokheri",
    "Nissing",
    "Nuh",
    "Palwal",
    "Palwal Rural",
    "Panchkula (Urban Estate)",
    "Panipat",
    "Panipat Taraf Ansar",
    "Panipat Taraf Makhdum Zadgan",
    "Panipat Taraf Rajputan",
    "Pataudi",
    "Pehowa",
    "Piala",
    "Pingwan",
    "Pinjore",
    "Punahana",
    "Pundri",
    "Radaur",
    "Raipur Rani",
    "Ram Garh",
    "Rampura",
    "Rania",
    "Ratia",
    "Rewari",
    "Rohtak",
    "Sadaura",
    "Safidon",
    "Saha",
    "Salamba",
    "Samalkha",
    "Sampla",
    "Sasauli",
    "Satrod Kalan",
    "Satrod Khas",
    "Satrod Khurd",
    "Sector 11 & Sector 12 Part II",
    "Shahbad (Shahabad Markanda)",
    "Sikanderpur",
    "Sirsa",
    "Siwani",
    "Sohna",
    "Sonipat",
    "Sunari Kalan",
    "Taoru",
    "Taraori",
    "Thanesar",
    "Tilpat",
    "Tohana",
    "Tosham",
    "Tundla",
    "Uchana",
    "Ugra Kheri",
    "Uklana Mandi",
    "Uncha Siwana",
    "Yamunanagar"
  ],
  "Tamil Nadu": [
    "Abiramam",
    "Achampudur",
    "Acharapakkam",
    "Achchipatti",
    "Adaikkakuzhi",
    "Adikaratti",
    "Adiramapattinam (Adirampattinam)",
    "Adiyanuthu",
    "Aduthurai (Maruthuvakudi)",
    "Agaram",
    "Agastheeswaram",
    "Alagappapuram (Azhagappapuram)",
    "Alamathi",
    "Alamelumangapuram",
    "Alampalayam",
    "Alandur",
    "Alanganallur",
    "Alangayam",
    "Alangudi",
    "Alangulam",
    "Alanthurai",
    "Alapakkam",
    "Allapuram",
    "Alur (Aloor)",
    "Alwarkurichi",
    "Alwarthirunagiri",
    "Amathur",
    "Ambasamudram",
    "Ambattur",
    "Ambur",
    "Ammainaickanur",
    "Ammanur",
    "Ammapattinam",
    "Ammapettai",
    "Ammapettai",
    "Ammavarikuppam",
    "Ammoor",
    "Anaimalai",
    "Anaiyur",
    "Anaiyur",
    "Anakaputhur",
    "Andankoil East",
    "Andipalayam",
    "Andipatti Jakkampatti",
    "Anjugrammam (Anjugramam)",
    "Annalagraharam",
    "Annamalai Nagar",
    "Annavasal",
    "Annur",
    "Anthiyur",
    "Anuppankulam",
    "Appakudal",
    "Arachalur",
    "Arakandanallur",
    "Arakonam (Arakkonam)",
    "Aralvaimozhi",
    "Arani",
    "Arani (Arni)",
    "Arasiramani",
    "Arasur",
    "Aravakurichi",
    "Aravankad (Aruvankadu)",
    "Arcot",
    "Arimalam",
    "Ariyalur",
    "Ariyalur",
    "Ariyappampalayam",
    "Ariyur",
    "Arumanai",
    "Arumbanur",
    "Arumbavur",
    "Arumuganeri",
    "Aruppukkottai",
    "Asaripallam",
    "Ashokapuram",
    "Athani",
    "Athanur",
    "Athimarapatti",
    "Athipatti",
    "Athipattu",
    "Athivilai",
    "Athur",
    "Athur",
    "Attayampatti",
    "Attur",
    "Avadattur",
    "Avadi",
    "Avalapalli",
    "Avalpoondurai",
    "Avanashi (Avinashi)",
    "Avaniapuram",
    "A. Vellalapatti (Vellalapatti)",
    "Ayacode",
    "Ayakudi",
    "Ayappakkam",
    "Aygudi",
    "Ayothiapattinam",
    "Ayyalur",
    "Ayyampalayam",
    "Ayyampettai",
    "Ayyampettai",
    "Ayyappanthangal",
    "Azhagiapandipuram (Azhagiapandiapuram)",
    "Balakrishnampatti",
    "Balakrishnapuram",
    "Bargur",
    "Batlagundu",
    "Belur",
    "Bhavani",
    "Bhavanisagar",
    "Bhuvanagiri",
    "Bikketti",
    "B.Mallapuram",
    "B. Meenakshipuram",
    "Bodinayakanur (Bodinayakkanur)",
    "Boothapandi",
    "Boothipuram",
    "Brahmana Periya Agraharam",
    "Chakkarapalli",
    "Chathirareddipatti",
    "Chatrapatti",
    "Chenbagaramanputhur",
    "Chengalpattu",
    "Chengam",
    "Chengappalli",
    "Chennagiri",
    "Chennai [Madras]",
    "Chennasamudram",
    "Chennimalai",
    "Cheranmadevi",
    "Chetpet (Chettupattu)",
    "Chettiarpatti",
    "Chettinaickenpatti",
    "Chettipalayam",
    "Chettipalayam",
    "Chettithangal",
    "Chidambaram",
    "Chidambaram Nm",
    "Chinna Anuppanadi",
    "Chinnakalayamputhur",
    "Chinnakkampalayam",
    "Chinnalapatti",
    "Chinnamanur",
    "Chinnampalayam (Chinniampalayam)",
    "Chinnamudalaipatti",
    "Chinnasalem",
    "Chinnasekkadu",
    "Chinnathadagam",
    "Chinnavedampatti",
    "Chinniam palayam",
    "Chithode",
    "Chitlapakkam",
    "Cholapuram",
    "Choozhal",
    "Coimbatore",
    "Colachel (Kolachal)",
    "Coonoor",
    "Courtalam (Courtallam)",
    "Cuddalore",
    "Dalavaipatti",
    "Damalerimuthur",
    "Dasanaickenpatti",
    "Denkanikottai",
    "Desur",
    "Devadanapatti",
    "Devakottai",
    "Devarshola",
    "Devasthanam",
    "Devikapuram",
    "Devipattinam",
    "Dhalavoipuram",
    "Dhali",
    "Dhaliyur",
    "Dharamapuram",
    "Dharapadavedu",
    "Dharapuram",
    "Dharasuram (Darasuram)",
    "Dharmapuri",
    "Dindigul",
    "Doramangalam",
    "Dusi",
    "Edaganasalai",
    "Edaicode (Edaikodu)",
    "Edappadi",
    "Edayanchavadi",
    "Elathur",
    "Elayirampannai",
    "Ellakkudy",
    "Ellandaikuttai",
    "Elumalai",
    "Eral",
    "Eranapuram",
    "Eriodu (Eriyodu)",
    "Erode",
    "Erumapalayam",
    "Eruvadi",
    "Ethapur",
    "Ettayapuram",
    "Ettimadai",
    "Ezhudesam",
    "Ganapathipuram",
    "Gandhinagar (Katpadi Extn)",
    "Gandipuram",
    "Gangaikondan",
    "Gangavalli",
    "Ganguvarpatti",
    "Gerugambakkam",
    "Gingee",
    "Gobichettipalayam",
    "Gopalasamudram",
    "Goundampalayam",
    "Gudalur",
    "Gudalur",
    "Gudalur",
    "Gudiyatham",
    "Gummidipoondi",
    "Gunduuppalavadi",
    "Hale-Dharmapuri",
    "Hanumanthampatti",
    "Harur",
    "Harveypatti",
    "Highways",
    "Hosur",
    "Hubbathala",
    "Huligal",
    "Idikarai",
    "Iduvai",
    "Ilampillai (Elampillai)",
    "Ilanji",
    "Ilayangudi (Ilaiyangudi)",
    "Iluppaiyurani",
    "Iluppur",
    "Inam Karur",
    "Inam Maniyachi",
    "Injambakkam",
    "Iravadanallur",
    "Irugur",
    "Jaffrabad",
    "Jagathala",
    "Jalakandapuram",
    "Jambai",
    "Jayankondam",
    "Jolarpet",
    "Kadambathur",
    "Kadambur",
    "Kadaparai",
    "Kadathur",
    "Kadayanallur",
    "Kadayanallur",
    "Kadhirvedu",
    "Kailasagiri",
    "Kakkalur",
    "Kalakad (Kalakkad)",
    "Kalambur",
    "Kalapatti",
    "Kalappanaickenpatti",
    "Kalavai",
    "Kalinjur",
    "Kaliyakkavilai",
    "Kalladaikurichi",
    "Kallakkurichi (Kallakurichi)",
    "Kallakudi (Kallakudy)",
    "Kallangudy",
    "Kallukuttam",
    "Kalparapatti",
    "Kalugumalai",
    "Kanakkampalayam (in: Udumalaipettai subdistrict)",
    "Kanakkampalayam (in: Tiruppur subdistrict)",
    "Kanam",
    "Kancheepuram (Kanchipuram)",
    "Kandanur",
    "Kangeyam",
    "Kangeyanallur",
    "Kaniyambadi",
    "Kaniyur",
    "Kaniyur",
    "Kanjiikoil",
    "Kannamangalam",
    "Kannampalayam",
    "Kannanendal (Kannadendal)",
    "Kannankurichi",
    "Kannanoor",
    "Kannapalayam",
    "Kannivadi",
    "Kannivadi",
    "Kanniyakumari (Kanyakumari)",
    "Kappiyarai",
    "Karadipatti",
    "Karaikkudi (Karaikudi)",
    "Karaipudur",
    "Karamadai",
    "Karambakkam",
    "Karambakkudi",
    "Kariamangalam",
    "Kariapatti",
    "Karugampattur",
    "Karukkalvadi",
    "Karumandi Chellipalayam",
    "Karungal",
    "Karunguzhi",
    "Karuppur",
    "Karur",
    "Kasinayagampatti",
    "Kasipalayam (E)",
    "Kasipalayam (G) (Kasipalayam-Gobi)",
    "Katpadi",
    "Kattathurai",
    "Kattiganapalli (Kathujuganapalli)",
    "Kattimancode",
    "Kattivakkam (Kathivakkam)",
    "Kattumannarkoil",
    "Kattupakkam",
    "Kattuputhur",
    "Kaveripakkam",
    "Kaveripattinam",
    "Kayalpattinam",
    "Kayatharu",
    "Keelakarai (Kilakarai)",
    "Keelamanjakudi",
    "Keeramangalam",
    "Keeranur",
    "Keeranur",
    "Keeripatti",
    "Keezhkulam (Kilkulam)",
    "Kelamangalam",
    "Kembainaickenpalayam",
    "Kethi (Ketti)",
    "Kila Ambur",
    "Kilampadi",
    "Kilapavoor (Keezhapavur)",
    "Kilkunda",
    "Killai",
    "Killiyoor (Killiyur)",
    "Kilmanavur",
    "Kilpennathur (Kizh-Pennathur)",
    "Kilpudupakkam",
    "Kilvaithinankuppam",
    "Kilvelur",
    "Kinathukadavu",
    "K.Madapur",
    "Kodaikanal",
    "Kodavasal (Kudavasal)",
    "Kodivalasa",
    "Kodumudi",
    "Koilambakkam",
    "Koilpalayam",
    "Kolappalur",
    "Kolathupalayam",
    "Kolathur",
    "Kollancode (Kollankodu)",
    "Kollankoil",
    "Komaralingam",
    "Kombai",
    "Konavattam",
    "Kondalampatti",
    "Kondappanaickenpatti",
    "Kondasamudram",
    "Kondichettipatti",
    "Kondur",
    "Konerikuppam",
    "Konganapuram",
    "Kooraikundu",
    "Koothappar",
    "Koradacheri",
    "Kosavampatti",
    "Kotagiri",
    "Kothanallur (Kothinallur)",
    "Kottagoundampatty",
    "Kottaiyur",
    "Kottakuppam",
    "Kottaram",
    "Kottivakkam",
    "Kottur",
    "Kovalam (Covelong)",
    "Kovilpatti",
    "Kovur",
    "Krishnagiri",
    "Krishnarayapuram",
    "Krishnasamudram",
    "Kuchanur",
    "Kulappuram",
    "Kulasekaram (Kulasekarapuram)",
    "Kulathur (Kulathoor)",
    "Kulithalai",
    "Kullursandai",
    "Kumaragiri",
    "Kumarapalayam (Komarapalayam)",
    "Kumarapuram",
    "Kumbakonam",
    "Kundrathur",
    "Kuniyamuthur",
    "Kurichi",
    "Kurinjipadi",
    "Kurudampalayam",
    "Kurukkupatti",
    "Kurumbalur",
    "Kurumbapatti",
    "Kuruppanaickenpalayam",
    "Kuthalam",
    "Kuthanallur",
    "Kuthankuzhi",
    "Kuzhithurai",
    "Labbaikudikadu",
    "Lakkampatti",
    "Lakkiampatti",
    "Lakshminarayanapuram",
    "Lalgudi",
    "Lalpet",
    "Madaharpakkam",
    "Madambakkam",
    "Madambakkam (in: Sriperumbudur subdistrict)",
    "Madathukulam",
    "Madavaram (Madhavaram)",
    "Madippakkam (Madipakkam)",
    "Madukkarai",
    "Madukkur",
    "Madurai",
    "Maduranthakam",
    "Maduravoyal",
    "Majaragollappatti",
    "Makkinampatti",
    "Malayadi",
    "Mallamooppampatti",
    "Mallankinaru",
    "Mallasamudram",
    "Mallur",
    "Malumichampatti",
    "Mamallapuram (Mahabalipuram)",
    "Mamsapuram",
    "Manachanallur",
    "Manakudi",
    "Manali",
    "Manalmedu",
    "Manalurpet",
    "Manamadurai",
    "Manapakkam",
    "Manapparai",
    "Manavalakurichi",
    "Mancad",
    "Mandaikadu",
    "Mandapam",
    "Mangadu",
    "Mangalam",
    "Mangalampet",
    "Manickapuram",
    "Manimutharu",
    "Manjakollai",
    "Manjalumoodu",
    "Mannarai",
    "Mannargudi",
    "Manthithoppu",
    "Mappilaiurani",
    "Maraimalainagar",
    "Marakkanam",
    "Maramangalathupatti",
    "Marandahalli",
    "Markayankottai",
    "Marudur",
    "Marungur (Marungoor)",
    "Maruthancode",
    "Masinaickenpatty",
    "Mathicode",
    "Mathigiri",
    "Mathur",
    "Mayiladuthurai",
    "Mecheri",
    "Medavakkam",
    "Meenambakkam",
    "Melacheval",
    "Melachokkanathapuram",
    "Melagaram",
    "Melamadai",
    "Melaparthibanur",
    "Melathiruppanthuruthi",
    "Melattur",
    "Melpattampakkam",
    "Melur",
    "Melvisharam",
    "Methukummal",
    "Mettamalai",
    "Mettunasuvanpalayam",
    "Mettupalayam",
    "Mettupalayam",
    "Mettur",
    "Mevalurkuppam",
    "Midalam",
    "Milavittan",
    "Minampalli-Pachamadevi",
    "Minjur",
    "Modakurichi",
    "Mohanur",
    "Molachur",
    "Mookondapalli",
    "Moolakaraipatti",
    "Moovarasampettai",
    "Mopperipalayam",
    "Morattupalayam",
    "Mudukulathur",
    "Mugalivakkam",
    "Mukasipidariyur",
    "Mukkudal",
    "Mulagumudu",
    "Mulanur",
    "Mullipattu",
    "Muruganpalayam",
    "Musiri",
    "Muthanampalayam",
    "Muthugoundam Pudur",
    "Muthukadu",
    "Muthupet",
    "Muthur",
    "Muttayyapuram",
    "Muzhucode",
    "Mylaudy (Myladi)",
    "Nadaikavu",
    "Nadukuthagai",
    "Naduvaneri",
    "Naduvattam",
    "Nagamalaipudukottai",
    "Nagamangalam",
    "Nagapattinam",
    "Nagavakulam",
    "Nagercoil",
    "Nagojanahalli",
    "Nallampatti",
    "Nallipalayam",
    "Nalloor (Nallur)",
    "Nallur",
    "Nallur $",
    "Namagiripettai",
    "Namakkal",
    "Nambiyur",
    "Nandambakkam",
    "Nandivaram - Guduvancheri",
    "Nangavalli",
    "Nangavaram",
    "Nanguneri",
    "Nanjikottai",
    "Nannilam",
    "Naranammalpuram",
    "Narasimhanaicken-palayam",
    "Narasingam",
    "Narasingapuram",
    "Narasingapuram",
    "Naravarikuppam",
    "Nasiyanur",
    "Natchiarkoil",
    "Natham",
    "Nathampannai",
    "Natrampalli",
    "Nattalam",
    "Nattapettai",
    "Nattarasankottai",
    "Navalpattu",
    "Navlock Garden",
    "Nazarathpettai",
    "Nazareth",
    "Nedungundram",
    "Needamangalam",
    "Neelagiri",
    "Neelambur",
    "Neelankarai",
    "Neikkarapatti",
    "Nellikuppam",
    "Nelliyalam",
    "Neripperichal",
    "Nerkunram (Nerkundram)",
    "Nerkuppai",
    "Nerunjipettai",
    "Neykkarappatti",
    "Neyveli",
    "Neyyoor",
    "Nilaiyur I Bit",
    "Nilakkottai",
    "Nolambur",
    "Nullivilai",
    "Odaipatti",
    "Odaiyakulam",
    "Oddanchatram",
    "Odugathur",
    "Oggiyamduraipattu",
    "Olagadam",
    "Omalur",
    "Orathanadu (Mukthambalpuram)",
    "Orikkai",
    "Othakadai",
    "Othakalmandapam",
    "Ottapparai",
    "O' Valley",
    "Overi",
    "Pachchal",
    "Pacode",
    "Padandal",
    "Padappai",
    "Padianallur",
    "Padikkasu vaithanpatti",
    "Padirikuppam",
    "Padmanabhapuram",
    "Painkulam",
    "Paiyur",
    "Palaganangudy",
    "Palakkodu",
    "Palamedu",
    "Palangarai",
    "Palani",
    "Palani Chettipatti",
    "Palappallam",
    "Palavakkam",
    "Palavansathu",
    "Palayam",
    "Palayampatti",
    "Palladam",
    "Pallallur",
    "Pallapalayam",
    "Pallapalayam",
    "Pallapatti",
    "Pallapatti",
    "Pallathur",
    "Pallavaram",
    "Pallikaranai",
    "Pallikonda",
    "Pallipalayam",
    "Pallipalayam Agraharam",
    "Pallipattu",
    "Pallippadai",
    "Paloor",
    "Palugal",
    "Pammal",
    "Panagudi",
    "Panaimarathupatti",
    "Panapakkam",
    "Pandamangalam",
    "Pandavarmangalam",
    "Pannaikadu",
    "Pannaipuram",
    "Panpoli",
    "Panruti",
    "Papanasam",
    "Pappankurichi",
    "Papparapatti",
    "Papparapatti",
    "Pappireddipatti",
    "Paramakudi",
    "Paramathi",
    "Parangipettai",
    "Paraniputhur",
    "Paravai",
    "Pathamadai (Pattamadai)",
    "Pattanam",
    "Pattinam",
    "Pattinamkattan",
    "Pattiveeranpatti",
    "Pattukkottai",
    "Pavali",
    "Peddikuppam",
    "Peerkankaranai",
    "Pennadam",
    "Pennagaram",
    "Pennathur",
    "Peraiyur",
    "Peralam",
    "Perambakkam",
    "Perambalur",
    "Peranamallur",
    "Peravurani",
    "Periagaram",
    "Periakottai",
    "Periyakodiveri",
    "Periyakulam",
    "Periyakurichi",
    "Periyamanali",
    "Periyanaicken-palayam",
    "Periya Negamam",
    "Periyapatti",
    "Periyasemur",
    "Pernampattu",
    "Perumagalur",
    "Perumagoundampatti",
    "Perumanallur",
    "Perundi",
    "Perundurai",
    "Perungalathur",
    "Perungudi",
    "Perungulam",
    "Perur",
    "Perur Chettipalayam",
    "Peruvilai",
    "Pethampalayam",
    "Pethanaickenpalayam",
    "Pichandarkovil",
    "Pillanallur",
    "P. J. Cholapuram",
    "P. Mettupalayam",
    "P. N. Patti",
    "Polichalur",
    "Pollachi",
    "Polur",
    "Ponmanai",
    "Ponnamaravathi",
    "Ponnampatti",
    "Ponneri",
    "Poolambadi",
    "Poolampatti",
    "Poolankinar",
    "Pooluvapatti",
    "Poonamallee",
    "Poravacheri",
    "Porur",
    "Pothanur",
    "Pothatturpettai",
    "Pudiyamputhur",
    "Pudukkottai",
    "Pudukkottai",
    "Pudupalayam",
    "Pudupalayam Agraharam",
    "Pudupattinam",
    "Pudupattinam",
    "Pudur (S)",
    "Puduvayal",
    "Puliankudi (Puliyankudi)",
    "Puliyoorsalai",
    "Puliyur",
    "Pullampadi (Pullambadi)",
    "Punjaipugalur",
    "Punjaipuliampatti",
    "Punjai Thottakurichi",
    "Puthagaram",
    "Puthalam",
    "Putheri",
    "Puthukkadai",
    "Puthur Agraharam",
    "Puvalur (Poovalur)",
    "Puzhal",
    "Puzhithivakkam (Ullagaram)",
    "Rajapalayam",
    "Rajapalayam",
    "Ramalingapuram",
    "Ramanathapuram",
    "Ramapuram",
    "Rameswaram",
    "Ranipettai (Ranipet)",
    "Rasipuram",
    "Rayagiri",
    "Reethapuram",
    "Rosalpatti",
    "R. Pudupatti",
    "R. S. Mangalam",
    "Rudravathi",
    "Sakkarakottai",
    "Sakkimangalam",
    "Salamedu",
    "Salangapalayam",
    "Salem",
    "Samalapuram",
    "Samanatham",
    "Samathur",
    "Samayanallur",
    "Sambavar Vadagarai",
    "Samusigapuram",
    "Sankaramanallur",
    "Sankarankoil (Sankarankovil)",
    "Sankaraperi",
    "Sankarapuram",
    "Sankarapuram",
    "Sankari (Sankagiri)",
    "Sankarnagar",
    "Sanniyasigundu",
    "Saravanampatti",
    "Sarcarsamakulam",
    "Sathankulam",
    "Sathiyavijayanagaram",
    "Sathkar",
    "Sathuvachari (Sathuvacheri)",
    "Sathyamangalam",
    "Sattur",
    "Sayalgudi",
    "Sayapuram",
    "Seerapalli",
    "Seithur",
    "Selathampatti",
    "Sembakkam",
    "Sembedu",
    "Sembianallur",
    "Semmipalayam",
    "Senapiratti",
    "Sengamalanachiarpatti",
    "Senneerkuppam",
    "Senthamangalam",
    "Sentharapatti",
    "Senur",
    "Sethiathoppu",
    "Sevilimedu",
    "Sevugampatti",
    "Sevur",
    "Sevur",
    "Shenbakkam",
    "Shenkottai (Sengottai)",
    "Sholavandan",
    "Sholinganallur",
    "Sholingur (Sholinghur)",
    "Sholur",
    "Sikkarayapuram",
    "Silaiman",
    "Silapadi",
    "Singampuneri (Singampunari)",
    "Singaperumalkoil",
    "Sircar Periapalayam",
    "Sirkali (Sirkazhi)",
    "Sirugamani",
    "Sirukalathur",
    "Sirukaveripakkam",
    "Sirumugai",
    "Sithayankottai",
    "Sithurajapuram",
    "Sivaganga",
    "Sivagiri",
    "Sivagiri",
    "Sivagiripatti",
    "Sivagnanapuram",
    "Sivakasi",
    "Sivanthipuram",
    "Somayampalayam",
    "Soolakkarai",
    "Soorapattu",
    "South Kannanur",
    "South Kodikulam",
    "South Nallur",
    "Srikalikapuram",
    "Srimushnam",
    "Sriperumbudur",
    "Sriramapuram",
    "Srivaikuntam",
    "Srivilliputhur",
    "St. Thomas Mount-cum-Pallavaram",
    "Suchindrum (Suchindram)",
    "Suleeswaranpatti",
    "Sulur",
    "Sumaitheerthapuram",
    "Sundarapandiam",
    "Sundarapandiapuram",
    "Sundarapandianpattinam",
    "Surampatti",
    "Surandai",
    "Suriyampalayam",
    "Swamimalai",
    "Tajpura",
    "Tambaram",
    "Tenkasi",
    "Terkukallikulam",
    "Thadikarankonam",
    "Thadikombu",
    "Thalainayar",
    "Thalakudi",
    "Thamaraikulam",
    "Thammampatti",
    "Thanakkankulam",
    "Thanjavur",
    "Thanthoni",
    "Thappakuttai",
    "Tharamangalam",
    "Tharangambadi",
    "Thathaiyangarpet",
    "Thathankuttai",
    "Thazhakudy",
    "Thedavur",
    "Theerthagiriyampattu",
    "Thenambakkam",
    "Thengampudur",
    "Theni Allinagaram",
    "Thenkarai",
    "Thenkarai",
    "Thenthiruperai",
    "Therur (Theroor)",
    "Thevaram",
    "Thevur",
    "Thiagadurgam",
    "Thikkanamcode",
    "Thingalnagar",
    "Thirparappu (Thiruparappu)",
    "Thirukarungudi",
    "Thirukkattupalli",
    "Thirumalpur",
    "Thirumangalam (Tirumangalam)",
    "Thirumazhisai",
    "Thirumuruganpoondi",
    "Thirunagar",
    "Thirunageswaram",
    "Thiruneermalai",
    "Thirunindravur (Thiruninravur)",
    "Thiruparankundram",
    "Thiruporur",
    "Thiruppalai",
    "Thiruppanandal",
    "Thirupuvanam (Thirubuvanam)",
    "Thirupuvanam",
    "Thiruthangal",
    "Thiruthuraipoondi",
    "Thiruvaiyaru",
    "Thiruvalam",
    "Thiruvallur (Tiruvallur)",
    "Thiruvarur",
    "Thiruvattar",
    "Thiruvengadam",
    "Thiruvidaimarudur",
    "Thiruvithancode (Thiruvithamcode)",
    "Thisayanvilai",
    "Thondamuthur",
    "Thondi",
    "Thoothukkudi (Thoothukudi)",
    "Thorapadi",
    "Thorapadi",
    "Thottipalayam",
    "Thottiyam",
    "Thozhur",
    "Thuthipattu",
    "Thuvakudi",
    "Tindivanam",
    "Tiruchendur (Thiruchendur)",
    "Tiruchengode",
    "Tiruchirappalli",
    "Tirukalukundram",
    "Tirukkoyilur (Tirukoilur)",
    "Tirumalaigiri",
    "Tirunelveli",
    "Tirupathur (Tiruppattur)",
    "Tirupathur",
    "Tirupattur",
    "Tiruppur",
    "Tirusulam",
    "Tiruttani (Thiruttani)",
    "Tiruvannamalai",
    "Tiruvethipuram (Cheyyar)",
    "Tiruvottiyur",
    "Tittacheri",
    "Tittakudi",
    "Tittangulam",
    "T.Kallupatti",
    "TNPL Pugalur",
    "Udangudi",
    "Udayarpalayam",
    "Udhagamandalam (Ooty)",
    "Udumalaipettai",
    "Ullur",
    "Ulundurpettai",
    "Unjalur",
    "Unnamalaikadai",
    "Uppidamangalam",
    "Uppiliapuram",
    "Urapakkam",
    "Usilampatti",
    "Usuppur",
    "Uthamapalayam",
    "Uthangarai",
    "Uthayendram",
    "Uthiramerur",
    "Uthukkottai (Uthukottai)",
    "Uthukuli",
    "Vadakarai Keezhpadugai",
    "Vadakkanandal",
    "Vadakkuvalliyur",
    "Vadalur",
    "Vadamadurai",
    "Vadavalli",
    "Vaddakkankulam",
    "Vadi",
    "Vadipatti",
    "Vadugapatti",
    "Vadugapatti",
    "Vaitheeswarankoil",
    "Valangaiman",
    "Valasaravakkam",
    "Valathur",
    "Valavandankottai",
    "Valayambattu",
    "Vallam",
    "Vallam",
    "Valparai",
    "Valvaithankoshtam",
    "Vanagaram",
    "Vanapadi",
    "Vanavasi",
    "Vandalur",
    "Vandavasi",
    "Vandiyur",
    "Vanganur",
    "Vaniputhur",
    "Vaniyambadi",
    "Vanniyoor",
    "Varadarajanpettai",
    "Vasudevanallur",
    "Vathirairuppu",
    "Vavarai",
    "Vazhapadi",
    "Vedapatti",
    "Vedaranyam",
    "Vedasandur",
    "Veeraganur",
    "Veerakeralam",
    "Veerakkalpudur",
    "Veerapandi",
    "Veerapandi",
    "Veerapandi",
    "Veerapandianpattinam Town",
    "Veerappanchatiram (Veerappanchatram)",
    "Veeravanallur",
    "Velampalayam",
    "Velankanni",
    "Velayudampalayam",
    "Vellakinar",
    "Vellakkalpatty",
    "Vellakoil",
    "Vellalur (Vellalore)",
    "Vellaravalli",
    "Vellimalai",
    "Vellore",
    "Vellottamparappu",
    "Velur",
    "Vembadithalam",
    "Vengampudur",
    "Vengathur",
    "Vengavasal",
    "Vengikkal",
    "Venkarai",
    "Venkatachalapuram",
    "Venkatapuram",
    "Vennanthur",
    "Veppathur",
    "Verkilambi",
    "Vettaikaranpudur",
    "Vettavalam",
    "Vijayapuri",
    "Vikramasingapuram",
    "Vikravandi",
    "Vilacheri",
    "Vilangudi",
    "Vilankurichi",
    "Vilapakkam",
    "Vilar",
    "Vilathikulam",
    "Vilathurai",
    "Vilavancode",
    "Vilavur",
    "Villukuri",
    "Viluppuram",
    "Viraganur",
    "Viralimalai",
    "Virinchipuram",
    "Virudampattu",
    "Virudhachalam",
    "Virudhunagar",
    "Virupakshipuram",
    "Viswanatham",
    "V.Pudupatti",
    "V. Pudur",
    "Walajabad",
    "Walajapet",
    "Wellington",
    "Yercaud",
    "Zamin Uthukuli",
    "Zuzuvadi"
  ],
  "Madhya Pradesh": [
    "Agar",
    "Ahirkhedi",
    "Ajaigarh",
    "Akoda",
    "Akodia",
    "Alampur",
    "Alirajpur",
    "Alot",
    "Amanganj",
    "Amanganj",
    "Amarpatan",
    "Amarwara",
    "Ambada",
    "Ambah",
    "Amkhera",
    "Amla",
    "Amlai",
    "Anjad",
    "Antari",
    "Anuppur",
    "Aron",
    "Ashoknagar",
    "Ashta",
    "Athner",
    "Babai",
    "Badagaon",
    "Badagaon (Badagoan)",
    "Bada Malhera",
    "Badarwas",
    "Badawada",
    "Badi",
    "Badkuhi",
    "Badnagar",
    "Badnawar",
    "Badod",
    "Badoda",
    "Badoni",
    "Badra",
    "Bagh",
    "Bagli",
    "Baihar",
    "Baikunthpur",
    "Balaghat",
    "Baldeogarh",
    "Bamhani",
    "Bamor",
    "Bamora",
    "Banda",
    "Bangarda Bada",
    "Bangarda Chhota",
    "Bangawan",
    "Bank",
    "Bansatar Kheda",
    "Baraily",
    "Barela",
    "Barghat",
    "Bargi",
    "Barhi",
    "Barigarh",
    "Barman Kalan",
    "Barwaha",
    "Barwaha Kasba",
    "Barwani",
    "Basoda (Ganj Basoda)",
    "Begamganj",
    "Beohari",
    "Berasia",
    "Betma",
    "Betul",
    "Betul-Bazar",
    "Bhainsa",
    "Bhainsdehi",
    "Bhander",
    "Bhanpura",
    "Bharveli",
    "Bhaurasa",
    "Bhavra",
    "Bhicholi Hapsi",
    "Bhikangaon",
    "Bhilakhedi",
    "Bhind",
    "Bhitarwar",
    "Bhopal",
    "Biaora",
    "Bichhiya",
    "Bijawar",
    "Bijuri",
    "Bilaua",
    "Bilpura",
    "Bina - Etawa",
    "Bina Railway Colony",
    "Birsinghpur",
    "Boda",
    "Borgaon",
    "Budni",
    "Burhanpur",
    "Burhar",
    "Buxwaha",
    "Buzurg",
    "Chachaura-Binaganj",
    "Chakghat",
    "Chandameta - Butaria",
    "Chanderi",
    "Chandia",
    "Chandla",
    "Chaurai Khas",
    "Chhanera",
    "Chhapiheda",
    "Chhatarpur",
    "Chhindwara",
    "Chichli",
    "Chicholi",
    "Chitrakoot",
    "Churhat",
    "Daboh",
    "Dabra",
    "Dabra",
    "Dahi",
    "Damoh",
    "Damua",
    "Datia",
    "Dehrisaray",
    "Deodara",
    "Deohra",
    "Deori",
    "Deori",
    "Depalpur",
    "Devendranagar",
    "Dewas",
    "Dhamnod",
    "Dhamnod",
    "Dhana",
    "Dhanpuri (Nargada Hari Dafai)",
    "Dhar",
    "Dharampuri",
    "Dhodaramohar (Bhoura)",
    "Diken",
    "Dindori",
    "Dola",
    "Dongar Parasia",
    "Dumar Kachhar",
    "Dungariya Chhapara",
    "Gadarwara",
    "Gairatganj",
    "Gamiria Sagar",
    "Gandhi Sagar Hydel Col",
    "Garhakota",
    "Garhi-Malhara",
    "Garoth",
    "Garra",
    "GCF Jabalpur (Gun Carriage Factory Jabalpur)",
    "Ghansaur (Ghansor)",
    "Ghoda Dongri Ryt",
    "Ghuwara",
    "Gogapur (Mehidpur Road)",
    "Gohad",
    "Goraiya",
    "Gormi",
    "Gotegaon (Chhota Chhindwara)",
    "Govindgarh",
    "Gujarkheda",
    "Guna",
    "Gurh",
    "Gwalior",
    "Hanumana",
    "Harda",
    "Harpalpur",
    "Harrai",
    "Hatod",
    "Hatpiplya (Hatpipalya)",
    "Hatta",
    "Hatwas",
    "Hindoria",
    "Hirapur",
    "Hirdepur",
    "Hoshangabad",
    "Hukmakhedi",
    "Ichhawar",
    "Iklehra",
    "Indergarh",
    "Indore",
    "Isagarh",
    "Itarsi",
    "Jabalpur",
    "Jabalpur Cantonment",
    "Jabera",
    "Jaisinghnagar",
    "Jaithari",
    "Jaitpur",
    "Jaitwara",
    "Jamai",
    "Jaora",
    "Jatara",
    "Jaura Khurd",
    "Jawad",
    "Jawar",
    "Jeron Khalsa",
    "Jhabua",
    "Jhundpura",
    "Jiran",
    "Jirapur",
    "Jobat",
    "Joura",
    "Kailaras",
    "Kakarhati",
    "Kanad",
    "Kannod",
    "Kantaphod",
    "Kapuria",
    "Kareli",
    "Karera",
    "Kari",
    "Karnawad",
    "Karrapur",
    "Kasrawad",
    "Katangi",
    "Katangi",
    "Kelhauri (Chachai)",
    "Keolari",
    "Khacharod (Khachrod)",
    "Khairi",
    "Khajuraho",
    "Khand (Bansagar)",
    "Khandwa",
    "Khaniyadhana",
    "Khargapur",
    "Khargone",
    "Khategaon",
    "Khetia",
    "Khilchipur",
    "Khirkiya",
    "Khor",
    "Khujner",
    "Khurai",
    "Kirnapur",
    "Kolar",
    "Kolaras",
    "Kosmi",
    "Kotar",
    "Kothi",
    "Kotma",
    "Kukdeshwar",
    "Kukshi",
    "Kumbhraj",
    "Kundam",
    "Kurwai",
    "Kymore",
    "Lahar",
    "Lakhnadon",
    "Lanji",
    "Lasudiya Mori",
    "Laundi (Lavkushnagar)",
    "Lidhora Khas",
    "Limbodi",
    "Lodhikheda",
    "Loharda",
    "Lonia Karbal",
    "Machalpur",
    "Madai",
    "Madhawgdha",
    "Maharajpur",
    "Maharajpur",
    "Maheshwar",
    "Mahidpur",
    "Mahura",
    "Maihar",
    "Majhauli",
    "Majhgawan",
    "Majholi",
    "Makdon",
    "Makronia Buzurg",
    "Maksi",
    "Malajkhand",
    "Malanpur",
    "Malhargarh",
    "Maliya Guda",
    "Manasa",
    "Manawar",
    "Mandav",
    "Mandideep",
    "Mandla",
    "Mandleshwar",
    "Mandsaur",
    "Manegaon",
    "Mangawan",
    "Manglaya Sadak",
    "Manpur",
    "Mau",
    "Mauganj",
    "Meghnagar",
    "Meharagaon",
    "Mehgaon",
    "Mhow Cantonment",
    "Mhowgaon",
    "Mihona",
    "Mohgaon",
    "Morar Cantonment",
    "Morena",
    "Multai",
    "Mundi",
    "Mungaoli",
    "Murwara (Katni)",
    "Nagda",
    "Nagod",
    "Nagri",
    "Naigarhi",
    "Nainpur",
    "Nalkheda",
    "Namli",
    "Nanpur",
    "Narayangarh",
    "Narsimhapur (Narsinghpur)",
    "Narsinghgarh",
    "Narsinghgarh",
    "Narwar",
    "Nasrullaganj",
    "Naudhia",
    "Neemuch",
    "Nepanagar",
    "Neuton Chikhli Kalan",
    "Niwari",
    "Niwas",
    "Nowbasata",
    "Nowgong",
    "Nowrozabad (Khodargama)",
    "Obedullaganj",
    "Omkareshwar",
    "Orchha",
    "Ordnance Factory Itarsi",
    "Ordnance Factory Khamaria",
    "Pachmarhi Cantonment",
    "Pachore",
    "Pal Chaurai (Pal Chourai)",
    "Palda",
    "Palera",
    "Pali",
    "Palsud",
    "Panagar",
    "Panara",
    "Pandhana",
    "Pandhurna",
    "Pankhedi",
    "Panna",
    "Pansemal",
    "Pasan",
    "Patan",
    "Patharia",
    "Pawai",
    "Petlawad",
    "Phuphkalan",
    "Pichhore",
    "Pichhore",
    "Pindrai",
    "Pipalrawan",
    "Pipariya",
    "Pipariya",
    "Piplanarayanwar",
    "Piploda",
    "Piplya Kumar",
    "Piplya Mandi",
    "Pipri",
    "Pithampur",
    "Polaykalan",
    "Porsa",
    "Prithvipur",
    "Raghogarh-Vijaypur",
    "Rahatgarh",
    "Raisen",
    "Rajakhedi",
    "Rajgarh",
    "Rajgarh",
    "Rajnagar",
    "Rajpur",
    "Ramgarh",
    "Rampura",
    "Rampur Baghelan",
    "Rampur Naikin",
    "Ranapur",
    "Ranipur (Tavanagar)",
    "Ratangarh",
    "Ratlam",
    "Ratlam Railway Colony (Ratlam Kasba)",
    "Rau",
    "Rehli",
    "Rehti",
    "Rewa",
    "Rosera",
    "Runji-Gautampura",
    "Sabalgarh",
    "Sabo",
    "Sagar",
    "Sagar Cantonment",
    "Sailana",
    "Sanawad",
    "Sanchi",
    "Sangvi",
    "Santer",
    "Sarangpur",
    "Sardarpur",
    "Sarni",
    "Satai",
    "Satlapur",
    "Satna",
    "Satwas",
    "Sausar",
    "Sawer",
    "Sehore",
    "Semaria",
    "Sendhwa",
    "Seondha",
    "Seoni",
    "Seoni-Malwa",
    "Sethiya (Sethia)",
    "Shahdol",
    "Shahgarh",
    "Shahpur",
    "Shahpur",
    "Shahpura",
    "Shahpura",
    "Shajapur",
    "Shamgarh",
    "Shamshabad",
    "Sheopur",
    "Shivpuri",
    "Shujalpur",
    "Sidhi",
    "Sihora",
    "Silwani",
    "Singoli",
    "Singrauli",
    "Sinhasa",
    "Sirgora",
    "Sirmour (Sirmaur)",
    "Sironj",
    "Sitamau",
    "Sohagpur",
    "Sonkatch",
    "Soyatkalan",
    "Suhagi",
    "Sultanpur",
    "Susner",
    "Suthaliya",
    "Suwasara",
    "Swroop Nagar",
    "Tal",
    "Talen",
    "Tarana",
    "Tarichar Kalan",
    "Tekanpur",
    "Tendukheda",
    "Tendukheda",
    "Teonthar",
    "Thandla",
    "Tikamgarh",
    "Timarni",
    "Tirodi",
    "Tonk Khurd",
    "Udaipura",
    "Ujjain",
    "Ukwa",
    "Umaria",
    "Unchahara (Unchehara)",
    "Unhel",
    "Vehicle Factory Area Jabalpur",
    "Vidisha",
    "Vijaypur",
    "Vijayraghavgarh",
    "Waraseoni"
  ],
  Jharkhand: [
    "Dhanbad",
    "Ranchi",
    "Jamshedpur",
    "Bokaro Steel City",
    "Deoghar",
    "Phusro",
    "Adityapur",
    "Hazaribag",
    "Giridih",
    "Ramgarh",
    "Jhumri Tilaiya",
    "Saunda",
    "Sahibganj",
    "Medininagar (Daltonganj)",
    "Chaibasa",
    "Chatra",
    "Gumia",
    "Dumka",
    "Madhupur",
    "Chirkunda",
    "Pakaur",
    "Simdega",
    "Musabani",
    "Mihijam",
    "Patratu",
    "Lohardaga",
    "Tenu dam-cum-Kathhara",
  ],
  Mizoram: ["Aizawl", "Lunglei", "Saiha"],
  Nagaland: [
    "Dimapur",
    "Kohima",
    "Zunheboto",
    "Tuensang",
    "Wokha",
    "Mokokchung",
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Mandi",
    "Solan",
    "Nahan",
    "Sundarnagar",
    "Palampur",
    "Kullu",
  ],
  Tripura: [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Pratapgarh",
    "Kailasahar",
    "Belonia",
    "Khowai",
  ],
  "Andhra Pradesh": [
    "Adoni",
    "Akkarampalle",
    "Amadalavalasa (Amudalavalasa)",
    "Amalapuram",
    "Anakapalle",
    "Anantapur",
    "Anantapur",
    "Arempudi",
    "Avilala",
    "Badvel",
    "Balaga",
    "Banaganapalle (Banganapalle)",
    "Bandarulanka",
    "Banumukkala",
    "Bapatla",
    "Bethamcherla",
    "Bheemunipatnam",
    "Bhimavaram",
    "Bobbili",
    "Bowluvada",
    "Buja Buja Nellore",
    "Cheepurupalle (Cheepurupalli)",
    "Chennamukkapalle",
    "Cherlopalle",
    "Chidiga",
    "Chilakaluripet",
    "Chintalavalasa",
    "Chintapalle",
    "Chirala",
    "Chirala",
    "Chittoor",
    "Chodavaram",
    "Cumbum",
    "Dharmavaram",
    "Dhone (Dronachalam)",
    "Dommara Nandyala",
    "Dowleswaram",
    "Dwarakatirumala",
    "Eluru",
    "Gajapathinagaram",
    "Gavaravaram",
    "Giddaluru",
    "Gooty",
    "Gopavaram",
    "Gudivada",
    "Gudivada",
    "Gudur",
    "Guntakal",
    "Guntupalle",
    "Guntur",
    "Hindupur",
    "Hiramandalam",
    "Hukumpeta",
    "Ibrahimpatnam",
    "Ichchapuram",
    "Jaggaiahpet (Jaggayyapeta)",
    "Jammalamadugu",
    "Jarjapupeta",
    "Kadapa (Cuddapah)",
    "Kadiri",
    "Kakinada",
    "Kakkalapalle",
    "Kalyandurg",
    "Kanapaka",
    "Kandukur",
    "Kanigiri U",
    "Kankipadu",
    "Kantabamsuguda",
    "Kanuru",
    "Katheru",
    "Kavali",
    "Kondapalle (Kondapalli)",
    "Kothavalasa",
    "Kovvur",
    "Kuppam",
    "Kurnool (incl. Kallur)",
    "L.A.Sagaram",
    "Macherla",
    "Machilipatnam",
    "Madanapalle",
    "Malicherla",
    "Mamidalapadu",
    "Mandapeta",
    "Mangalagiri",
    "Mangalam",
    "Mangampeta",
    "Mangasamudram",
    "Markapur",
    "Modameedipalle",
    "Moragudi",
    "Morampudi",
    "Muddanur",
    "Mulaguntapadu",
    "Mulakuddu",
    "Murakambattu",
    "Nadim Tiruvuru",
    "Nagari",
    "Nagireddipalle",
    "Nakkapalle",
    "Nandyal",
    "Narasannapeta",
    "Narasapur",
    "Narasaraopet",
    "Narayanapuram",
    "Narayanavanam",
    "Narsipatnam",
    "Nellimarla",
    "Nellore",
    "Nidadavole (Nidadavolu)",
    "Nuzvid",
    "Ongole",
    "Palacole (Palakollu)",
    "Palakonda",
    "Palamaner",
    "Palasa Kasibugga",
    "Pamur",
    "Papampeta",
    "Parvathipuram",
    "Payakaraopeta",
    "Peda Boddepalle",
    "Pedana",
    "Peddapuram",
    "Perur",
    "Piduguralla",
    "Pileru",
    "Pithapuram",
    "Podili",
    "Ponduru",
    "Ponnur",
    "Poranki",
    "Prasadampadu",
    "Proddatur",
    "Pulivendla (Pulivendula)",
    "Punganur",
    "Puttur",
    "Rajahmundry",
    "Rajam",
    "Rajampet",
    "Ramachandrapuram",
    "Ramanayyapeta",
    "Ramapuram",
    "Ramavarappadu",
    "Rameswaram",
    "Rampachodavaram",
    "Rayachoti",
    "Rayadurg",
    "Renigunta",
    "Repalle",
    "Salur",
    "Samalkot",
    "Sanivarapupeta",
    "Satrampadu",
    "Sattenapalle",
    "Singarayakonda",
    "Somandepalle",
    "Sompeta",
    "Srikakulam",
    "Srikalahasti",
    "Sriramnagar",
    "Srisailam Project RFC Township (Right Flank Colony)",
    "Sulluru (Sullurpeta)",
    "Suryaraopeta",
    "Tada Khandrika",
    "Tadepalle",
    "Tadepalligudem",
    "Tadigadapa",
    "Tadpatri (Tadipatri)",
    "Tangellamudi",
    "Tanuku",
    "Tekkali",
    "Tenali",
    "Thummalamenta",
    "Tiruchanur",
    "Tirumala",
    "Tirupati",
    "Tirupati NMA",
    "Tummikapalle",
    "Tuni",
    "Upper Sileru Project Site Camp",
    "Uravakonda",
    "Vaddeswaram",
    "Venkatagiri",
    "Veparala",
    "Vetapalem",
    "Vijayawada",
    "Vinnamala",
    "Vinukonda",
    "Visakhapatnam [Vishakhapatnam]",
    "Vizianagaram",
    "Yelamanchili",
    "Yemmiganur",
    "Yenumalapalle",
    "Yerrabalem",
    "Yerraguntla"
  ],
  Punjab: [
    "Ludhiana",
    "Patiala",
    "Amritsar",
    "Jalandhar",
    "Bathinda",
    "Pathankot",
    "Hoshiarpur",
    "Batala",
    "Moga",
    "Malerkotla",
    "Khanna",
    "Mohali",
    "Barnala",
    "Firozpur",
    "Phagwara",
    "Kapurthala",
    "Zirakpur",
    "Kot Kapura",
    "Faridkot",
    "Muktsar",
    "Rajpura",
    "Sangrur",
    "Fazilka",
    "Gurdaspur",
    "Kharar",
    "Gobindgarh",
    "Mansa",
    "Malout",
    "Nabha",
    "Tarn Taran",
    "Jagraon",
    "Sunam",
    "Dhuri",
    "Firozpur Cantt.",
    "Sirhind Fatehgarh Sahib",
    "Rupnagar",
    "Jalandhar Cantt.",
    "Samana",
    "Nawanshahr",
    "Rampura Phul",
    "Nangal",
    "Nakodar",
    "Zira",
    "Patti",
    "Raikot",
    "Longowal",
    "Urmar Tanda",
    "Morinda, India",
    "Phillaur",
    "Pattran",
    "Qadian",
    "Sujanpur",
    "Mukerian",
    "Talwara",
  ],
  Chandigarh: ["Chandigarh"],
  Rajasthan: [
    "1 GB-A",
    "24 AS-C",
    "3 e Village",
    "3 STR",
    "8 PSD-B",
    "9 LLG (LALGARH)",
    "Abu Road",
    "Ahore",
    "Ajeetgarh",
    "Ajmer",
    "Akeda Doongar",
    "Aklera",
    "Aligarh",
    "Alwar",
    "Amet",
    "Antah",
    "Anupgarh",
    "Asind",
    "Atru",
    "Babai",
    "Badlya",
    "Baggar",
    "Bagru",
    "Bakani",
    "Bali",
    "Balotra",
    "Banasthali",
    "Bandikui",
    "Banswara",
    "Baral",
    "Baran",
    "Bargaon Rural",
    "Bari",
    "Bari Sadri",
    "Barmer",
    "Baskhoh",
    "Bassi",
    "Bay",
    "Bayana",
    "Bayana Rural",
    "Beawar",
    "Bedla",
    "Beejoliya Kalan (Bijolia)",
    "Begun",
    "Behror",
    "Beriyawali",
    "Bhadra",
    "Bhalariya",
    "Bharatpur",
    "Bhavri",
    "Bhawani Mandi",
    "Bhilwara",
    "Bhim",
    "Bhinder",
    "Bhinmal",
    "Bhiwadi",
    "Bhoogar",
    "Bhusawar",
    "Bhuwana",
    "Bichhri",
    "Bidasar",
    "Bikaner",
    "Bilara",
    "Bissau",
    "Boraj-Kazipura",
    "Borawar",
    "Budhpura",
    "Bundi",
    "Chaksu",
    "Chawand",
    "Chechat",
    "Chenar Village",
    "Chhabra",
    "Chhapar",
    "Chhoti Sadri",
    "Chirawa",
    "Chittaurgarh (Chittorgarh)",
    "Chomu",
    "Churu",
    "Danta",
    "Dausa",
    "Deeg",
    "Delwara",
    "Deogarh",
    "Deoli",
    "Deshnoke",
    "Desoola",
    "Dhariawad",
    "Dhaulpur (Dholpur)",
    "Dhorimanna (Dhorimana)",
    "Didwana",
    "Diwakari",
    "Dungargarh",
    "Dungarpur",
    "Emri",
    "Falna",
    "Fatehnagar",
    "Fatehpur",
    "Gajsinghpur",
    "Galiakot",
    "Ganganagar (Sri Ganganagar)",
    "Gangapur",
    "Garhi",
    "Gogunda",
    "Goredi Chancha",
    "Gothan",
    "Gothra",
    "Govindgarh",
    "Govindgarh",
    "Goyli",
    "Guhala",
    "Gulabpura",
    "Hameer Garh",
    "Hanumangarh",
    "Hindaun",
    "Indragarh",
    "Islampur",
    "Jahazpur",
    "Jaipur",
    "Jaisalmer",
    "Jaitaran",
    "Jalor",
    "Jamwa Ramgarh",
    "Jhagarwas",
    "Jhalawar",
    "Jhalrapatan",
    "Jhunjhunu",
    "Jobner",
    "Jodhpur",
    "Kaithoon",
    "Kaman",
    "Kanor",
    "Kanota",
    "Kanwat",
    "Kapasan",
    "Kaprain",
    "Karanpur",
    "Karauli",
    "Kasba Bonli",
    "Kawai",
    "Kekri",
    "Kelwa",
    "Keshoraipatan",
    "Kesrisinghpur",
    "Khairabad",
    "Khairthal",
    "Khandela",
    "Khanpur",
    "Kherli",
    "Kherliganj",
    "Kherwara Chhaoni",
    "Khetri",
    "Kishangarh",
    "Kishangarh",
    "Kishangarh Renwal",
    "Kolayat",
    "Kolvi (Mandi Rajendrapur)",
    "Kota",
    "Kotputli",
    "Kuchaman City",
    "Kuchera",
    "Kumbhkot",
    "Kumher",
    "Kuri Bhagtasani",
    "Kushalgarh",
    "Lachhmangarh (Laxmangarh)",
    "Ladnu",
    "Lakheri",
    "Lalsot",
    "Losal",
    "Mahu Kalan",
    "Mahwa",
    "Makrana",
    "Makrana Village",
    "Malpura",
    "Malsisar",
    "Mandalgarh",
    "Mandawa",
    "Mandawar",
    "Mangrol",
    "Manoharpur (Monoharpur)",
    "Manoharthana",
    "Marwar Junction",
    "Mavli",
    "Merta City",
    "Merta Road",
    "Modak",
    "Mount Abu",
    "Mukandgarh (Mukundgarh)",
    "Mundwa",
    "Nadbai",
    "Nagar",
    "Nagaur",
    "Nainwa",
    "Nandri",
    "Nasirabad",
    "Nathdwara",
    "Nawa",
    "Nawalgarh",
    "Neem-Ka-Thana",
    "Neemrana",
    "Newa Talai",
    "Nimbahera",
    "Niwai (Newai)",
    "Nohar",
    "Nooan",
    "Padampur",
    "Pali",
    "Parbatsar",
    "Partapur",
    "Phalodi",
    "Phulera",
    "Pilani",
    "Pilibanga",
    "Pindwara",
    "Pipar City",
    "Pirawa",
    "Pokaran (Pokhran)",
    "Pratapgarh",
    "Pushkar",
    "Raisinghnagar",
    "Rajakhera",
    "Rajaldesar",
    "Rajgarh",
    "Rajgarh",
    "Rajsamand",
    "Ramganj Mandi",
    "Ramgarh",
    "Ramgarh",
    "Ramgarh",
    "Rani",
    "Ratangarh",
    "Ratannagar",
    "Rawatbhata",
    "Rawatsar",
    "Reengus",
    "Reodar",
    "Rishabhdeo",
    "Sadri",
    "Sadulshahar",
    "Sagwara",
    "Salumbar",
    "Sambhar",
    "Sanchore",
    "Sangaria",
    "Sangariya",
    "Sangod",
    "Santpur Rural",
    "Sapotra",
    "Sardargarh",
    "Sardarshahar",
    "Sarmathura",
    "Sarwar",
    "Satalkheri",
    "Sawa",
    "Sawai Madhopur",
    "Seemalwara (Simalwara)",
    "Semari",
    "Shahjahanpur",
    "Shahpura",
    "Shahpura",
    "Sheoganj",
    "Sikar",
    "Singhana",
    "Sirohi",
    "Sojat",
    "Sojat Road",
    "Sri Madhopur",
    "Sujangarh",
    "Suket",
    "Sumerganj Mandi",
    "Sumerpur",
    "Surajgarh",
    "Suratgarh",
    "Takhatgarh",
    "Talera",
    "Tapookra",
    "Taranagar",
    "Tijara",
    "Todabhim",
    "Todaraisingh",
    "Tonk",
    "Udaipur",
    "Udaipurwati",
    "Udpura",
    "Uniara",
    "Utarlai",
    "Vidyavihar",
    "Vijainagar",
    "Vijainagar",
    "Viratnagar",
    "Weir"
  ],
  Assam: [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Nagaon",
    "Tinsukia",
    "Jorhat",
    "Bongaigaon City",
    "Dhubri",
    "Diphu",
    "North Lakhimpur",
    "Tezpur",
    "Karimganj",
    "Sibsagar",
    "Goalpara",
    "Barpeta",
    "Lanka",
    "Lumding",
    "Mankachar",
    "Nalbari",
    "Rangia",
    "Margherita",
    "Mangaldoi",
    "Silapathar",
    "Mariani",
    "Marigaon",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Raurkela",
    "Brahmapur",
    "Sambalpur",
    "Puri",
    "Baleshwar Town",
    "Baripada Town",
    "Bhadrak",
    "Balangir",
    "Jharsuguda",
    "Bargarh",
    "Paradip",
    "Bhawanipatna",
    "Dhenkanal",
    "Barbil",
    "Kendujhar",
    "Sunabeda",
    "Rayagada",
    "Jatani",
    "Byasanagar",
    "Kendrapara",
    "Rajagangapur",
    "Parlakhemundi",
    "Talcher",
    "Sundargarh",
    "Phulabani",
    "Pattamundai",
    "Titlagarh",
    "Nabarangapur",
    "Soro",
    "Malkangiri",
    "Rairangpur",
    "Tarbha",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bhilai Nagar",
    "Korba",
    "Bilaspur",
    "Durg",
    "Rajnandgaon",
    "Jagdalpur",
    "Raigarh",
    "Ambikapur",
    "Mahasamund",
    "Dhamtari",
    "Chirmiri",
    "Bhatapara",
    "Dalli-Rajhara",
    "Naila Janjgir",
    "Tilda Newra",
    "Mungeli",
    "Manendragarh",
    "Sakti",
  ],
  "Jammu and Kashmir": [
    "Srinagar",
    "Jammu",
    "Baramula",
    "Anantnag",
    "Sopore",
    "KathUrban Agglomeration",
    "Rajauri",
    "Punch",
    "Udhampur",
  ],
  Manipur: ["Imphal", "Thoubal", "Lilong", "Mayang Imphal"],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Kollam",
    "Thrissur",
    "Palakkad",
    "Alappuzha",
    "Malappuram",
    "Ponnani",
    "Vatakara",
    "Kanhangad",
    "Taliparamba",
    "Koyilandy",
    "Neyyattinkara",
    "Kayamkulam",
    "Nedumangad",
    "Kannur",
    "Tirur",
    "Kottayam",
    "Kasaragod",
    "Kunnamkulam",
    "Ottappalam",
    "Thiruvalla",
    "Thodupuzha",
    "Chalakudy",
    "Changanassery",
    "Punalur",
    "Nilambur",
    "Cherthala",
    "Perinthalmanna",
    "Mattannur",
    "Shoranur",
    "Varkala",
    "Paravoor",
    "Pathanamthitta",
    "Peringathur",
    "Attingal",
    "Kodungallur",
    "Pappinisseri",
    "Chittur-Thathamangalam",
    "Muvattupuzha",
    "Adoor",
    "Mavelikkara",
    "Mavoor",
    "Perumbavoor",
    "Vaikom",
    "Palai",
    "Panniyannur",
    "Guruvayoor",
    "Puthuppally",
    "Panamattom",
  ],
  Delhi: ["Delhi", "New Delhi"],
  "Dadra and Nagar Haveli": ["Silvassa"],
  Puducherry: ["Pondicherry", "Karaikal", "Yanam", "Mahe"],
  Uttarakhand: [
    "Dehradun",
    "Hardwar",
    "Haldwani-cum-Kathgodam",
    "Srinagar",
    "Kashipur",
    "Roorkee",
    "Rudrapur",
    "Rishikesh",
    "Ramnagar",
    "Pithoragarh",
    "Manglaur",
    "Nainital",
    "Mussoorie",
    "Tehri",
    "Pauri",
    "Nagla",
    "Sitarganj",
    "Bageshwar",
  ],
  "Uttar Pradesh": [
    "Abupur",
    "Achalganj",
    "Achhalda",
    "Adari",
    "Afzalgarh",
    "Agarwal Mandi",
    "Agra",
    "Agra Cantonment",
    "Ahrauli Shekh",
    "Ahraura",
    "Ailam",
    "Air Force Area",
    "Ajhuwa",
    "Ajitpur",
    "Akbarpur",
    "Akbarpur",
    "Alhaipur",
    "Aliganj",
    "Aligarh",
    "Allahabad",
    "Allahabad Cantonment",
    "Allahganj",
    "Allapur",
    "Almaspur",
    "Amanpur",
    "Amara Khaira Chak",
    "Ambehta",
    "Amethi",
    "Amethi",
    "Amethi Jadid",
    "Amila",
    "Aminagar Sarai",
    "Aminagar urf Bhurbaral",
    "Amraudha",
    "Amroha",
    "Anandnagar",
    "Anpara",
    "Antu",
    "Anupshahr",
    "Anurudhpur Purab Patti",
    "Aonla",
    "Arail Uparhar",
    "Armapur Estate",
    "Artauni",
    "Asapur",
    "Ashrafpur Jalal",
    "Ashrafpur Kichhauchha",
    "Atrari",
    "Atrauli",
    "Atrauliya (Atraulia)",
    "Auraiya",
    "Aurangabad",
    "Aurangabad Bangar",
    "Aurangabad Gadana",
    "Auras",
    "Awagarh",
    "Ayodhya",
    "Azamgarh",
    "Azizpur",
    "Azmatgarh",
    "Babarpur Ajitmal",
    "Baberu",
    "Babina",
    "Babrala",
    "Babugarh",
    "Bachhraon",
    "Bachhrawan",
    "Bad",
    "Bagh Nagar Urf Bakhira",
    "Baghpat",
    "Bah",
    "Bahadurganj",
    "Bahadurpur",
    "Bahalimpura",
    "Baheri",
    "Bahjoi",
    "Bahraich",
    "Bahsuma",
    "Bahuwa",
    "Bajna",
    "Bakalpur Mathura",
    "Bakewar",
    "Bakshi Ka Talab",
    "Baldeo",
    "Ballia",
    "Balrampur",
    "Banat",
    "Banda",
    "Bangarmau",
    "Banguwan Kalan",
    "Banjarepur",
    "Banki",
    "Bansdih",
    "Bansgaon",
    "Bansi",
    "Banthla",
    "Baragaon",
    "Baragaon",
    "Barahatir Jagdishpur",
    "Baraut",
    "Bareilly",
    "Bareilly Cantonment",
    "Barel",
    "Bargo",
    "Barha",
    "Barhalganj",
    "Barhani Bazar",
    "Barkhera",
    "Baroun",
    "Barsana",
    "Barua Sagar",
    "Barwar",
    "Barwara Mazra",
    "Basantpur Saitli",
    "Basta",
    "Basti",
    "Baswar",
    "Beelna",
    "Begumabad Budhana",
    "Behat",
    "Bela Pratapgarh",
    "Belthara Road",
    "Beniganj",
    "Benipur",
    "Beswan",
    "Bewar",
    "Bhabnan Bazar",
    "Bhadarsa",
    "Bhadohi",
    "Bhagawanpur",
    "Bhagipur",
    "Bhagwant Nagar",
    "Bharatganj",
    "Bhargain",
    "Bharthana",
    "Bharuhana",
    "Bhatni Bazar",
    "Bhatpar Rani",
    "Bhawan Bahadur Nagar",
    "Bhinga",
    "Bhogaon",
    "Bhokarhedi",
    "Bhulepur",
    "Bidhuna",
    "Bighapur",
    "Bihka Urf Pura Mufti",
    "Bijnor",
    "Bijpur",
    "Bikapur",
    "Bilari",
    "Bilariaganj",
    "Bilaspur",
    "Bilaspur",
    "Bilgram",
    "Bilhaur",
    "Bilram",
    "Bilsanda",
    "Bilsi",
    "Bindki",
    "Birbhanpur",
    "Birjapur",
    "Bisalpur",
    "Bisanda Buzurg",
    "Bisauli",
    "Bisharatganj",
    "Bishunipur",
    "Bisokhar",
    "Biswan",
    "Bithoor",
    "Budaun",
    "Budhana",
    "Bugrasi",
    "Bulandshahr",
    "Buxer",
    "Chail",
    "Chak Babura Alimabad",
    "Chakeri",
    "Chakia",
    "Chakmano Urf Dargah",
    "Chak Sikari",
    "Chandauli",
    "Chandausi",
    "Chandpur",
    "Chandpur",
    "Charkhari",
    "Charthawal (Charthaval)",
    "Chaumuhan",
    "Chaurhat",
    "Chhapraula",
    "Chhaprauli",
    "Chharra Rafatpur",
    "Chhatari",
    "Chhibramau",
    "Chhitauni",
    "Chhitpur",
    "Chhutmalpur",
    "Chilkana Sultanpur",
    "Chirgaon",
    "Chitbara Gaon",
    "Chitrakoot Dham (Karwi)",
    "Chopan",
    "Choubepur Kalan",
    "Chunar",
    "Churk Ghurma",
    "Colonelganj",
    "Dadri",
    "Dahilamau",
    "Dalmau",
    "Dankaur",
    "Dariyabad",
    "Dasna",
    "Dataganj",
    "Daurala",
    "Dayalbagh",
    "Dehtora",
    "Deoband",
    "Deoranian",
    "Deoretha",
    "Deoria",
    "Deori Singhpura",
    "Deosaini",
    "Derapur",
    "Devinagar",
    "Dewa",
    "Dhakauli",
    "Dhampur",
    "Dhampur Husainpur",
    "Dhanauha",
    "Dhanauli",
    "Dhanipur",
    "Dhaura Tanda",
    "Dhaurehra",
    "Dhaurra Mafi",
    "Dibai",
    "Dibiyapur",
    "Dildarnagar Fatehpur Bazar",
    "Dindaspur",
    "Doghat",
    "Dohrighat",
    "Domariyaganj (Domariaganj)",
    "Dostpur",
    "Dudhi",
    "Dulhipur",
    "Ekdil",
    "Erich",
    "Etah",
    "Etawah",
    "Etmadpur",
    "Faizabad",
    "Faizabad Cantonment",
    "Faizganj",
    "Farah",
    "Faridnagar",
    "Faridpur",
    "Faridpur",
    "Fariha",
    "Farrukhabad-cum-Fatehgarh",
    "Fatehabad",
    "Fatehganj Pashchimi",
    "Fatehganj Purvi",
    "Fatehgarh",
    "Fatehpur",
    "Fatehpur",
    "Fatehpur Chaurasi",
    "Fatehpur Sikri",
    "Fazi Nagar",
    "Firozabad",
    "Gabhana",
    "Gaddoo Pur",
    "Gadhi",
    "Gagalhedi Must.",
    "Gajraula",
    "Gangaghat",
    "Gangapur",
    "Gangiri",
    "Gangoh",
    "Ganj Dundawara",
    "Ganj Muradabad",
    "Garauri",
    "Garautha",
    "Garhi Pukhta",
    "Garhi Tamana",
    "Garhmukhteshwar (Garhmukteshwar)",
    "Gaura",
    "Gaura Barhaj",
    "Gaura Kala",
    "Gauri Bazar",
    "Gausganj",
    "Gawan",
    "Ghatampur",
    "Ghaziabad",
    "Ghazipur",
    "Ghiraur",
    "Ghorawal",
    "Ghosi",
    "Ghosia Bazar",
    "Ghughuli (Ghughali)",
    "Gird Baragaon",
    "Gird Gonda",
    "Gohand",
    "Gokul",
    "Gola Bazar",
    "Gola Gokaran Nath",
    "Gonda",
    "Gopamau",
    "Gopiganj",
    "Gorakhpur",
    "Gosainganj",
    "Gosainganj (Goshainganj)",
    "Got",
    "Govardhan",
    "Greater Noida",
    "Gulaothi",
    "Gulariya",
    "Gulariya Bhindara",
    "Gunnaur",
    "Gursahaiganj",
    "Gursarai",
    "Gyanpur",
    "Hafiz Ganj",
    "Hafizpur",
    "Haidergarh",
    "Haldaur",
    "Hallaur",
    "Hamirpur",
    "Handia",
    "Hapur",
    "Haqiqatpur Urf Khudawas",
    "Hardoi",
    "Harduaganj",
    "Hargaon",
    "Hariharpur",
    "Harpalpur",
    "Harraiya",
    "Harsewakpur No.2",
    "Hasangarh",
    "Hasanpur",
    "Hasayan",
    "Hastinapur",
    "Hata",
    "Hathgram",
    "Hathras",
    "Hathras Dehat",
    "Hindalco Industries Ltd., Renukoot",
    "Hyderabad",
    "Ibrahimpur",
    "Iffco Census Village",
    "Iglas",
    "Ikauna",
    "Iltifatganj Bazar",
    "Indian Telephone Industry, Mankapur (Sp. Village)",
    "Islamnagar",
    "Itaunja",
    "Itwa",
    "Jafarabad",
    "Jagner",
    "Jahangirabad",
    "Jahangirpur",
    "Jais",
    "Jaithara",
    "Jakhaon",
    "Jalalabad",
    "Jalalabad",
    "Jalali",
    "Jalal Patti",
    "Jalalpur",
    "Jalalpur Dehat",
    "Jalaun",
    "Jalesar",
    "Jamshila",
    "Jamuhan",
    "Jangipur",
    "Jangl Hakeem No 2",
    "Janki Nagar",
    "Jansath",
    "Jarwal",
    "Jasra",
    "Jasrana",
    "Jaswantnagar",
    "Jatari (Jattari)",
    "Jaunpur",
    "Jewar",
    "Jhalu",
    "Jhansi",
    "Jhansi Cantonment",
    "Jhansi Railway Settlement",
    "Jhinjhak",
    "Jhinjhana",
    "Jhusi",
    "Jhusi Kohna",
    "Jiyanpur",
    "Joya",
    "Jugauli",
    "Jyoti Khuriya (Jyoti Khuria)",
    "Kabrai",
    "Kachhauna Patseni",
    "Kachhla",
    "Kachhwa",
    "Kachnar",
    "Kadaura",
    "Kadipur",
    "Kailashpur",
    "Kaimganj",
    "Kairana",
    "Kakari",
    "Kakarmatta",
    "Kakgaina",
    "Kakod",
    "Kakori",
    "Kakrala",
    "Kalinagar",
    "Kalli Pashchim",
    "Kallipur",
    "Kallu",
    "Kalpi",
    "Kalwari",
    "Kamalganj",
    "Kampil",
    "Kanaudia Chemical & Industries Ltd., Renukoot",
    "Kandharpur",
    "Kandhla",
    "Kandhla Rural",
    "Khekada",
    "Kheragarh",
    "Kheri",
    "Kherli Hafizpur",
    "Khetasarai",
    "Khojn Pur",
    "Khora",
    "Khudaganj",
    "Khurja",
    "Khurja Rural",
    "Khutar",
    "Kiraoali (Kiraoli)",
    "Kiratpur",
    "Kishni",
    "Kishunpur",
    "Kithaur",
    "Koeripur",
    "Konch",
    "Kopaganj",
    "Kora Jahanabad",
    "Koraon",
    "Korwa",
    "Kosi Kalan",
    "Kota",
    "Kotra",
    "Kotwa",
    "Kotwa (Kotwa II)",
    "Kotwali",
    "Kukra",
    "Kul Pahar",
    "Kunda",
    "Kundarki",
    "Kunwargaon",
    "Kuraoali (Kuraoli)",
    "Kurara",
    "Kursath",
    "Kursath",
    "Kurthi Jafarpur",
    "Kushinagar",
    "Kusmara",
    "Kwarasi",
    "Lachhiman Patti",
    "Laharpur",
    "Lahartara",
    "Lahsari",
    "Lakhimpur",
    "Lakhna",
    "Lalganj",
    "Lal Gopalganj Nindaura",
    "Lalhapur",
    "Lalitpur",
    "Lar",
    "Lawar",
    "Ledwa Mahua",
    "Lerhupur",
    "Lohta",
    "Loni",
    "Lucknow",
    "Lucknow Cantonment",
    "Machhlishahr (Machhali Shahar)",
    "Madhoganj",
    "Madhogarh",
    "Madiya",
    "Maghar",
    "Mahmudabad",
    "Mahmudpur Taluka Madpur Sult",
    "Mahoba",
    "Maholi",
    "Mahona",
    "Mahrajganj",
    "Mahrajganj",
    "Maheshpur",
    "Mahewa Patti Pashchim Uparhar",
    "Mahimapur",
    "Majhara Pipar Ahatmali",
    "Majhauliraj",
    "Makhanpur",
    "Malhipur",
    "Malihabad",
    "Mallawan",
    "Mandawar",
    "Manikpur",
    "Manikpur Sarhat",
    "Manjoor Garhi",
    "Mankapur",
    "Marehra",
    "Mariahu",
    "Maruadih",
    "Maruadih Railway Settlement",
    "Maswasi",
    "Mataundh",
    "Maudaha",
    "Maunath Bhanjan (Mau)",
    "Mauranipur",
    "Maurawan",
    "Mawana",
    "Meerut",
    "Meerut Cantonment",
    "Mehdawal",
    "Mehnagar",
    "Mendu",
    "Middha",
    "Milak",
    "Miranpur",
    "Mirganj",
    "Mirzapur-cum-Vindhyachal",
    "Misrikh-cum-Neemsar (Misrikh Neemsar)",
    "Modinagar",
    "Mogra Badshahpur (Mungra Badshahpur)",
    "Mohammadabad",
    "Mohammadabad",
    "Mohammadi",
    "Mohan",
    "Mohanpur",
    "Mohenpur",
    "Mohiuddinpur",
    "Moradabad",
    "Moth",
    "Mubarakpur",
    "Mughalsarai",
    "Mughalsarai Railway Settlement",
    "Muhammadabad",
    "Mukrampur Khema",
    "Mundera Bazar",
    "Mundiya",
    "Muradgram Pur Pursi",
    "Muradnagar",
    "Mursan",
    "Musafirkhana",
    "Muzaffarnagar",
    "Nadigaon",
    "Nagina",
    "Nagram",
    "Nai Bazar",
    "Nainana-Brahman",
    "Nainana Jat",
    "Naiparapur",
    "Najibabad",
    "Nakur",
    "Nanauta",
    "Nandgaon",
    "Nandivaram-Guduvancheri",
    "Nangal",
    "Naraini",
    "Narauli",
    "Naraura (Narora)",
    "Naugawan Sadat",
    "Nautanwa",
    "Nawabganj",
    "Nawabganj",
    "Nawabganj",
    "Nawabganj",
    "Nehtaur",
    "Nichlaul",
    "Nidhauli Kalan",
    "Nihal Garh Chak Jangla",
    "Nivi",
    "Niwari",
    "Nizamabad",
    "Noorpur",
    "Northern Railway Colony",
    "Nyoria Husainpur",
    "Nyotini",
    "Obaree",
    "Obra",
    "Oel Dhakwa",
    "Orai",
    "Oran",
    "Ordinance Factory Muradnagar",
    "Pachperwa",
    "Padarathpur",
    "Padrauna",
    "Pahar Ganj",
    "Pahasu",
    "Paintepur",
    "Pakbara",
    "Pakriya Naugwan Mustqil",
    "Palhni",
    "Pali",
    "Pali",
    "Pali Khera",
    "Palpur",
    "Palwal",
    "Para",
    "Parasi",
    "Parichha",
    "Parikshitgarh",
    "Parmanandpur",
    "Parsadepur",
    "Parsona",
    "Patadi",
    "Patala",
    "Patholi",
    "Patti",
    "Pavi Sadakpur",
    "Phalauda",
    "Phaphund",
    "Phulpur",
    "Phulpur",
    "Phulwaria",
    "Pihani",
    "Pilibhit",
    "Pilkana",
    "Pilkhuwa",
    "Pinahat",
    "Pipalsana Chaudhari",
    "Pipiganj",
    "Pipraich",
    "Piprayli Bujurg",
    "Pipri",
    "Powayan (Pawayan)",
    "Pratapgarh City",
    "Premchak Urf Baheri",
    "Pukhrayan",
    "Puranpur",
    "Pura Pandey",
    "Purdilnagar",
    "Purquazi",
    "Purwa",
    "Qasimpur Power House Colony",
    "Rabupura",
    "Radhakund",
    "Ramdaspur Urf Nagal",
    "Ramgarh Panjoopur",
    "Ramkola",
    "Ramnagar",
    "Rampur",
    "Rampur",
    "Rampur Karkhana",
    "Rampur Maniharan",
    "Ranchi Bangar",
    "Ranipur",
    "Raniyan",
    "Rashidpur Garhi",
    "Rasra",
    "Rath",
    "Rau",
    "Raya",
    "Renukoot",
    "Reoti",
    "Richha",
    "Risiya Bazar (Risia Bazar)",
    "Rithora",
    "Rohta",
    "Rori",
    "Rudauli",
    "Rudayan",
    "Rudrapur",
    "Runkata",
    "Rustamnagar Sahaspur",
    "Sadabad",
    "Sadat",
    "Sadatmasaura",
    "Sadruddin Nagar",
    "Sahanpur",
    "Saharanpur",
    "Sahaspur",
    "Sahaswan",
    "Sahatwar",
    "Sahjanwan",
    "Sahpau",
    "Saidhari",
    "Saidpur",
    "Saidpur",
    "Saidpur Khajuria",
    "Saijni Nankar",
    "Sainthal",
    "Saiyad Raza (Saiyad Raja)",
    "Sakaldiha",
    "Sakhanu",
    "Sakit",
    "Salarpur",
    "Salarpur Khadar",
    "Salempur",
    "Salon",
    "Sambhal",
    "Samdhan",
    "Samthar",
    "Sandi",
    "Sandila",
    "Sani",
    "Sarai Abdulmalik",
    "Sarai Aquil",
    "Sarai Lahur Urf Lahurpur",
    "Sarai Mir",
    "Sarai Mohana",
    "Sardhana",
    "Sarila",
    "Sarsaul",
    "Sarsawa",
    "Sarsawan",
    "Sarwat",
    "Sasni",
    "Satiyava",
    "Satpokhari",
    "Satrikh",
    "Saunkh",
    "Saurikh",
    "Savarur",
    "Seohara",
    "Sewalkhas",
    "Sewarhi",
    "Shahabad",
    "Shahabad",
    "Shaha Urf Pipalgaon",
    "Shahbudinpur",
    "Shahganj",
    "Shahi",
    "Shahjahanpur",
    "Shahjahanpur Cantonment",
    "Shahpur",
    "Shamsabad",
    "Shamsabad",
    "Shankargarh",
    "Shekhpura",
    "Shergarh",
    "Sherkot",
    "Shikarpur",
    "Shikohabad",
    "Shishgarh",
    "Shivdaspur",
    "Shivli",
    "Shivrajpur",
    "Shohratgarh",
    "Siddharthnagar (Tetri Bazar, Naugarh)",
    "Siddhaur",
    "Sidhauli",
    "Sidhpura",
    "Sikanderpur",
    "Sikanderpur",
    "Sikandra",
    "Sikandrabad",
    "Sikri Kalan",
    "Sindhawali",
    "Singahi Bhiraura",
    "Sirathu",
    "Sirauli",
    "Sir Gobardhan",
    "Sirsa",
    "Sirsaganj",
    "Sirsi",
    "Sisauli",
    "Siswa Bazar",
    "Sitapur",
    "Sonbhadra (Robertsganj)",
    "Soraon",
    "Soron",
    "Suar",
    "Subeha",
    "Sujavalpur",
    "Sultanpur",
    "Sumerpur",
    "Suriyawan",
    "Susuwahi",
    "Suzabad",
    "Swamibagh",
    "Talbehat",
    "Talgram",
    "Tambaur-cum-Ahamdabad",
    "Tanda",
    "Tanda",
    "Tatarpur Lallu",
    "Thakurdwara",
    "Thana Bhawan",
    "Thiriya Nizamat Khan",
    "Tikait Nagar",
    "Tikri",
    "Tilhar",
    "Tilthi",
    "Tindwari",
    "Tirwaganj",
    "Titron",
    "Tondi Fatehpur",
    "Tulsipur",
    "Tundla",
    "Tundla Kham",
    "Tundla Railway Colony",
    "Ugu",
    "Ujhani",
    "Ujhari",
    "Umarha",
    "Umri",
    "Umri Kalan",
    "Un",
    "Unchahar",
    "Unnao",
    "Usawan",
    "Usehat",
    "Uska Bazar",
    "Utraula",
    "Varanasi [Benares]",
    "Varanasi Cantonment",
    "Vijaigarh",
    "Villimar Kundi",
    "Vrindavan",
    "Walidpur",
    "Warhapur",
    "Wazirganj",
    "Zaidpur",
    "Zamania"
  ],
  Bihar: [
    "Amarpur",
    "Anwari",
    "Araria",
    "Areraj",
    "Arrah",
    "Arwal",
    "Asarganj",
    "Aurangabad",
    "Bagaha",
    "Bahadurganj",
    "Bahadurpur",
    "Bairgania",
    "Bakhri",
    "Bakhtiarpur",
    "Balia",
    "Banka",
    "Banmankhi Bazar",
    "Bara",
    "Barahiya",
    "Barauli",
    "Barauni",
    "Barbigha",
    "Barh",
    "Begusarai",
    "Behea",
    "Belsand",
    "Benipur",
    "Bettiah",
    "Bhabua",
    "Bhadauni",
    "Bhagalpur",
    "Bhagirathpur",
    "Bhardua",
    "Bhuindhara",
    "Bihar Sharif",
    "Bihat",
    "Bihta",
    "Bikram",
    "Bikramganj",
    "Birpur",
    "Bodh Gaya",
    "Buxar",
    "Chakia",
    "Chanari",
    "Chanpatia",
    "Chapra (Chhapra)",
    "Colgong (Kahalgaon)",
    "Colgong",
    "Dalsinghsarai",
    "Damodarpur",
    "Darbhanga",
    "Dariapur",
    "Daudnagar",
    "Dehri",
    "Dhaka",
    "Dharampur",
    "Dighwara",
    "Dinapur Cantonment",
    "Dinapur Nizamat",
    "Dumari urf Damodarpur Shahjahan",
    "Dumra",
    "Dumraon",
    "Ekangar Sarai",
    "Fatwah (Fatuha)",
    "Forbesganj",
    "Gaya",
    "Gazipur",
    "Ghoghardiha",
    "Gogri Jamalpur",
    "Gopalganj",
    "Habibpur",
    "Hajipur",
    "Hanspura",
    "Hathua",
    "Hat Saraiya",
    "Hilsa",
    "Hisua",
    "Islampur",
    "Jagdishpur (Jagdispur)",
    "Jainagar",
    "Jamalpur",
    "Jamui",
    "Janakpur Road",
    "Janpur",
    "Jehanabad",
    "Jhajha",
    "Jhanjharpur",
    "Jogabani (Jogbani)",
    "Kanti",
    "Kargahia Purab",
    "Kasba",
    "Kataiya",
    "Katihar",
    "Kesaria",
    "Khagaria",
    "Khagaul",
    "Kharagpur",
    "Khusrupur",
    "Kishanganj",
    "Koath",
    "Koilwar",
    "Kurthaur",
    "Lakhisarai",
    "Lalganj",
    "Laruara",
    "Madhepura",
    "Madhuban",
    "Madhubani",
    "Madhubani",
    "Maharajganj",
    "Mahnar Bazar",
    "Mairwa",
    "Majhauli Khetal",
    "Makhdumpur",
    "Malhipur",
    "Maner",
    "Manihari",
    "Mansur Chak",
    "Marhaura",
    "Masaurhi",
    "Mathurapur",
    "Mehsi",
    "Mirganj",
    "Mohanpur",
    "Mokameh (Mokama)",
    "Motihari",
    "Motipur",
    "Munger",
    "Murliganj",
    "Muzaffarpur",
    "Nabinagar",
    "Narkatiaganj",
    "Nasriganj",
    "Naubatpur",
    "Naugachhia (Naugachia)",
    "Nawada",
    "Nirmali",
    "Nohsa",
    "Nokha",
    "Nurpur",
    "Nurpur",
    "Obra",
    "Padri",
    "Paharpur",
    "Pakri Dayal",
    "Pareo",
    "Paria",
    "Pataliputra Housing Colony",
    "Patna",
    "Phulwari Sharif",
    "Piro",
    "Puraini",
    "Purnia",
    "Rafiganj",
    "Raghunathpur",
    "Rajauli",
    "Rajgir",
    "Rajopatti urf Kota Bazar",
    "Ramgarh",
    "Ramnagar",
    "Raxaul Bazar",
    "Revelganj",
    "Rosera",
    "Sabour",
    "Saharsa",
    "Sahebganj",
    "Saidpura",
    "Samastipur",
    "Sanrha",
    "Saraiya",
    "Sarimpur",
    "Sasaram",
    "Satghara",
    "Shahjangi",
    "Shahpur",
    "Sheikhpura",
    "Shekhpura",
    "Sheohar",
    "Sherghati",
    "Silao",
    "Singhesar Asthan",
    "Sitamarhi",
    "Siwan",
    "Sonepur (Sonpur)",
    "Sugauli",
    "Sultanganj",
    "Supaul",
    "Talkhapur Dumra",
    "Tarapur",
    "Teghra",
    "Telkap",
    "Thakurganj",
    "Tikari",
    "Tola Baliadih",
    "Tola Chain",
    "Tola Mansaraut",
    "Tola Pairamatihana",
    "Warisaliganj",
    "Yehiapur",
  ],
 
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Ramagundam",
    "Khammam",
    "Mahbubnagar",
    "Mancherial",
    "Adilabad",
    "Suryapet",
    "Jagtial",
    "Miryalaguda",
    "Nirmal",
    "Kamareddy",
    "Kothagudem",
    "Bodhan",
    "Palwancha",
    "Mandamarri",
    "Koratla",
    "Sircilla",
    "Tandur",
    "Siddipet",
    "Wanaparthy",
    "Kagaznagar",
    "Gadwal",
    "Sangareddy",
    "Bellampalle",
    "Bhongir",
    "Vikarabad",
    "Jangaon",
    "Bhadrachalam",
    "Bhainsa",
    "Farooqnagar",
    "Medak",
    "Narayanpet",
    "Sadasivpet",
    "Yellandu",
    "Manuguru",
    "Kyathampalle",
    "Nagarkurnool",
  ],
  Meghalaya: ["Shillong", "Tura", "Nongstoin"],
  "Himachal Praddesh": ["Manali"],
  "Arunachal Pradesh": ["Naharlagun", "Pasighat"],
  Goa: ["Marmagao", "Panaji", "Margao", "Mapusa"],
  "West Bengal": [
    "Abhirampur",
    "Ahmadpur",
    "Aiho",
    "Aistala",
    "Ajodhya Nagar",
    "Ajodhyanagar",
    "Alikhoja",
    "Alipur",
    "Alipur",
    "Alipur (Alipore)",
    "Alipurduar",
    "Alipurduar Railway Junction",
    "Amalhara",
    "Amarshi Kasba",
    "Ambhua",
    "Amkula",
    "Amlagora",
    "Amlajora",
    "Amodghata",
    "Amta",
    "Amtala",
    "Anantabati",
    "Anantapur",
    "Anarbaria",
    "Andal (Gram)",
    "Andul",
    "Ankurhati",
    "Anulia",
    "Anup Nagar",
    "Arambag",
    "Argari",
    "Arjunpur",
    "Arra",
    "Arra",
    "Asansol",
    "Ashadtalya",
    "Ashokenagar Kalyangarh (Ashoknagar)",
    "Asuti",
    "Aurangabad",
    "Babanpur",
    "Bablari Dewanganj",
    "Badamtam Tea Garden",
    "Badhagachhi",
    "Badkulla",
    "Baduria",
    "Bagbari",
    "Bagnan",
    "Bagula",
    "Baharu",
    "Bahir Sarbamangala",
    "Bahula",
    "Baidyabati",
    "Baidyanathpur",
    "Bairatisal",
    "Baisguri",
    "Baksa",
    "Baksinagar",
    "Baktarnagar",
    "Balarambati",
    "Balarampota",
    "Balarampur",
    "Balarampur",
    "Baliadanga",
    "Balibhara",
    "Balichak",
    "Balihati",
    "Ballavpur",
    "Bally",
    "Bally",
    "Baluhati",
    "Balurghat",
    "Bamangachhi",
    "Bamangram",
    "Bamanpukur",
    "Bamna",
    "Bamunara",
    "Bamunari",
    "Banagram",
    "Banarhat Tea Garden",
    "Bandhail",
    "Bandipur",
    "Bandoan",
    "Baneshwarpur M P",
    "Baneswar",
    "Bangalpur",
    "Bangsidharpur M P",
    "Ban Harishpur",
    "Baniara",
    "Baniban",
    "Baniban Jagadishpur",
    "Banjetia",
    "Bankra",
    "Bankra",
    "Bankul",
    "Bankura",
    "Bansberia",
    "Banshra",
    "Banshra",
    "Banupur",
    "Bara",
    "Bara Bamonia",
    "Barabazar",
    "Bara Jumla",
    "Baranagar",
    "Barasat",
    "Bara Suzapur",
    "Barda",
    "Barddhaman (Bardhaman)",
    "Bargachhia",
    "Bargachhia",
    "Barijhati",
    "Barijpur",
    "Barjora",
    "Barkalikapur",
    "Barrackpore",
    "Barrackpur Cantonment",
    "Barua",
    "Barua Gopalpur",
    "Baruihuda",
    "Baruipara",
    "Baruipur",
    "Baruipur (P)",
    "Barunda",
    "Basai",
    "Basantapur",
    "Basanti",
    "Basantia",
    "Basirhat",
    "Baska",
    "Basudebpur",
    "Basudebpur",
    "Batika",
    "Batul",
    "Bayarsing",
    "Begampur",
    "Begari",
    "Beharia",
    "Beldanga",
    "Beldubi",
    "Belebathan",
    "Benia Gram",
    "Benjanhari Acharial",
    "Benudia",
    "Berandari Bagaria",
    "Berhampore (Baharampur)",
    "Betpuli",
    "Bhabki",
    "Bhadreswar",
    "Bhagabatipur",
    "Bhandardaha",
    "Bhandar Gachha",
    "Bhangar Raghunathpur",
    "Bhangri Pratham Khanda",
    "Bhanowara",
    "Bhasa",
    "Bhasaipaikar",
    "Bhatenda",
    "Bhatpara",
    "Bhimram",
    "Bholar Dabri",
    "Bidhannagar",
    "Bidyadharpur",
    "Bikihakola",
    "Bilandapur",
    "Bilkanda",
    "Bilpahari",
    "Binnaguri",
    "Bipra Noapara",
    "Bira",
    "Birlapur",
    "Birnagar",
    "Bishnupur",
    "Bishnupur",
    "Bishnupur",
    "Bishnupur",
    "Bolpur",
    "Bongaon (Bangaon)",
    "Bora Gagangohalia",
    "Borai",
    "Bowali",
    "Brindabanpur",
    "Budbud",
    "Budge Budge",
    "Buita",
    "Cart Road",
    "Chachanda",
    "Chak Alampur",
    "Chakapara",
    "Chak Bankola",
    "Chak Banshberia (Chak Bansberia)",
    "Chak Barbaria",
    "Chak Baria",
    "Chak Bhrigu",
    "Chakchaka",
    "Chakdaha",
    "Chak Enayetnagar",
    "Chakiabhita",
    "Chak Kanthalia",
    "Chak Kashipur",
    "Chak Meghoan",
    "Chalsa Mahabari",
    "Champahati",
    "Champdani",
    "Chamrail",
    "Chanchal",
    "Chandannagar",
    "Chandapur Champagachhi",
    "Chanddandaha",
    "Chandipur",
    "Chandpala Anantapathpur",
    "Chandpara",
    "Chandpur",
    "Chandpur M",
    "Chandrakona",
    "Chandrapur",
    "Chandrapur",
    "Chandrapur",
    "Chanduria",
    "Chapari",
    "Chapra",
    "Char Brahmanagar",
    "Charka",
    "Char Maijdia",
    "Chaspara",
    "Chata Kalikapur",
    "Chatta Baria",
    "Chaulia",
    "Chechakhata",
    "Chekya",
    "Chelad",
    "Chhatianmor",
    "Chhekati",
    "Chhora",
    "Chhota Laukuthi",
    "Chhota Suzapur",
    "Chikanpara",
    "Chikrand",
    "Chinchuria",
    "Chittaranjan",
    "Chong Ghurali",
    "Chongtong Tea Garden",
    "Chopa",
    "Contai",
    "Cooper's Camp",
    "Dabgram",
    "Dafahat",
    "Dafarpur",
    "Dafarpur",
    "Dainhat",
    "Dakra",
    "Dakshin Bagdogra",
    "Dakshin Baguan",
    "Dakshin Chatra",
    "Dakshin Jhapardaha",
    "Dakshin Khagrabari",
    "Dakshin Khanda",
    "Dakshin Odlabari",
    "Dakshin Rajyadharpur",
    "Dakshin Raypur",
    "Dakshin Santoshpur",
    "Dakshin Santoshpur",
    "Dalkhola",
    "Dalurband",
    "Dandirhat",
    "Danga",
    "Dankuni",
    "Darappur",
    "Darjiling (Darjeeling)",
    "Daulatpur",
    "Deara",
    "Debipur",
    "Debipur",
    "Deora",
    "Deora",
    "Deulgram",
    "Deuli",
    "Deulpur",
    "Dhaliabari",
    "Dhamua",
    "Dhania",
    "Dhanyakuria",
    "Dharmapuram",
    "Dhatrigram",
    "Dhola",
    "Dhuilya",
    "Dhulagari",
    "Dhulasimla",
    "Dhulian",
    "Dhusaripara",
    "Diamond Harbour",
    "Digha",
    "Digha",
    "Dighirpar",
    "Dignala",
    "Dihi Kalas",
    "Dihimandalghat",
    "Dinga Khola",
    "Dinhata",
    "Dogachhia",
    "Domjur",
    "Domohani",
    "Donalia",
    "Dubra",
    "Dubrajpur",
    "Dum Dum",
    "Dumriguri",
    "Dungra Khasmahal",
    "Durganagar",
    "Durgapur",
    "Durllabhganj",
    "Dwari Geria",
    "Egara",
    "Egra",
    "Ekabbarpur",
    "Eksara",
    "English Bazar",
    "Erashal",
    "Falakata Barrage Township",
    "Fatehpur",
    "Fatellapur",
    "Fatepur",
    "Gabberia",
    "Gadigachha",
    "Gairkata",
    "Gangadharpur",
    "Gangadharpur",
    "Gangapur",
    "Gangarampur",
    "Gangnapur",
    "Gangni",
    "Gangpur",
    "Ganye Gangadharpur",
    "Garalgachha",
    "Garbeta",
    "Garh Kamalpur",
    "Garia",
    "Garshyamnagar",
    "Garulia",
    "Gaur Daha",
    "Gayespur",
    "Geni",
    "Ghatal",
    "Ghola Noapara",
    "Ghoraberia",
    "Ghoralia",
    "Ghorsala",
    "Ghosal Chak",
    "Ghuni",
    "Ghutgarya",
    "Ging Tea Garden",
    "Giria",
    "Goaljan",
    "Goasafat",
    "Gobardanga",
    "Gobindapur",
    "Goda",
    "Gondalpara",
    "Gopalpur",
    "Gopalpur",
    "Gopalpur",
    "Gopinathpur",
    "Gopjan",
    "Gora Bazar",
    "Guma",
    "Guriahati",
    "Guskara",
    "Hafania",
    "Halalpur Krishnapur",
    "Haldia",
    "Haldibari",
    "Halisahar",
    "Halyan",
    "Hansghara",
    "Hanskunda",
    "Hanspukuria",
    "Haora (Howrah)",
    "Harharia Chak",
    "Haridasmati",
    "Hariharpur",
    "Harinadibhastsala",
    "Harindanga",
    "Haringhata Farm",
    "Haripur",
    "Harirampur",
    "Harishpur",
    "Hasimnagar",
    "Hatgachha",
    "Hatsimla",
    "Hijuli",
    "Hijuli",
    "Hincha Gerya",
    "Hindusthan Cables Town (Rupnarainpur)",
    "Hingalganj",
    "Hirapur",
    "Hugli-Chinsurah (Hugli-Chuchura)",
    "Hutmura",
    "Ichhapur (Ichapore)",
    "Ichchhapor Defence Estate",
    "Ichhlampur",
    "Ilambazar",
    "Islampur",
    "Islampur",
    "Itahari",
    "Itinda",
    "Jadupur",
    "Jafarpur",
    "Jafrabad",
    "Jagadanandapur",
    "Jagadishpur",
    "Jagannathpur",
    "Jagatballavpur",
    "Jagatnagar",
    "Jagijhora Barabak",
    "Jagtaj",
    "Jala Kendua",
    "Jalalpur",
    "Jallabad",
    "Jalpaiguri",
    "Jaluidanga",
    "Jamuria",
    "Janai",
    "Jangal",
    "Jangalpara",
    "Jangipur",
    "Jateshwar",
    "Jatragachhi",
    "Jaygaon (Jaigaon)",
    "Jaykrishnapur",
    "Jaykrishnapur",
    "Jaynagar",
    "Jaynagar Mazilpur",
    "Jaypur",
    "Jaypur Bil",
    "Jemari (J.K. Nagar Township)",
    "Jetia",
    "Jhalda",
    "Jhalda",
    "Jhangra",
    "Jhanti Pahari",
    "Jhargram",
    "Jhorhat",
    "Jiaganj-Azimganj",
    "Jirat",
    "Joka",
    "Jot Kamal",
    "Kaijuri",
    "Kajora",
    "Kakdihi",
    "Kakramari",
    "Kalaikunda",
    "Kalara",
    "Kaliaganj",
    "Kalikapota",
    "Kalikapur",
    "Kalikapur Barasat",
    "Kalimpong",
    "Kalipur",
    "Kalkut",
    "Kalna",
    "Kalua",
    "Kalyani",
    "Kalyanpur",
    "Kamalapur",
    "Kamarhati",
    "Kamat Phulbari",
    "Kamgachhi",
    "Kamranga",
    "Kanaipur",
    "Kanaipur",
    "Kanchrapara",
    "Kandi",
    "Kanganbaria",
    "Kanki",
    "Kanksa",
    "Kankuria",
    "Kanpur",
    "Kantaberia",
    "Kantaliya",
    "Kantaranguri",
    "Kantlia",
    "Kapashanria",
    "Karari Chandpur",
    "Karia",
    "Karidhya",
    "Karimpur",
    "Kasba",
    "Kashimnagar",
    "Kasim Bazar (Cossimbazar)",
    "Katwa",
    "Kaugachhi",
    "Kenda",
    "Kendra Khottamdi",
    "Kendua",
    "Kendua",
    "Keota",
    "Kesabpur",
    "Khadalgobra",
    "Khadinan",
    "Khagrabari",
    "Khajutti",
    "Khalia",
    "Khalisani",
    "Khandra",
    "Khanpur",
    "Khantora",
    "Kharagpur",
    "Kharagpur Railway Settlement",
    "Kharar",
    "Kharia",
    "Kharibari",
    "Kharimala Khagrabari",
    "Kharisha",
    "Kharsarai",
    "Khasjalalsi",
    "Khatra",
    "Khidirpur (Kidderpore)",
    "Khodarampur",
    "Khodar Bazar",
    "Khorddabamonia",
    "Koch Bihar (Cooch Behar)",
    "Kodalia",
    "Kohetpur",
    "Kokapur",
    "Kola",
    "Kolaghat",
    "Kolkata [Calcutta]",
    "Komaralingam",
    "Konardihi",
    "Konnagar",
    "Kotbar",
    "Kotulpur",
    "Koyra",
    "Kriparampur",
    "Krishna Chandrapur",
    "Krishnanagar",
    "Krishnapur",
    "Krishnapur",
    "Krishna Sali",
    "Kshidirpur",
    "Kshirpai (Khirpai)",
    "Kulberia",
    "Kuldanga",
    "Kulia",
    "Kulihanda",
    "Kulitapara",
    "Kulti",
    "Kumirmora",
    "Kunustara",
    "Kurseong",
    "Kusadanga",
    "Labhpur",
    "Lagda",
    "Lalman",
    "Lalpur",
    "Lalpur",
    "Lapara",
    "Laskarpara",
    "Lataguri",
    "Ledisol",
    "Madanpur",
    "Madhusudanpur",
    "Madhyamgram",
    "Madna",
    "Magrahat",
    "Mahadeb Nagar",
    "Mahal",
    "Mahendrapur",
    "Maheshtala",
    "Mahiari",
    "Mahira",
    "Mahishrekha",
    "Mainaguri",
    "Majdia",
    "Majaragollappatti",
    "Majiara",
    "Makardaha",
    "Makhal Tala",
    "Mallik Bagan",
    "Mallikpur",
    "Mamrejpur",
    "Manbazar",
    "Mandarbani",
    "Mangalbari",
    "Mangarjung Tea Garden (Nagri)",
    "Manikpur",
    "Manirampur",
    "Mansinhapur",
    "Maricha",
    "Masat",
    "Masat",
    "Masila",
    "Maslandapur",
    "Mathabhanga",
    "Mathapari",
    "Mathurapur",
    "Mathurapur",
    "Matialihat",
    "Mechiabasti",
    "Medinipur (Midnapore)",
    "Mekliganj (Mekhliganj)",
    "Memari",
    "Mihitikri",
    "Milki",
    "Minakhan",
    "Mira",
    "Mirdhanga",
    "Mirik",
    "Mirjapur",
    "Mirzapur",
    "Mirzapur",
    "Mithipur",
    "Mohanpur",
    "Mohanpur",
    "Mugkalyan",
    "Muragachha",
    "Murarai",
    "Murgathaul",
    "Murshidabad",
    "Murulia",
    "Nababpur",
    "Nabadiganta Industrial Township",
    "Nabadwip",
    "Nabaghanapur",
    "Nabagram",
    "Nabagram Colony",
    "Naba Kola",
    "Nabghara",
    "Nabgram",
    "Nachhratpur Katabari",
    "Nadabhanga",
    "Nagar Changrabandha",
    "Nagdaha",
    "Nahazari",
    "Nainan",
    "Nait",
    "Naldanga",
    "Nalhati",
    "Namajgram",
    "Nandambakkam",
    "Nandigram",
    "Nari",
    "Nasaratpur",
    "Nasibpur",
    "Nasra",
    "Natibpur",
    "Naul",
    "Nawapara (Nuapada)",
    "Nayabahadurpur",
    "Nazirpur",
    "Nebadhai Duttapukur",
    "New Barrackpore",
    "Nibra",
    "Nimpith",
    "Noapara",
    "Nokpul",
    "North Barrackpore (North Barrackpur)",
    "North Dumdum",
    "Nrisinghapur",
    "Oadipur",
    "Odlabari",
    "Old Malda",
    "Ondal",
    "Osmanpur",
    "Osmanpur",
    "Pairagachha",
    "Palashban",
    "Palladaha",
    "Paltapara",
    "Panchghara",
    "Panchghara",
    "Panchla",
    "Panchpara",
    "Pandua",
    "Pangachhiya",
    "Paniara",
    "Panihati",
    "Panpara",
    "Panskura",
    "Panuhat",
    "Panuria",
    "Parangarpar",
    "Paraniputhur",
    "Parasia",
    "Parbbatipur",
    "Par Beliya",
    "Par Patiram",
    "Paschim Bainan",
    "Paschimbhatjangla",
    "Paschim Gazipur",
    "Paschim Jitpur",
    "Paschim Khalna",
    "Paschim Punropara",
    "Paschim Rajyadharpur",
    "Pashchim Khalna",
    "Patdaha",
    "Patharberia",
    "Patihal",
    "Patuli",
    "Patulia",
    "Petua",
    "Phulia",
    "Piarinagar",
    "Poali",
    "Podara",
    "Prayagpur",
    "Priyanagar",
    "Pujali",
    "Punglia",
    "Purba Bishnupur M",
    "Purba Ranaghat",
    "Purbba Narayanpur",
    "Purbba Tajpur (Purba Tajpur)",
    "Puruliya (Purulia)",
    "Purusottampur",
    "Radhanagar",
    "Radhapur",
    "Raghabpur",
    "Raghabpur",
    "Raghudebbati",
    "Raghudebpur",
    "Raghunathchak",
    "Raghunathpur",
    "Raghunathpur",
    "Raghunathpur (PS-Dankuni)",
    "Raghunathpur (PS-Magra)",
    "Raigachhi",
    "Raiganj",
    "Raipur",
    "Raipur Bazar",
    "Rajapur",
    "Rajarhat Gopalpur",
    "Rajbalhat",
    "Rajnagar",
    "Rajpur Sonarpur",
    "Ramakantapur",
    "Ramanathpur",
    "Ramchandrapur",
    "Ramchandrapur",
    "Ramchandrapur (in: Thakurpukur Mahestola subdistrict)",
    "Ramchandrapur (in: Sonarpur subdistrict)",
    "Rameswarpur",
    "Ramjibanpur",
    "Ramkrishnapur",
    "Ramnagar",
    "Ramnagar",
    "Rampurhat",
    "Ranaghat",
    "Ranaghat",
    "Rangabhita",
    "Raniganj",
    "Ratibati",
    "Raynagar",
    "Rekjuani",
    "Rishra",
    "Rishra",
    "Rongmook Ceder Tea Garden",
    "Rudrapur",
    "Ruiya",
    "Sadigachhi",
    "Sadpur",
    "Saguna",
    "Sahajadpur",
    "Sahapur",
    "Sahapur",
    "Sahebganj",
    "Sahebpur",
    "Sainthia",
    "Salar",
    "Salipur",
    "Saltor",
    "Samali",
    "Samuktola",
    "Sangrampur",
    "Sankarpur",
    "Sankrail",
    "Sankrailjala",
    "Santaldih Thermal Power Project-Town",
    "Santoshpur",
    "Sarenga",
    "Sarpi",
    "Sashpur",
    "Satigachha",
    "Sehara",
    "Serampore",
    "Serpur",
    "Shankara",
    "Shankhanagar",
    "Shantipur",
    "Shashati",
    "Shibalaya",
    "Shilda",
    "Shimulpur",
    "Shuvararah",
    "Shyamdhan",
    "Shyampur",
    "Shyampur",
    "Sibdanga Badarpur",
    "Sibnagar",
    "Siduli",
    "Silampur",
    "Siliguri",
    "Simhat",
    "Simla",
    "Simlapal",
    "Simurali",
    "Singtam Tea Garden",
    "Singur",
    "Sirakol",
    "Sirsha",
    "Sisha-Jumrha",
    "Sobhaganj",
    "Solgohalia",
    "Sonada Khasmahal",
    "Sonamukhi",
    "Sonatala",
    "Sonatikiri",
    "Sonda",
    "South Dumdum",
    "Srikantabati",
    "Srimantapur",
    "Sripur",
    "Srirampur",
    "Suri",
    "Surul",
    "Swangrampur",
    "Taherpur",
    "Taki",
    "Talbandha",
    "Taldi",
    "Tamluk",
    "Tarakeswar",
    "Tari",
    "Teghari",
    "Teghari",
    "Tehatta",
    "Teorkhali",
    "Tentulkuli",
    "Tiorkhali",
    "Titagarh",
    "Topsi",
    "Tufanganj",
    "Tulshighata",
    "Udang",
    "Ukhra",
    "Ula",
    "Uluberia",
    "Usthi",
    "Uttampur",
    "Uttar Bagdogra",
    "Uttar Bagundi",
    "Uttar Bishnupur",
    "Uttar Durgapur",
    "Uttar Goara",
    "Uttar Jhapardaha",
    "Uttar Kalas",
    "Uttar Kamakhyaguri",
    "Uttar Kusum",
    "Uttar Latabari",
    "Uttar Madarihat",
    "Uttar Mahammadpur",
    "Uttarpara Kotrung",
    "Uttarparanij",
    "Uttar Pirpur",
    "Uttar Raypur",
    "Uttar Satali",
  ],
    "Andaman and Nicobar Islands": ["Port Blair"],
};

export default stateCityData;
