export const universityOptions = [
  "Aligarh Muslim University (AMU)",
  "Amity University",
  "Amrita Vishwa Vidyapeetham",
  "Andhra University",
  "Anna University",
  "Awadhesh Pratap Singh University, Rewa",
  "Baba Ghulam Shah Badshah University, Rajouri",
  "Banaras Hindu University (BHU)",
  "Barkatullah University, Bhopal",
  "Bastar Vishwavidyalaya, Jagdalpur",
  "Bharathiar University",
  "Bharati Vidyapeeth College of Engineering, Pune",
  "Bharati Vidyapeeth University",
  "Bhavnagar University, Bhavnagar",
  "Birla Institute of Technology and Science (BITS), Pilani",
  "Calcutta University",
  "Central University of Bihar",
  "Central University of Gujarat",
  "Central University of Haryana",
  "Central University of Himachal Pradesh",
  "Central University of Jammu",
  "Central University of Jharkhand",
  "Central University of Karnataka",
  "Central University of Kashmir, Ganderbal",
  "Central University of Kerala",
  "Central University of Odisha",
  "Central University of Punjab",
  "Central University of Rajasthan",
  "Central University of Tamil Nadu",
  "Chandigarh University",
  "Chhattisgarh Kamdhenu Vishwavidyalaya, Durg",
  "Chhattisgarh Swami Vivekanand Technical University, Bhilai",
  "Christ University, Bangalore",
  "Cluster University of Jammu",
  "Cluster University of Srinagar",
  "COEP Technological University",
  "Datta Meghe Institute of Medical Sciences",
  "Dayananda Sagar University, Bangalore",
  "Devi Ahilya Vishwavidyalaya (DAVV), Indore",
  "Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT), Gandhinagar",
  "Dr. Babasaheb Ambedkar Marathwada University",
  "Dr. Babasaheb Ambedkar Open University",
  "Dr. Babasaheb Ambedkar Technological University",
  "Dr. B.R. Ambedkar Open University, Hyderabad",
  "Dr. D.Y. Patil Institute of Technology, Pimpri",
  "Dr. D.Y. Patil Vidyapeeth",
  "Dr. Harisingh Gour Vishwavidyalaya (Central University), Sagar",
  "Dr. Panjabrao Deshmukh Krishi Vidyapeeth",
  "EFL University Hyderabad",
  "Fr. Conceicao Rodrigues College of Engineering",
  "Gautam Buddha University",
  "GITAM University Hyderabad Campus",
  "Gondwana University",
  "Government College of Engineering, Amravati",
  "Government College of Engineering, Karad",
  "Gujarat State University",
  "Gujarat Technological University, Ahmedabad",
  "Gujarat University",
  "Gujarat University, Ahmedabad",
  "Guru Gobind Singh Indraprastha University",
  "Guru Nanak Dev University",
  "Hemchand Yadav Vishwavidyalaya, Durg",
  "Hemchandracharya North Gujarat University, Patan",
  "Hidayatullah National Law University, Raipur",
  "Homi Bhabha National Institute",
  "ICFAI Foundation for Higher Education (IFHE), Hyderabad",
  "IIT Bhilai",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Dharwad",
  "IIT Goa",
  "IIT Gandhinagar",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT Hyderabad (IIT Hyderabad)",
  "IIT Indore",
  "IIT Jodhpur",
  "IIT Jammu",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Madras",
  "IIT Mandi",
  "IIT Palakkad",
  "IIT Patna",
  "IIT Ropar",
  "IIT Tirupati",
  "IIT Varanasi (BHU)",
  "Indian Institute of Information Technology (IIIT) Bhopal",
  "Indian Institute of Information Technology, Nagpur",
  "Indian Institute of Management Ahmedabad",
  "Indian Institute of Management Amritsar",
  "Indian Institute of Management Bangalore",
  "Indian Institute of Management Bodh Gaya",
  "Indian Institute of Management Calcutta",
  "Indian Institute of Management Indore",
  "Indian Institute of Management Indore (IIM Indore)",
  "Indian Institute of Management Jammu",
  "Indian Institute of Management Kashipur",
  "Indian Institute of Management Kozhikode",
  "Indian Institute of Management Lucknow",
  "Indian Institute of Management Nagpur",
  "Indian Institute of Management Raipur",
  "Indian Institute of Management Ranchi",
  "Indian Institute of Management Rohtak",
  "Indian Institute of Management Sambalpur",
  "Indian Institute of Management Shillong",
  "Indian Institute of Management Sirmaur",
  "Indian Institute of Management Trichy",
  "Indian Institute of Management Udaipur",
  "Indian Institute of Management Visakhapatnam",
  "Indian Institute of Science (IISc)",
  "Indian Institute of Science (IISc), Bangalore",
  "Indian Institute of Science Education and Research (IISER) Bhopal",
  "Indian Institute of Technology Bhilai (IIT Bhilai)",
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Delhi",
  "Indian Institute of Technology Gandhinagar",
  "Indian Institute of Technology Guwahati",
  "Indian Institute of Technology Hyderabad",
  "Indian Institute of Technology Indore (IIT Indore)",
  "Indian Institute of Technology Jodhpur",
  "Indian Institute of Technology Kanpur",
  "Indian Institute of Technology Kharagpur",
  "Indian Institute of Technology Madras",
  "Indian Institute of Technology Mandi",
  "Indian Institute of Technology Patna",
  "Indian Institute of Technology Roorkee",
  "Indian Institute of Technology Ropar",
  "Indian Institute of Technology Tirupati",
  "Indian Institute of Technology Varanasi (BHU)",
  "Indian Statistical Institute",
  "Indira Gandhi Institute of Technology",
  "Indira Gandhi Krishi Vishwavidyalaya, Raipur",
  "Indira Gandhi National Open University",
  "Indira Gandhi National Tribal University, Amarkantak",
  "Institute of Chemical Technology",
  "International Institute of Information Technology Hyderabad (IIIT Hyderabad)",
  "IIIT Allahabad",
  "IIIT Bhubaneswar",
  "IIIT Dharwad",
  "IIIT Guwahati",
  "IIIT Hyderabad",
  "IIIT Indore",
  "Islamic University of Science and Technology, Awantipora",
  "Jadavpur University",
  "Jain University, Bangalore",
  "Jawaharlal Nehru Centre for Advanced Scientific Research (JNCASR), Bangalore",
  "Jawaharlal Nehru Technological University",
  "Jawaharlal Nehru Technological University Hyderabad (JNTUH)",
  "Jawaharlal Nehru University (JNU)",
  "Jiwaji University, Gwalior",
  "JSS Academy of Higher Education and Research",
  "K.J. Somaiya College of Engineering",
  "Kalasalingam Academy of Research and Education",
  "Kalinga Institute of Industrial Technology (KIIT)",
  "Karnataka State Open University",
  "Karnataka State Open University, Mysuru",
  "Kerala University",
  "KL Deemed to be University",
  "Krishna Vishwa Vidyapeeth",
  "Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya, Raipur",
  "Kurukshetra University",
  "Lovely Professional University",
  "Maharaja Chhatrasal Bundelkhand University, Chhatarpur",
  "Maharaja Sayajirao University of Baroda, Vadodara",
  "Mahatma Gandhi Chitrakoot Gramodaya Vishwavidyalaya, Chitrakoot",
  "Mahatma Gandhi University",
  "Mahatma Phule Krishi Vidyapeeth",
  "Makhanlal Chaturvedi National University of Journalism, Bhopal",
  "Manipal Academy of Higher Education (MAHE)",
  "Manipal Academy of Higher Education (MAHE), Manipal",
  "Mangalore University, Mangalore",
  "Maulana Azad National Institute of Technology (MANIT) Bhopal",
  "Maulana Azad National Urdu University",
  "Maulana Azad National Urdu University",
  "MIT World Peace University",
  "Mizoram University",
  "Mumbai Technical University",
  "Nagaland University",
  "NALSAR University of Law, Hyderabad",
  "Nalanda Open University",
  "National Institute of Technology Karnataka",
  "National Institute of Technology Raipur (NIT Raipur)",
  "National Institute of Technology Rourkela",
  "National Institute of Technology Srinagar (NIT Srinagar)",
  "National Institute of Technology Tiruchirappalli",
  "National Law University Delhi",
  "National Law University Jodhpur",
  "Nanded University",
  "Nirma University, Ahmedabad",
  "Osmania University, Hyderabad",
  "Pandit Deendayal Energy University (PDEU), Gandhinagar",
  "Pandit Deendayal Petroleum University",
  "Pandit Ravishankar Shukla University, Raipur",
  "Pandit S.N. Shukla University, Shahdol",
  "Patna University",
  "PES University, Bangalore",
  "Pt. Deendayal Upadhyay Memorial Health Sciences and Ayush University, Raipur",
  "Pt. Sundarlal Sharma (Open) University, Bilaspur",
  "Punjab Agricultural University",
  "Panjab University",
  "Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV), Bhopal",
  "Rajiv Gandhi University",
  "Rajiv Gandhi University of Health Sciences",
  "Rajiv Gandhi University of Health Sciences, Bangalore",
  "Rajarambapu Institute of Technology",
  "Rani Durgavati Vishwavidyalaya, Jabalpur",
  "Rashtrasant Tukadoji Maharaj Nagpur University",
  "S.R.T.M. University",
  "Sandip University, Nashik",
  "Sanvidhan College of Management",
  "Sant Gadge Baba Amravati University",
  "Sardar Patel University, Vallabh Vidyanagar",
  "Sardar Vallabhbhai National Institute of Technology",
  "SASTRA Deemed University",
  "Saurashtra University, Rajkot",
  "Savitribai Phule Pune University",
  "Shaheed Mahendra Karma Vishwavidyalaya, Jagdalpur",
  "Sher-e-Kashmir University of Agricultural Sciences and Technology of Jammu (SKUAST-J), Jammu",
  "Sher-e-Kashmir University of Agricultural Sciences and Technology of Kashmir (SKUAST-K), Srinagar",
  "Shivaji College",
  "Shivaji Science College",
  "Shivaji University",
  "Shreemati Nathibai Damodar Thackersey Women's University",
  "Sikkim Manipal University",
  "Sinhgad College of Engineering",
  "Siksha 'O' Anusandhan",
  "Sri Ramachandra Institute of Higher Education and Research",
  "Sri Venkateswara University",
  "Swami Vivekanand University, Sagar",
  "Tata Institute of Fundamental Research",
  "Tata Institute of Fundamental Research, Hyderabad",
  "Tata Institute of Social Sciences",
  "Tezpur University",
  "Thapar Institute of Engineering and Technology",
  "Tilak Maharashtra Vidyapeeth",
  "Tripura University",
  "University of Allahabad",
  "University of Calcutta",
  "University of Calicut",
  "University of Delhi (DU)",
  "University of Hyderabad",
  "University of Jammu, Jammu",
  "University of Kashmir, Srinagar",
  "University of Lucknow",
  "University of Madras",
  "University of Mumbai",
  "University of Mysore",
  "University of Mysore, Mysuru",
  "University of Rajasthan",
  "University of Science and Technology Meghalaya",
  "Veer Narmad South Gujarat University, Surat",
  "Vellore Institute of Technology (VIT)",
  "Vidyapeeth Arts, Science and Commerce College",
  "Visva Bharati University",
  "Visvesvaraya Technological University (VTU), Belagavi",
  "Vishwakarma Institute of Information Technology",
  "Vishwakarma Institute of Technology",
  "Vishwakarma University",
  "Vasantrao Naik Marathwada Krishi Vidyapeeth",
  "Walchand College of Engineering",
  "West Bengal State University",
  "West Bengal University of Technology",
  "Yashwantrao Chavan Maharashtra Open University",
  "Private University",
  "Other",
  "Other Maharashtra Universities"
];
