export const universityOptions = [
  // 50 Maharashtra universities
  "Savitribai Phule Pune University",
  "University of Mumbai",
  "Institute of Chemical Technology",
  "Bharati Vidyapeeth University",
  "Dr. D.Y. Patil Vidyapeeth",
  "Symbiosis International University",
  "Homi Bhabha National Institute",
  "Tata Institute of Social Sciences",
  "Shivaji University",
  "Yashwantrao Chavan Maharashtra Open University",
  "SNDT Women's University",
  "Tilak Maharashtra Vidyapeeth",
  "Maharashtra University of Health Sciences",
  "Sant Gadge Baba Amravati University",
  "Rashtrasant Tukadoji Maharaj Nagpur University",
  "COEP Technological University",
  "Dr. Babasaheb Ambedkar Marathwada University",
  "Krishna Vishwa Vidyapeeth",
  "K.J. Somaiya College of Engineering",
  "Mumbai Technical University",
  "S.R.T.M. University",
  "Dr. Babasaheb Ambedkar Technological University",
  "Mahatma Phule Krishi Vidyapeeth",
  "Gondwana University",
  "D.Y. Patil University, Pune",
  "Datta Meghe Institute of Medical Sciences",
  "Vasantrao Naik Marathwada Krishi Vidyapeeth",
  "Dr. Panjabrao Deshmukh Krishi Vidyapeeth",
  "Indian Institute of Information Technology, Nagpur",
  "Shreemati Nathibai Damodar Thackersey Women's University",
  "Shivaji Science College",
  "Vidyapeeth Arts, Science and Commerce College",
  "MIT World Peace University",
  "Vishwakarma Institute of Technology",
  "Bharati Vidyapeeth College of Engineering, Pune",
  "Fr. Conceicao Rodrigues College of Engineering",
  "Rajarambapu Institute of Technology",
  "Government College of Engineering, Amravati",
  "Government College of Engineering, Karad",
  "Walchand College of Engineering",
  "Vishwakarma Institute of Information Technology",
  "Sinhgad College of Engineering",
  "Vishwakarma University",
  "Dr. D.Y. Patil Institute of Technology, Pimpri",
  "Sandip University, Nashik",
  "Sanvidhan College of Management",
  "Nanded University",
  "Shivaji College",
  "Other Maharashtra Universities",

  // 200 other Indian universities
  "Indian Institute of Science (IISc)",
  "Jawaharlal Nehru University (JNU)",
  "Jamia Millia Islamia",
  "Manipal Academy of Higher Education (MAHE)",
  "Banaras Hindu University (BHU)",
  "University of Delhi (DU)",
  "Amrita Vishwa Vidyapeetham",
  "Aligarh Muslim University (AMU)",
  "Jadavpur University",
  "Vellore Institute of Technology (VIT)",
  "SRM Institute of Science and Technology",
  "Anna University",
  "Siksha 'O' Anusandhan",
  "Kalinga Institute of Industrial Technology (KIIT)",
  "University of Hyderabad",
  "Calcutta University",
  "Birla Institute of Technology and Science (BITS), Pilani",
  "Chandigarh University",
  "Kerala University",
  "KL Deemed to be University",
  "JSS Academy of Higher Education and Research",
  "Andhra University",
  "Bharathiar University",
  "Lovely Professional University",
  "SASTRA Deemed University",
  "Thapar Institute of Engineering and Technology",
  "Kalasalingam Academy of Research and Education",
  "Amity University",
  "Central University of Tamil Nadu",
  "Central University of Gujarat",
  "Central University of Punjab",
  "Central University of Kerala",
  "Central University of Haryana",
  "Central University of Odisha",
  "Central University of Jharkhand",
  "Central University of Karnataka",
  "Central University of Himachal Pradesh",
  "Dr. Ram Manohar Lohia Avadh University",
  "Dr. Babasaheb Ambedkar Open University",
  "EFL University Hyderabad",
  "Gautam Buddha University",
  "Gujarat University",
  "Guru Gobind Singh Indraprastha University",
  "Guru Nanak Dev University",
  "Himachal Pradesh University",
  "Indira Gandhi National Open University",
  "Indira Gandhi Institute of Technology",
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Delhi",
  "Indian Institute of Technology Kanpur",
  "Indian Institute of Technology Kharagpur",
  "Indian Institute of Technology Madras",
  "Indian Institute of Technology Roorkee",
  "Indian Institute of Technology Guwahati",
  "Indian Statistical Institute",
  "Jawaharlal Nehru Technological University",
  "Karnataka State Open University",
  "Kurukshetra University",
  "Mahatma Gandhi University",
  "Manipur University",
  "Maulana Azad National Urdu University",
  "Mizoram University",
  "Nagaland University",
  "Nalanda Open University",
  "National Institute of Technology Karnataka",
  "National Institute of Technology Rourkela",
  "National Institute of Technology Tiruchirappalli",
  "National Law University Delhi",
  "National Law University Jodhpur",
  "North Eastern Hill University",
  "Panjab University",
  "Pandit Deendayal Petroleum University",
  "Patna University",
  "Punjab Agricultural University",
  "Rajiv Gandhi University",
  "Rajasthan Technical University",
  "Rajiv Gandhi University of Health Sciences",
  "Sambalpur University",
  "Sardar Vallabhbhai National Institute of Technology",
  "Sikkim Manipal University",
  "Sri Venkateswara University",
  "Sri Ramachandra Institute of Higher Education and Research",
  "Tata Institute of Fundamental Research",
  "Tezpur University",
  "Tripura University",
  "Utkal University",
  "University of Calicut",
  "University of Madras",
  "University of Rajasthan",
  "University of Science and Technology Meghalaya",
  "University of Allahabad",
  "University of Calcutta",
  "University of Lucknow",
  "University of Mysore",
  "Visva Bharati University",
  "West Bengal University of Technology",
  "West Bengal State University",
  "Central University of Jammu",
  "Central University of Rajasthan",
  "Central University of Bihar",
  "IIT Hyderabad",
  "IIT Indore",
  "IIT Bhubaneswar",
  "IIT Gandhinagar",
  "IIT Mandi",
  "IIT Patna",
  "IIT Ropar",
  "IIT Varanasi (BHU)",
  "IIT Jodhpur",
  "IIT Palakkad",
  "IIT Tirupati",
  "IIT Dhanbad",
  "IIT Jammu",
  "IIT Goa",
  "IIT Bhilai",
  "IIT Dharwad",
  "IIIT Allahabad",
  "IIIT Guwahati",
  "IIIT Hyderabad",
  "IIIT Indore",
  "IIIT Bhubaneswar",
  "IIIT Dharwad",
  "Indian Institute of Management Ahmedabad",
  "Indian Institute of Management Bangalore",
  "Indian Institute of Management Calcutta",
  "Indian Institute of Management Lucknow",
  "Indian Institute of Management Kozhikode",
  "Indian Institute of Management Indore",
  "Indian Institute of Management Shillong",
  "Indian Institute of Management Udaipur",
  "Indian Institute of Management Raipur",
  "Indian Institute of Management Ranchi",
  "Indian Institute of Management Rohtak",
  "Indian Institute of Management Trichy",
  "Indian Institute of Management Bodh Gaya",
  "Indian Institute of Management Sambalpur",
  "Indian Institute of Management Amritsar",
  "Indian Institute of Management Nagpur",
  "Indian Institute of Management Visakhapatnam",
  "Indian Institute of Management Jammu",
  "Indian Institute of Management Sirmaur",
  "Indian Institute of Management Kashipur",
  "Other"
];
