const specializationOptions = [
  "Advanced Excel and Power BI",
  "AI/ML",
  "Aptitude",
  "Aptitude (QA & LR)",
  "Aptitude Training",
  "Automation & Robotics",
  "Behavioral Soft Skills / Team Building / Campus to Corporate / POSH",
  "Chemical Technical (Campus Interview)",
  "Civil",
  "Civil Engineering",
  "Computer Science",
  "Corporate Trainer",
  "CS (Computer Science)",
  "Data Analytics - BI",
  "Data Structures and Algorithms (DSA)",
  "English",
  "Excel & Power BI",
  "Excel + AI, Finance",
  "Finance",
  "Finance, Accounts, Management, Leadership, Corporate Finance",
  "Finance, Communication Skills",
  "Food Technology and Professional Skills for Teachers and Students",
  "Generative AI and HR Soft Skills Training",
  "HR",
  "HR Soft Skills",
  "IMC (Industrial Maintenance & Control)",
  "Information Technology",
  "Industry Expert",
  "IoT (Internet of Things)",
  "Java, .NET, C, C++",
  "Java Full Stack",
  "Java MERN and AWS",
  "Leadership, Behaviors, and Communication",
  "Life Skills, Verbal Aptitude, Leadership Training",
  "Logical Reasoning and Quantitative Aptitude (LR QA Aptitude)",
  "M.Sc (Mathematics) and Aptitude Trainer with 15 Years of Experience",
  "Marketing",
  "MCA (Master of Computer Applications)",
  "Mechanical",
  "MERN Full Stack Trainer",
  "Microsoft Excel, PowerPoint, Word, Power BI, Human Resource Management",
  "MS Office and Data Analysis using Power BI",
  "Personal Finance",
  "PLC Programming & SCADA",
  "Power BI",
  "Psychology of Communication & Emotional Wellbeing",
  "Python",
  "Python, Java Full Stack, SQL, ML",
  "Sales and Marketing",
  "Sales, Marketing, Leadership, Soft Skills",
  "Soft Skills",
  "Soft Skills & Advanced Excel",
  "Soft Skills Trainer",
  "Soft Skills, Corporate Performance Improvement, Business Communication, Business English",
  "Soft Skills and Verbal Ability",
  "Technical",
  "Technical - Java Full Stack",
  "Technical - Mechanical",
  "Technical - Sales",
  "Technical - Mechatronics",
  "Technical - Civil",
  "Technical - Digital Marketing, Marketing Analytics",
  "Technical - IoT",
  "Technical - Machine Learning",
  "Technical - Computer Science",
  "Technical - Electrical",
  "Technical - Full Stack",
  "Technical - IMC",
  "Technical - MS Excel and Power BI",
  "Technical Sales",
  "Verbal Aptitude",
  "Others"
];

export default specializationOptions;
